### ISSUE TITLE
Darc doesn't purge eng/common

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#1109] opened 2018-10-23 15:51 UTC
It doesn't appear that darc purges the eng/common folder.

Intentional?

Look at 

https://github.com/dotnet/arcade-minimalci-sample/tree/master/eng/common/templates/phases

vs 

https://github.com/dotnet/arcade/tree/master/eng/common/templates/phases

The latter is supposed to be the source of truth for the eng/common folder.  It appears that about 2 months ago there was some refactoring, the `publish-build-asset.yml` and `push-build-asset.yml` went away in the Arcade repo, but they persist in Arcade-minimalci-sample repo.

@mmitche @alexperovich

**Comment by mmitche** [comment] 2018-10-23 16:02
https://github.com/dotnet/arcade/pull/1105

**Comment by jcagme** [comment] 2018-10-23 16:03
Will close this as dupe of the above mentioned #1105

**Closed by jcagme** 2018-10-23 16:03 UTC

**Comment by chcosta** [comment] 2018-10-23 16:43
Doh, guess I could have spent a few minutes lurking around before filing this.  Thank you!
