### ISSUE TITLE
Generalize codeOptimization targets

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#1397] opened 2018-11-27 18:08 UTC
The targets in codeOptimization should be generalized for use by other repositories than corefx. Currently, it stores versions and nuget package names/feeds that are specific to corefx and also directly accesses files from the PackagesDir, which makes the targets unusable by any other repository, forcing us to duplicate code in other repositories to do the same work, so we should fix it so it can be used by at least also coreclr, if not other repositories for which we may collect IBC data in the future.

**Comment by tmat** [comment] 2018-11-27 18:18
Arcade SDK already has support for IBCMerge.
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/OptimizationData.targets

Is it sufficient for CoreFX?

**Comment by ericstj** [comment] 2019-01-28 21:56
@tmat it looks like this is expecting *.IBC files but you're providing PGOs from roslyn in https://dotnet.myget.org/feed/roslyn/package/nuget/RoslynDependencies.OptimizationData.

To close this issue I'd expect some documentation that describes how to use those targets along with packages which match the conventions expected by the targets (or issues tracking the production of such packages).  As this is I think there are still missing pieces.

**Comment by tmat** [comment] 2019-01-29 02:54
The data are no longer read from the nuget package. Roslyn fetches them from Azure DevOps drop, but you can download them from anywhere and put them to `$(IbcOptimizationDataDir)`. 

We are still working on the system and will move some of the infra to Arcade since it is gonna be needed by multiple repos that insert into VS. In any case, OptimizationData.targets will remain agnostic to where the data came from and not tied to VS infrastructure in any way.

**Comment by ericstj** [comment] 2019-01-29 18:37
@tmat you're talking about this: https://github.com/dotnet/roslyn/blob/8b2707b2ca2baa4e4a5bfa16be886a3d8ed0e848/eng/build.ps1#L269-L293

Is that what you recommend as the contract between roslyn and CoreFx for ingesting the optimization data?  Why is that better than the nuget package used today?  Seems like we have mechanisms for flowing nuget packages between repositories but this would venting some way to flow the metadata to construct that drop string through BAR (as well as some new code to download and stage the files from the drop).

The transport isn't what I was trying to highlight here.  AFAIK the transport being a nuget package is working fine, and should continue to work.  The problem is that nuget has only *.PGO's and not *.IBC files and these targets only support IBC files as input.  Sorry if I'm missing something simple here.

**Comment by ericstj** [comment] 2019-02-06 19:35
> There is no need for a contract between Roslyn and CoreFX

I see.  That was the missing part of this picture for me.  The sole reason we run IBCMerge in CoreFx today is to merge in the data provided by roslyn.  In the future I agree that we can follow the pattern you've established.

For now I'll be deleting the functionality in CoreFx that merges in roslyn IBC data.

Thanks!

**Closed by ericstj** 2019-02-06 19:35 UTC

**Comment by ericstj** [comment] 2019-02-07 23:39
Correction: we also have IBC data coming from https://dotnet.myget.org/F/dotnet-core-optimization-data/api/v3/index.json but I believe I can plumb that through the arcade targets.

**Comment by adiaaida** [comment] 2019-02-08 00:24
Just an FYI: we started pushing PGO and IBC packages to https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json, so if you end up plumbing things through the arcade target, I would start pulling from there now. We are hoping to stop pushing packages to myget asap.

**Comment by tmat** [comment] 2019-02-08 00:41
@adiaaida Do these packages contain raw IBC data and the original binaries that were used for the training?

**Comment by adiaaida** [comment] 2019-02-08 15:46
@tmat They do. They are exactly the same packages that come out of myget now.
