### ISSUE TITLE
Cannot run VSIX project after a recent arcade change

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/arcade#2040] opened 2019-02-14 00:52 UTC
Whenever I try to run a VSIX project, I get the following,

![image](https://user-images.githubusercontent.com/1579269/52754455-7463f180-2faf-11e9-89c4-ffbf5c7a657a.png)

[This](https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj) is the project I was trying to start if that helps.

Is there a workaround? This is currently blocking us from investigating VS crashes

**Comment by tmat** [comment] 2019-02-14 02:19
Looking.

**Comment by tmat** [comment] 2019-02-14 02:56
Fix is in the PR. BTW, looking at the project I'd suggest a few changes:

You your own hive, e.g. "Razor". If you want to install Roslyn to that hive we have an installer that does that. Isolating each repo's extensions to their hive makes it possible to build your solution on my machine without affecting my RoslynDev hive where I might be working on unrelated changes and don't want ASP.NET suddenly start behaving differently just because I built your solution.
```
    <!-- Use the RoslynDev Experimental instance so we can mingle with local builds of Roslyn -->
    <VSSDKTargetPlatformRegRootSuffix>RoslynDev</VSSDKTargetPlatformRegRootSuffix>
```

This can be removed:
```
    <!-- Required to run the project localy -->
    <StartArguments>/rootsuffix $(VSSDKTargetPlatformRegRootSuffix) /log</StartArguments>
```

This can be removed - it's set to true if the project sets VisualStudioInsertionComponent, which it does.
```
    <IsProductComponent>true</IsProductComponent>
```

This shouldn't be needed. This property is set in Microsoft.VSSDK.BuildTools.props file of microsoft.vssdk.buildtools package. Setting it the VS from msbuild path is gonna cause inconsistencies.
```
    <!-- Update the VSToolsPath to ensure VSIX builds -->
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
```

Why does the comment say that this needs to be set for VSIX to build? If the package restores correctly it should build just fine.

**Comment by tmat** [comment] 2019-02-14 05:48
Never mind, I figured where the problem is with VSToolPath. Will include the fix in the PR.

**Closed** 2019-02-14 22:16 UTC

**Comment by ajaybhargavb** [comment] 2019-02-15 21:46
Thanks @tmat
