### ISSUE TITLE
Standardization of runtime assembly attributes

### ISSUE THREAD

**Issue by sebastienros** [dotnet/arcade#5866] opened 2020-07-30 20:29 UTC
In runtime assemblies we have these:

```
[assembly: AssemblyMetadata("RepositoryUrl", "git://github.com/dotnet/runtime")]
[assembly: AssemblyInformationalVersion("5.0.0-preview.8.20357.3+225405979bef9252208fcc71ea0552e1cb27a1e2")]
```

In ASP.NET ones:

```
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/aspnetcore")]
[assembly: AssemblyInformationalVersion("5.0.0-preview.8.20357.7")]
[assembly: AssemblyMetadata("CommitHash", "380a5679bbc5cef03471ab68bd9b2d14085ead91")]
```

I'd love to see these version metadata standardized across repositories, and probably keep it stable as long as possible, such that application that need to introspect these are broken less often.

Suggestions:
- Use different attributes for the version and the commit hash, like ASP.NET
- Standardize the repository url, probably with the `https` scheme instead of `git`

**Comment by dougbu** [comment] 2020-09-17 17:12
> Why is ASP.NET deviating from the .NET SDK and SourceLink defaults?

dotnet/aspnetcore has been configured this way from the get-go i.e. when Nate converted the repo to use Arcade, probably because the commit SHA in `[AssemblyInformationalVersion(...)]` is redundant for us (due to the `[AssemblyMetadata(CommitHash, ...)]` attribute) and to match the previous configuration. Code hasn't changed since dotnet/aspnetcore@41ce223c1cf4. See https://github.com/dotnet/aspnetcore/blob/ecaf78672a68c3139d4435afb81c9f905fb9036f/eng/Versions.props#L23-L24.

/fyi Arcade sets `$(IncludeSourceRevisionInInformationalVersion)` the same way when `$(VersionSuffixDateStamp)` is empty i.e. outside official builds. See https://github.com/dotnet/arcade/blob/4873d157a8f34f8cc7e28b3f9938b32c642ef542/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L150-L156

@tmat you introduced the [Assembly informational version](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md#assembly-informational-version-generation) section in the [Versioning document](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md) when you did 038fb2cb86a6 / #974 Was the choice of `[AssemblyInformationalVersion(...)]` over `[AssemblyMetadata(CommitHash, ...)]` arbitrary❔ I ask because I'd rather not make a change for change's sake at this point in 5.0.

/cc @Pilchie for his thoughts.

> Standardize the repository url, probably with the https scheme instead of git

@jkotas your comments above don't address this part of @sebastienros's suggestions.

**Comment by Pilchie** [comment] 2020-09-17 17:21
I'm in favor of having the same metadata in the same format, but don't have strong opinions on what that format is.

For the URL, that probably comes from how the build checks out the repo, no?

**Comment by dougbu** [comment] 2020-09-21 18:25
My leaning is toward leaving the `[assembly: AssemblyMetadata("CommitHash", "380a5679bbc5cef03471ab68bd9b2d14085ead91")]` bit alone but switch `$(IncludeSourceRevisionInInformationalVersion)` to `true` or remove that setting entirely.

dotnet/efcore has this problem too. It sets the property to `false` and does not provide `[AssemblyMetadata("CommitHash", ...)]`. Should remove the setting there too.

@tmat any other suggestions here or [above](https://github.com/dotnet/arcade/issues/5866#issuecomment-694374405)❔

**Comment by dougbu** [comment] 2020-09-22 00:03
PRs are now out to ensure all 3.1 and 5.0 assemblies from aspnetcore, aspnetcore-tooling, efcore, and extensions include the commit SHA in their `[AssemblyInformationalVersion]` values. aspnetcore-tooling and extensions didn't need to change. The aspnetcore and efcore fixes should be included in 3.1.10 and 5.0.rc2.

Left the extra `[AssemblyMetadata("CommitHash", ...)]` attribute in dotnet/aspnetcore assemblies alone. It's redundant but does no harm and it's read in some of our code.

**Comment by bricelam** [comment] 2020-09-22 18:28
Note, both EF6 and EF Core copy the AssemblyInformationalVersion value into a column with a max length of 32 preventing them from including the commit hash.

**Comment by dougbu** [comment] 2020-09-28 22:35
Late-ish status update: Attributes in aspnetcore assemblies now contain the commit SHA in `[AssemblyInformationalVersion]` and overall look something like
``` c#
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/aspnetcore")]
[assembly: AssemblyInformationalVersion("5.0.0-preview.8.20357.7+380a5679bbc5cef03471ab68bd9b2d14085ead91")]
[assembly: AssemblyMetadata("CommitHash", "380a5679bbc5cef03471ab68bd9b2d14085ead91")]
```

Due to the efcore database restriction on `[AssemblyInformationalVersion]` value length, I couldn't change that value but did add `CommitHash` information. Attributes in its assemblies now look something like
``` c#
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/efcore")]
[assembly: AssemblyInformationalVersion("5.0.0-preview.8.20357.7")]
[assembly: AssemblyMetadata("CommitHash", "380a5679bbc5cef03471ab68bd9b2d14085ead91")]
```

@bricelam do you have a follow-up issue to allow us to use the usual `[AssemblyInformationalVersion]` format in 6.0❔

**Comment by dougbu** [comment] 2020-09-28 22:47
@jkotas back in https://github.com/dotnet/arcade/issues/5866#issuecomment-694374405 I mentioned
>> Standardize the repository url, probably with the https scheme instead of git

> @jkotas your comments above don't address this part of @sebastienros's suggestions.

Are there plans / separate issues about using the HTTPS in the dotnet/runtime `RepositoryUrl` assembly metadata❔

FYI the problem isn't what @Pilchie suggested [above](https://github.com/dotnet/arcade/issues/5866#issuecomment-694379306):
> For the URL, that probably comes from how the build checks out the repo, no?

At least in the 'release/5.0' branch, the Checkout job e.g. https://dev.azure.com/dnceng/internal/_build/results?buildId=834340&view=logs&j=d0f7f2a6-67a3-56ad-4d55-ab8f5477a232&t=85c6aa13-a46e-555d-e9c6-025f9efee64f&l=16 uses HTTPS:
``` powershell
git remote add origin https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-runtime
```

**Comment by dougbu** [comment] 2020-09-28 22:48
@sebastienros up to you when we close this issue. I left it open primarily because the 3.1.10 changes aren't in and I'm not sure if follow-up issues are needed.

**Closed** 2020-09-28 22:50 UTC

**Comment by bricelam** [comment] 2020-09-29 17:21
> @bricelam do you have a follow-up issue to allow us to use the usual [AssemblyInformationalVersion] format in 6.0❔

@ajcvickers is this something we want to invest in?

**Comment by ajcvickers** [comment] 2020-09-29 17:24
@bricelam Do you think it has enough value to do?

**Comment by bricelam** [comment] 2020-09-29 17:29
Personally? No. All the information is now available. Having a standard format is only valuable if it becomes ubiquitous across the entire .NET ecosystem.

**Comment by ajcvickers** [comment] 2020-09-29 17:30
@bricelam Agreed.

**Comment by bricelam** [comment] 2020-09-29 17:30
Also, using three attributes is more normalized. 🤓
