### ISSUE TITLE
Symbol Publishing failing with assembly load issue

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1425] opened 2018-12-02 02:55 UTC
Symbol Publishing is failing for me with the version of `Microsoft.SymbolUploader.Build.Tasks` currently included by default with arcade (1.0.0-beta-63008-01)

Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=51062

I've update to the latest version of `Microsoft.SymbolUploader.Build.Tasks` and I'm still reproducing the same issue. 
```
2018-12-02T02:12:11.2801425Z F:\vsagent\-containerSas\38\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18579.6\tools\Publish.proj(119,5): error : Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.4.2, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
2018-12-02T02:12:11.2802536Z F:\vsagent\-containerSas\38\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18579.6\tools\Publish.proj(119,5): error :    at Microsoft.SymbolUploader.PublishOperation.<PublishFiles>d__59.MoveNext() in /_/src/Microsoft.SymbolUploader/PublishOperation.cs:line 286
2018-12-02T02:12:11.2803344Z F:\vsagent\-containerSas\38\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18579.6\tools\Publish.proj(119,5): error : --- End of stack trace from previous location where exception was thrown ---
2018-12-02T02:12:11.2803858Z F:\vsagent\-containerSas\38\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18579.6\tools\Publish.proj(119,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-02T02:12:11.2804305Z F:\vsagent\-containerSas\38\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18579.6\tools\Publish.proj(119,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-02T02:12:11.2804728Z F:\vsagent\-containerSas\38\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18579.6\tools\Publish.proj(119,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2018-12-02T02:12:11.2805207Z F:\vsagent\-containerSas\38\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18579.6\tools\Publish.proj(119,5): error :    at Microsoft.SymbolUploader.Build.Task.PublishSymbols.<ExecuteAsync>d__45.MoveNext() in /_/src/Microsoft.SymbolUploader.Build.Task/PublishSymbols.cs:line 157
```

**Comment by mikem8361** [comment] 2018-12-04 01:07
I think I know what the problem is. Not sure why it is happening now but I had to build a private “System.Net.Http.Formatting” a while back (for Desktop/net461) to change the dependency the Newtonsoft.Json to version 9.0.1 so the uploader could run under msbuild. It wasn’t strong named signed I think.  I guess all my ugly hacks come back to haunt me.

**Comment by mikem8361** [comment] 2018-12-04 01:30
The symbol uploader code (mostly borrowed from the VSO/VSTS artifacts “symbol” tool) is heavily dependent on this assembly.  I don’t have time to take out all of the usage.  It has been this way and working just fine for the last year that we have been publishing symbols with it.  I wonder what has changed (new version of msbuild or desktop runtime?)

**Comment by mikem8361** [comment] 2018-12-04 18:15
Should be fixed with symbol uploader version 1.0.0-beta-63604-05.

**Comment by tmat** [comment] 2018-12-04 18:35
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L73

**Comment by mikem8361** [comment] 2018-12-04 19:35
This will be fixed after the latest arcade SDK is picked up by the repo(s) in question.

**Closed by mikem8361** 2018-12-04 19:35 UTC
Labels: Critical

**Comment by markwilkie** [comment] 2018-12-04 22:06
Thanks @mikem8361 !
