### ISSUE TITLE
Test or infrastructure issue?

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#11355] opened 2022-10-20 18:56 UTC
In https://github.com/dotnet/runtime/pull/77132, build analysis reported infrastructure issues but the issue associated with the failure is a repo issue so there might be something wrong with how we are categorizing known issues

**Comment by missymessa** [comment] 2023-01-24 22:53
Dupe of #11293

**Closed by missymessa** 2023-01-24 22:53 UTC
