### ISSUE TITLE
Issues when signing VSIX

### ISSUE THREAD

**Issue by jakubch1** [dotnet/arcade#6239] opened 2020-09-24 11:44 UTC
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When signing VSIX I have issue that spaces/%20 are incorrectly handled by signing process. 2 examples below:
1) 
Extracting file 'Microsoft.VisualStudio.CodeCoverage.Shim.dll' from 'C:\A\1\14\s\artifacts\VSSetup\Release\Insertion\Microsoft.VisualStudio.TestTools.DynamicCodeCoverage.vsix' to 'C:\A\1\14\s\artifacts\tmp\Release\ContainerSigning\11\Contents/Team%20Tools/Dynamic%20Code%20Coverage%20Tools/coreclr/Microsoft.VisualStudio.CodeCoverage.Shim.dll'.
Tracking file 'C:\A\1\14\s\artifacts\tmp\Release\ContainerSigning\11\Contents/Team%20Tools/Dynamic%20Code%20Coverage%20Tools/coreclr/Microsoft.VisualStudio.CodeCoverage.Shim.dll' isNested=True
Caching file Microsoft.VisualStudio.CodeCoverage.Shim.dll EB72BDE17FBA05935A5B4BD5B9CF3CC39FAB2BA2D2C47D1380415E2007916DFF
Removing public sign: 'Microsoft.VisualStudio.CodeCoverage.Shim.dll'
 
C:\A\1\14\a\MicroBuild\Plugins\MicroBuild.Plugins.Signing.1.1.307\build\MicroBuild.Plugins.Signing.targets(43,5): Cannot StrongName sign the file at C:\A\1\14\s\artifacts\tmp\Release\ContainerSigning\11\Contents\Team Tools\Dynamic Code Coverage Tools\coreclr\Microsoft.VisualStudio.CodeCoverage.Shim.dll because it does not have a public key [C:\A\1\14\s\artifacts\tmp\Release\Signing\Round0.proj]

2)
Extracting file 'CodeCoverage.exe' from 'C:\A\1\14\s\artifacts\VSSetup\Release\Insertion\Microsoft.VisualStudio.TestTools.DynamicCodeCoverage.vsix' to 'C:\A\1\14\s\artifacts\tmp\Release\ContainerSigning\4\Contents/Team%20Tools/Dynamic%20Code%20Coverage%20Tools/CodeCoverage.exe'.
Tracking file 'C:\A\1\14\s\artifacts\tmp\Release\ContainerSigning\4\Contents/Team%20Tools/Dynamic%20Code%20Coverage%20Tools/CodeCoverage.exe' isNested=True
Caching file CodeCoverage.exe 7B221FD5180836C1949593EA51EDCD7C33DD94AEC126785460F77730B0C06F0E
 
29> 24.10.47.22 Warning: System.ApplicationException: C:\A\1\14\s\artifacts\tmp\Release\ContainerSigning\4\Contents\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe doesn't exist
   at Microsoft.VisualStudio.Tools.Build.SubmitterBase.SubmitFile(SignRecord record, Timeout globalTimeout, QueueFileType queueFileType)
   at Microsoft.VisualStudio.Tools.Build.ESRPClientSigner.RunSubmitAndRetrieve(List`1 records, ESRPClientSettings esrpClientSettings)
   at Microsoft.VisualStudio.Tools.Build.PRSLabSigner.RunSubmitAndRetrieve(List`1 records, ESRPClientSettings esrpClientSettings)
   at Microsoft.VisualStudio.Tools.Build.SignerBase.DoSign(Object o)

Is there an easy way to sign files before packing to VSIX and disable nested signing?

**Comment by riarenas** [comment] 2020-09-24 20:44
Triage: @jakubch1 are you still blocked on this?

**Comment by jakubch1** [comment] 2020-09-24 21:29
Yes. We are still blocked on this.

**Comment by MattGal** [comment] 2020-09-24 21:48
@chcosta is this something you can address in your current epic?

**Comment by chcosta** [comment] 2020-09-24 21:52
Probably, but that wouldn't provide the urgency needed to unblock someone.

**Comment by riarenas** [comment] 2020-09-24 21:54
Talked to @markwilkie.  We should investigate the issue as part of FR and see what it would take to fix this in signtool. 

CC @ilyas1974

**Comment by markwilkie** [comment] 2020-09-24 21:55
@ilyas1974 - could you at least look at this as part of FR please to see what's involved?

@jakubch1 - given that this isn't part of the dotnet stack proper, our ability to support this in an urgent fashion is limited.  However, we'll take a peek and with any luck it's a quick and easy fix.  Also, if you find the issue, we're happy to take a PR to arcade (which is where signtool lives)

**Comment by mmitche** [comment] 2020-10-21 19:57
@jakubch1 There's a problem with this fix: #6248

The problem is that most of the paths inside of our containers are not URLs, but Url decode will incorrectly morph some valid paths in some cases. We will then make decisions based on those new file names. Example: Any file containing + (which UrlDecode changes to a space).

Right now we hit an assert where we incorrectly assume a file will not be nested: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L242

I think this needs to be fixed in another way. Maybe the issue was that the %20's are getting dropped when generating the signing prop file?

/cc @chcosta

**Comment by jakubch1** [comment] 2020-10-22 10:29
@mmitche do you have more examples? The issue is only for '+'? Is it part of the filename or path? We could add all such examples to tests.

In our case we have to change:
Team%20Tools/Dynamic%20Code%20Coverage/netstandard2.0/ProjectOne.dll -> Team Tools/Dynamic Code Coverage/netstandard2.0/ProjectOne.dll

without this it fails. I see 2 possible solutions:

1) replace WebUtility.UrlDecode with .Replace("%20", " ")
2) Replace subfolders to random Guid. So it would create file like this:
Team%20Tools/Dynamic%20Code%20Coverage/netstandard2.0/ProjectOne.dll -> {RandomGuid}/ProjectOne.dll.
If I understand correctly real paths are still remembered by tool so those will be restored when building back original package.

@chcosta  @mmitche  what do you think?

**Comment by mmitche** [comment] 2020-10-22 14:01
The only place I saw this was with a +. But Url  The problem is that if the file name gets changed, the rest of signtool starts to fail or could do the wrong thing. When processing the nested file,  https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L697 might indicate that a file with a + in it hasn't been processed yet. But then we do UrlDecode on that, and pass it on to TrackFile. TrackFile, ExtractSignInfo, etc. will then process the file based on the incorrect file name. That could cause us to hit https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L242. Or if someone had an explicit cert specified for one of these files, we wouldn't match it correctly.

All of signtool is basically assuming that files that are being processed on disk (whether passed in to ItemsToSign or extracted and then tracked) have file names that are the same as the original. So IMO we should never extract to a different file name.

Do you have the original VSIX that has the problem? My hunch is that the fix should be in our generation of the signing.props file passed off to microbuild, not signtool's extraction code.

Btw this isn't a critical issue. The file that hits this at the moment wouldn't be signed anyway.

**Comment by jakubch1** [comment] 2020-10-23 13:33
I've rerun failing scenario with arcade version before this fix.

Let's describe whole thing:
1) In swr file we specify all paths with spaces, not %20
2) In VSIX file paths are changed to contain %20 (is this default in zip files?) but inside manifest.json the file is specified without %20: {"fileName":"/Contents/Team Tools/Dynamic Code Coverage Tools/amd64/CodeCoverage.exe","sha256":"B7BE597B9557270D8E8524A491F50AEB8FFF6CD86FA27B40DE992D120BCA38EE"
3) Logs from arcade (%20):
Extracting file 'CodeCoverage.exe' from 'C:\A\1\47\s\artifacts\VSSetup\Release\Insertion\Microsoft.VisualStudio.TestTools.DynamicCodeCoverage.vsix' to 'C:\A\1\47\s\artifacts\tmp\Release\ContainerSigning\26\Contents/Team%20Tools/Dynamic%20Code%20Coverage%20Tools/amd64/CodeCoverage.exe'.
Tracking file 'C:\A\1\47\s\artifacts\tmp\Release\ContainerSigning\26\Contents/Team%20Tools/Dynamic%20Code%20Coverage%20Tools/amd64/CodeCoverage.exe' isNested=True
4) Round0.proj still with %20:
        <FilesToSign Include="C:\A\1\47\s\artifacts\tmp\Release\ContainerSigning\26\Contents/Team%20Tools/Dynamic%20Code%20Coverage%20Tools/amd64/CodeCoverage.exe">
            <Authenticode>Microsoft400</Authenticode>
        </FilesToSign>
5) Microbuild signing is searching for paths with spaces:
Submitting C:\A\1\47\s\artifacts\tmp\Release\ContainerSigning\26\Contents\Team Tools\Dynamic Code Coverage Tools\amd64\CodeCoverage.exe for Real signing

I will make change to replace UrlDecode with Uri.UnescapeDataString. This will not modify '+'.

**Comment by jakubch1** [comment] 2020-10-26 06:56
Thanks @mmitche  for help on this. I've prepared fix which is escaping paths when generating csproj for signing: #6441 
The issue here is that msbuild is unescaping paths when reading csproj.

**Closed** 2020-10-27 22:06 UTC
Labels: First Responder
