### ISSUE TITLE
eng/common/templates/job/execute-sdl.yml should use its own pool or allow overriding pools by caller

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#3565] opened 2019-08-03 21:43 UTC
eng/common/templates/job/execute-sdl.yml should use its own pool or allow overriding pools by caller

Currently, the 'Validate Run SDL tool' task seems to use the default pool associated with the build pipeline, which may not be functional. Tasks should use their own pools, or inherit pools from the calling yml I believe. 

See here for build that's stuck: https://dev.azure.com/dnceng/internal/_build/results?buildId=293218

**Comment by JohnTortugo** [comment] 2019-08-03 22:19
@sunandabalu

**Comment by vatsan-madhavan** [comment] 2019-08-05 19:16
/cc @riarenas 

can i get an idea for when to expect a solution for this?

**Comment by markwilkie** [comment] 2019-08-05 20:14
@vatsan-madhavan - I would not consider this a blocker to adopting stages

**Comment by sunandabalu** [comment] 2019-08-05 21:05
@MattGal

**Comment by vatsan-madhavan** [comment] 2019-08-05 21:15
> I would not consider this a blocker to adopting stages

I don’t understand how this is not a blocker.

**Comment by markwilkie** [comment] 2019-08-05 21:17
If I'm understanding this correctly, this is about SDL not running correctly.  (not following exactly why, but I think that's orthogonal right now)  SDL automation is optional and not directly related to moving to stages.

**Comment by sunandabalu** [comment] 2019-08-05 21:27
I have updated the execute-sdl.yml to use its own pool like the other post-build steps, its in PR.

**Comment by JohnTortugo** [comment] 2019-08-05 22:01
@vatsan-madhavan, you can just disable SDL validation while the issue is addressed. For that, i form parameters for post-build.yml as shown below:

```
      SDLValidationParameters:
        enable: false
``

**Comment by vatsan-madhavan** [comment] 2019-08-06 02:08
Thanks, got it!

**Comment by sunandabalu** [comment] 2019-08-09 18:26
PR to add pool to execure-sdl.yml is merged. Closing this issue.

**Closed by sunandabalu** 2019-08-09 18:26 UTC

**Comment by vatsan-madhavan** [comment] 2019-08-09 18:40
@sunandabalu - thanks! we will watch out for the update and re-enable SDK validation.
