### ISSUE TITLE
Maestro dependency flow failed to trigger subscription

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#12505] opened 2023-02-09 00:41 UTC
Subscription d29ed396-31b9-4307-51a3-08d9b98d2513 failed to trigger for @MichaelSimons. Telemetry shows an exception [as seen here](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0utSE4tKMnMzytWqFEoz0gtSlXQUshILFZQSjGyTE0xtjTTNTZMstQ1MTYw1zU1TDTWNbBIsUyytEgxMjU0VgIAvcj55j8AAAA%253D/timespan/P1D). Cause is unknown. There are other similar exceptions logged, perhaps there is a wider problem. Additional context from Teams may be found [here](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1675897093526?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1675897093526&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1675897093526&allowXTenantAccess=false). Investigate!

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by dkurepa** [comment] 2023-02-09 18:40
I tried doing some investigation here but didn't get very far. The exception we're getting `Microsoft.ServiceFabric.Actors.ActorConcurrencyLockTimeoutException` means that we're sending two requests to the same actor, and the second item is timing out.
This happens when we try to call the PullRequestActor from the SubscriptionActor in https://github.com/dotnet/arcade-services/blob/b907b1e419b56d74852ecd13a7132db8e8686ddd/src/Maestro/SubscriptionActorService/SubscriptionActor.cs#L225. What's weird is this is the only request we're making to that actor, so there shouldn't be any other items in it's queue, causing this request to time out

**Comment by dkurepa** [comment] 2023-02-09 18:44
Also, this issue only appears for two subscriptions, `d29ed396-31b9-4307-51a3-08d9b98d2513` and `f5e16d6d-e643-4370-f3ed-08d8e97c775d`

**Comment by riarenas** [comment] 2023-02-10 20:50
I did some digging here when I was asked to take a quick look.

If you look at the logs for each of these stuck subscriptions, you will see that the `UpdateDependencies` operation from the `DependencyUpdater` is timing out. It seems to be happening during the coherency calculation for the repo.

As an experiment I did the following:

* Recreated one of the affected subscriptions so that we could rule out issues with the pull request actor being stuck and causing the `LockTimeoutExceptions`: I recreated the subscription from the SDK repo to the installer repo.
```
https://github.com/dotnet/sdk (.NET 8.0.1xx SDK) ==> 'https://github.com/dotnet/installer' ('main')
  - Id: f8ee08b0-6c3d-485a-6895-08db0a1df366
  - Update Frequency: EveryBuild
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags: dotnet/domestic-cat
  - Merge Policies:
    Standard
```

* Took a look at the operations from the dependency updater and from the pull request actor for the newly created subscription: [Go to Log Analytics and run query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA22Nyw3DIBAF76liRQXhDyWkiohlF9kHGwRESSQXH%252Fue29NoRm%252F2lHnAAa99rTvwJ3Ob5xpwO%252BC9cGeojXu62PNBsKQBgrJSLlhm773LGKQxwcQ7Wxm0LqgE1P4nQ2ULos%252BFXJKaojGnH2PxMmqProjrs3biDviFuW48ZtoaEI%252F8AwHl1QGoAAAA/timespan/P7D)

* I see that the dependency updater reported a `TimeoutException` long before the pull request actor finished the coherency calculation for which updates need to be applied to the repo.

This query shows which subscriptions are affected by timeouts by the dependency updater:  [Go to Log Analytics and run query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA2WOTQrCQBSD957i0ZUi9AQiCFXowlX1ANOZ2A50fpj3ihY8vP1BKHQXQvIl%252BGhEscHz7vtukUAxhbqDKw21iimrBha4%252FGEdQi%252FXf5yUUIEIb%252BD18IxGCVK%252BcY6nRVR9zTrZuXrhwetzRv9B3bMEV4wDnqcj%252BS0kp0Rg7mBWDWh58lK2gyEJ1M9M4hV0wpGxLNZrGTMsyfpmv2GvO6U5%252FADZEmdO%252FwAAAA%253D%253D/timespan/P2D)​​​​​​​

As for next steps from an FR perspective:
* We should understand why some of the remaining actors ended up stuck after one timed out operation
* Verify whether the subscriptions that are seeing timeouts are all blocked, or if they are only seeing spurious timeouts

**Comment by MichaelSimons** [comment] 2023-02-14 16:21
Is there an update on when the dependency flows will be unblocked?

**Comment by ulisesh** [comment] 2023-02-15 23:23
@MichaelSimons we are tracking the fix for this issue in https://github.com/dotnet/arcade/issues/6782. We will discuss it in triage tomorrow and I'll share the plan once we have it

**Comment by ulisesh** [comment] 2023-02-17 19:35
I'm closing this as a dupe of #6782. The product construction team will take care of it

**Comment by riarenas** [comment] 2023-02-17 19:37
I disagree with this being a duplicate. Regardless of the CPD algorithm issues in the installer repository, we still have actors that are timing out and we should determine how to gracefully deal with that.

**Comment by tkapin** [comment] 2023-03-02 17:56
This problem was reported again today (on the FR channel as "darc not opening PRs? Part 2"). Based on the discussion, we need to remove the fallback to the legacy coherency algorithm (incl. the legacy coherency algorithm itself). This is tracked as #6782.

**Comment by dkurepa** [comment] 2023-04-03 10:28
A customer has reported another failing subscription:
https://github.com/dotnet/sdk (.NET 7.0.3xx SDK) ==> '[https://github.com/dotnet/installer'](https://github.com/dotnet/installer%27) ('release/7.0.3xx')
  - Id: 5f4141ca-7ec3-45bd-2cce-08daee6e84fe

**Comment by premun** [comment] 2023-04-14 12:05
Another problem [here](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1681470187187?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1681470187187&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1681470187187) with the subscription `c32383ee-d79c-4435-5b63-08d8d8feb47e`.

Also saw this for `23116d50-8f86-4127-4cdc-08d9fbbd4857`.

**Comment by tkapin** [comment] 2023-04-14 14:44
@Andrii, please look into this as part of the FR, including the #6782. Thanks!

**Comment by tkapin** [comment] 2023-04-17 09:29
Could you please also try to find how often this issue happened in the past from the exceptions in app insights? Thanks

**Comment by andriipatsula** [comment] 2023-04-19 14:50
> Could you please also try to find how often this issue happened in the past from the exceptions in app insights? Thanks

startofmonth | count | distinct subscription_id
-- | -- | --
2023-01-01 | 13 | 5
2023-02-01 | 125 | 10
2023-03-01 | 109| 11
2023-04-01 | 37 | 6

*`count` - number of records /2 with an `ActorConcurrencyLockTimeoutException` exception per month
*`distinct subscription_id` - number of unique subscription_id with an `ActorConcurrencyLockTimeoutException` exception per month 

[query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA12PPU%252FEMAyGd36F1eUSaI%252B2x3IDA0JssLEhdEoTl0bQ5HAc3Yf48bg98aGTPMSv7Tfvg3uLW%252FYxpIsv2A1ICJcwmATFneVI9zHYTITBHh6jfX%252F2I8bMDz9HBZjggEVNbMYtdMg7xADKGcZJVm3drqq6kdKwXMKZflM1a63lZ9wzitMYAw9wC%252BJGHPu5Vb%252F2%252FxZT7pIlP4fYeCcnMiBjWUnuz%252ByTnyYQe%252BBMATqT0IH9g4EPoYE%252BEpgJExbqpa7WlamOr1d6MRM5EFIwPSMVJTTl1CI9YUrmDacoKY%252BjIX9EMc6Blb5uy9Nz43xiHyTNWU4N3eEE%252BQ2AgkUKeAEAAA%253D%253D)

**Comment by ilyas1974** [comment] 2023-05-15 18:39
@andriipatsula, what are our next steps (if any) with this issue?

**Comment by andriipatsula** [comment] 2023-06-13 15:28
The PR that removes that legacy coherency algorithm is merged.

**Closed by andriipatsula** 2023-06-13 15:28 UTC
Labels: First Responder
