### ISSUE TITLE
arcade-services builds updating BAR with no triggered release

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2830] opened 2019-05-20 18:05 UTC
This might also apply to other repos., 

BAR builds 11898, 11891, 11848 and 11795 are in BAR but did not trigger a release, hence the packages were not published.

I was not able to find any logs related to failed releases and no issues were created since there was no associated release.

fyi: @JohnTortugo

**Comment by JohnTortugo** [comment] 2019-05-21 03:59
I investigated this a few hours ago:

- The problem is that a default channel mapping is missing (got removed) for the arcade-services repo in BAR/Maestro. We are investigating what happened here.
- I manually created a release for the latest arcade-services build.

**Comment by JohnTortugo** [comment] 2019-05-21 18:09
Actually the problem is that the INT release pipeline for arcade-services, which is the one that assign the build to a channel, is failing in CredScan: https://dnceng.visualstudio.com/internal/_release?definitionId=21&view=mine&_a=releases

@jcagme @mmitche @markwilkie - who usually looks on CredScan issues?

**Comment by markwilkie** [comment] 2019-05-21 18:16
Is it a false positive?

**Comment by alexperovich** [comment] 2019-05-21 18:16
Where are you seeing the CredScan failure? I just see a scenario test failure.

**Comment by JohnTortugo** [comment] 2019-05-21 18:20
@alexperovich yeah, I mean those test failures. I assumed those are the reason for the `Deploy Darc` stage not executing. I'll take a closer look to confirm.

**Comment by alexperovich** [comment] 2019-05-21 18:21
Yea, the Scenario Tests failed, so we didn't push the build into the release branch. This is correct behavior, we can't deploy a broken darc.

**Comment by JohnTortugo** [comment] 2019-05-21 18:23
That makes sense to me. What I wanted to point out in the original message is that this was the reason the builds weren't published.

Those don't look as flaky tests, all latest builds failed. Is that a known issue?

**Comment by riarenas** [comment] 2019-05-22 14:34
https://github.com/dotnet/arcade-services/pull/415 introduced a set of warnings when creating batched subscriptions and the tests were not updated to consider them.

I tried to fix this in https://github.com/dotnet/arcade-services/pull/423 but they are now failing with a different message.
I mostly understand the issue, filed https://github.com/dotnet/core-eng/issues/6419 and will try to get these unblocked asap.

This all looks by design to me.

Do you think it would make sense for the INT pipeline to deploy darc even if the tests fail? I really don't want to enable that for production, but for INT it might not be as bad?

**Comment by mmitche** [comment] 2019-05-22 14:43
> Do you think it would make sense for the INT pipeline to deploy darc even if the tests fail? I really don't want to enable that for production, but for INT it might not be as bad?

Yes, for sure.

**Comment by riarenas** [comment] 2019-05-22 14:46
The int pipeline has been updated to deploy Darc even if the tests fail. I also triggered all the "deploy darc" step for all releases that had failed, and this step will add the builds to the right channels.

**Comment by JohnTortugo** [comment] 2019-05-22 16:35
Thanks Ricardo

**Comment by JohnTortugo** [comment] 2019-05-22 21:20
Closing this as there is no action on publishing side and there is already an issue for tracking fix on arcade-services.

**Closed by JohnTortugo** 2019-05-22 21:20 UTC
