### ISSUE TITLE
Microsoft.NET.Test.SDK package is outdated

### ISSUE THREAD

**Issue by nohwnd** [dotnet/arcade#5604] opened 2020-06-03 14:06 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

This line uses 16.1.1 version of Test.SDK, which is an outdated version. This directly impacts how tests are executed because this package delivers the test host in which tests run. 

Could this be updated to at least 16.5.0 (which is the Test Platform version few lines below in that file), or better to 16.6.1?

Can we somehow keep this in sync automatically in the future? I see most other dependencies are either current or very recent. 

https://github.com/dotnet/arcade/blob/3c0eb1ae436f4a30fb3517196463190c3fa8b626/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L81-L86

**Comment by garath** [comment] 2020-06-18 23:16
Duplicate of dotnet/arcade#5291

We're looking at updating the default. Unfortunately this is one of the few things not managed by subscription. 

In case you're not aware, you are able to override these default versions in the repository's versions.props file.

**Comment by nohwnd** [comment] 2020-06-19 07:16
Thanks, I am aware, but not many projects override those, so it would be nice to have a more recent version pushed by arcade.

**Comment by garath** [comment] 2020-07-02 20:44
Closing as duplicate.

**Closed by garath** 2020-07-02 20:44 UTC
