### ISSUE TITLE
Darc `get-build` command duplicate output bug

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#12933] opened 2023-03-22 10:48 UTC
The darc `get-build` command has a bug when you run it with the `--repo` and `--commit` parameters:
The command will output the same build twice for some reason
This only happens when using these parameters, using the `--id` parameter works fine

### Release Note Description
Fix Darc `get-build` command duplicate output bug when using `--repo` and `--commit` parameters

**Comment by ali-turan7** [comment] 2023-04-14 14:40
this is the PR https://github.com/dotnet/arcade-services/pull/2256.

**Comment by ali-turan7** [comment] 2023-04-23 21:36
The issue is resolved by deduplicating the result list.

**Closed by ali-turan7** 2023-04-23 21:36 UTC
Labels: area-product-construction
