### ISSUE TITLE
HarvestPackage doesn't handle NuGetFallback folders

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#1687] opened 2019-01-03 23:18 UTC
From https://github.com/dotnet/arcade/pull/1684#pullrequestreview-189220106:

> [@joperezr] There is one more bug around harvesting which is that today we only look at the package folder for harvesting items, and we don't look into the NuGetFallback folders. If a specific package is already present on the fallback folder then it won't get restored to your package's cache so harvesting would fail. I believe that today in a clean machine, this would be the case. Anyways, that could get fixed in a different PR.

**Comment by joperezr** [comment] 2019-01-03 23:59
I already had this logged, so closing this as a dupe of #1351

**Closed by joperezr** 2019-01-03 23:59 UTC
