### ISSUE TITLE
Onboard arcade services to V3 publishing 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6945] opened 2021-02-11 03:32 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Onboard arcade services to V3 publishing

**Comment by riarenas** [comment] 2021-02-12 15:49
is this a duplicate of https://github.com/dotnet/arcade/issues/6932?

**Comment by mmitche** [comment] 2022-09-27 16:05
This has been complete.d

**Closed by mmitche** 2022-09-27 16:05 UTC
