### ISSUE TITLE
[BARViz] Trying to view a repo that has no builds in a specific channel results in an "Unable to Load Content" message after a long loading time

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2814] opened 2019-05-16 16:12 UTC
If I click on a repo that doesn't have a build in a channel, I get an infinite spinning circle. If I refresh, I end up seeing this:

![image](https://user-images.githubusercontent.com/23242101/57869366-bde3f880-77b9-11e9-9511-f51364b40d2f.png)

For instance: https://maestro-prod.westus2.cloudapp.azure.com/3/https:%2F%2Fgithub.com%2Fdotnet%2Farcade/latest/graph

Since there are no Arcade builds in channel 3, the Maestro API call returns a 404 by design.

We should guard better against this, either by not showing repos that don't have builds for the selected channel, or by improving the error message.

**Comment by riarenas** [comment] 2019-05-16 16:12
cc/ @mjanecke

**Comment by mjanecke** [comment] 2019-05-16 16:23
Duplicate of https://github.com/dotnet/core-eng/issues/5860

**Closed by mjanecke** 2019-05-16 16:23 UTC
