### ISSUE TITLE
Multiple unit test failures when running tests locally

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [dotnet/arcade#7092] opened 2021-03-11 09:37 UTC
```
[jw@cn06 arcade]$ ./test.sh
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.NuGetRepack.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.NuGetRepack.Tests.dll [netcoreapp3.1|x64]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.VersionTools.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.VersionTools.Tests.dll [netcoreapp3.1|x64]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.Helix.JobSender.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.Helix.JobSender.Tests.dll [netcoreapp3.1|x64]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.VersionTools.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.VersionTools/tests/Microsoft.DotNet.VersionTools.Tests.csproj]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.Arcade.Sdk.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.Arcade.Sdk.Tests.dll [netcoreapp3.1|x64]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.Helix.Sdk.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.Helix.Sdk.Tests.dll [netcoreapp3.1|x64]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.NuGetRepack.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.NuGetRepack/tests/Microsoft.DotNet.NuGetRepack.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Helix.JobSender.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Helix/JobSender.Tests/Microsoft.DotNet.Helix.JobSender.Tests.csproj]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.SourceBuild.Tasks.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.SourceBuild.Tasks.Tests.dll [netcoreapp3.1|x64]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.RemoteExecutor.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.RemoteExecutor.Tests.dll [netcoreapp3.1|x64]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Arcade.Sdk.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Arcade.Sdk.Tests/Microsoft.DotNet.Arcade.Sdk.Tests.csproj]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.PackageValidation.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.PackageValidation.Tests.dll [netcoreapp3.1|x64]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.VersionTools.Tasks.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.VersionTools.Tasks.Tests.dll [netcoreapp3.1|x64]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Helix.Sdk.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Helix/Sdk.Tests/Microsoft.DotNet.Helix.Sdk.Tests/Microsoft.DotNet.Helix.Sdk.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.RemoteExecutor.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.RemoteExecutor/tests/Microsoft.DotNet.RemoteExecutor.Tests.csproj]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.Build.Tasks.Feed.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.Build.Tasks.Feed.Tests.dll [netcoreapp3.1|x64]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.PackageValidation.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.PackageValidation.Tests/Microsoft.DotNet.PackageValidation.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.VersionTools.Tasks.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.VersionTools.Tasks.Tests/Microsoft.DotNet.VersionTools.Tasks.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Build.Tasks.Feed.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Build.Tasks.Feed.Tests/Microsoft.DotNet.Build.Tasks.Feed.Tests.csproj]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.ApiCompat.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.ApiCompat.Tests.dll [netcoreapp3.1|x64]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.ApiCompat.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.ApiCompat/tests/Microsoft.DotNet.ApiCompat.Tests.csproj]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.SignTool.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.SignTool.Tests.dll [netcoreapp3.1|x64]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.XUnitExtensions.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.XUnitExtensions.Tests.dll [netcoreapp3.1|x64]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.SignTool.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.SignTool.Tests/Microsoft.DotNet.SignTool.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.XUnitExtensions.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.XUnitExtensions/tests/Microsoft.DotNet.XUnitExtensions.Tests.csproj]
  Running tests: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.Build.Tasks.Packaging.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.Build.Tasks.Packaging.Tests.dll [netcoreapp3.1|x64]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Build.Tasks.Packaging.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Build.Tasks.Packaging/tests/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj]
  Tests succeeded: /home/jw/dotnet/arcade/artifacts/bin/Microsoft.DotNet.SourceBuild.Tasks.Tests/Debug/netcoreapp3.1/Microsoft.DotNet.SourceBuild.Tasks.Tests.dll [netcoreapp3.1|x64]

Build FAILED.

XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.VersionTools.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.VersionTools/tests/Microsoft.DotNet.VersionTools.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.NuGetRepack.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.NuGetRepack/tests/Microsoft.DotNet.NuGetRepack.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Helix.JobSender.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Helix/JobSender.Tests/Microsoft.DotNet.Helix.JobSender.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Arcade.Sdk.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Arcade.Sdk.Tests/Microsoft.DotNet.Arcade.Sdk.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Helix.Sdk.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Helix/Sdk.Tests/Microsoft.DotNet.Helix.Sdk.Tests/Microsoft.DotNet.Helix.Sdk.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.RemoteExecutor.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.RemoteExecutor/tests/Microsoft.DotNet.RemoteExecutor.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.PackageValidation.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.PackageValidation.Tests/Microsoft.DotNet.PackageValidation.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.VersionTools.Tasks.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.VersionTools.Tasks.Tests/Microsoft.DotNet.VersionTools.Tasks.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Build.Tasks.Feed.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Build.Tasks.Feed.Tests/Microsoft.DotNet.Build.Tasks.Feed.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.ApiCompat.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.ApiCompat/tests/Microsoft.DotNet.ApiCompat.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.SignTool.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.SignTool.Tests/Microsoft.DotNet.SignTool.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.XUnitExtensions.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.XUnitExtensions/tests/Microsoft.DotNet.XUnitExtensions.Tests.csproj]
XUnit : error : Tests failed: /home/jw/dotnet/arcade/artifacts/log/Debug/Microsoft.DotNet.Build.Tasks.Packaging.Tests_netcoreapp3.1_x64.log [netcoreapp3.1|x64] [/home/jw/dotnet/arcade/src/Microsoft.DotNet.Build.Tasks.Packaging/tests/Microsoft.DotNet.Build.Tasks.Packaging.Tests.csproj]
    0 Warning(s)
    13 Error(s)

Time Elapsed 00:00:14.62
Build failed with exit code 1. Check errors above.
[jw@cn06 arcade]$ 
```

**Comment by riarenas** [comment] 2021-03-18 18:20
I can reproduce this in ubuntu wsl by running `test.sh`, and on my windows box, simply doing a `./build.cmd -test` also results in multiple test failures. This makes me believe the tests are just broken when run locally.

Updated the title and moving to First Responders to take a look

**Comment by lpatalas** [comment] 2021-03-29 16:12
From what I see there are several groups of failed tests when run locally:
- [X] FindLatestDropTests - these fail on DateTime parsing when current culture is not set to US (already fixed on my branch)
- [ ] GenerateResxSourceTests - the generated output looks correct but is different than expected one. Maybe due to differences in compiler version? Needs further investigation
- [ ] MinimalRepoTests - build fails with `The local source 'C:\...\arcade\artifacts\packages\Debug\Shipping\' doesn't exist`.
- [ ] RepoWithConditionalProjectsToBuildTests - same as above
- [ ] RemoteExecutorTests - RemoteExecutor does not throw expected exception and exits with error code `-2147450749`

**Comment by riarenas** [comment] 2021-03-29 17:02
@lpatalas The only thing that pops up to me is the `The local source 'C:\...\arcade\artifacts\packages\Debug\Shipping\' doesn't exist`

if you run `build.cmd -pack -test` does this change at all? the `-pack` command should generate the artifacts folder.

**Comment by lpatalas** [comment] 2021-03-29 20:35
@riarenas Thanks, I tried it but it didn't change anything.

I found in the meantime that those failures are legit and the reason why they don't fail on CI is that we explicitly disabled `Microsoft.DotNet.Arcade.Sdk.Tests` project ([tests/UnitTests.proj#L46](https://github.com/dotnet/arcade/blob/76aa678a2cef0ef955f5907eb3da58f690755d05/tests/UnitTests.proj#L46)). I guess the next step for tomorrow is to try to enable it and see what are the problems with running it on CI.

**Comment by lpatalas** [comment] 2021-03-30 13:11
I have enabled Arcade.SDK.Tests on branch and run a build for that: https://dev.azure.com/dnceng/public/_build/results?buildId=1063262. The only additional error there is for `GenerateSourcePackageSourceLinkTargetsFile` task - it does not fail on local machine.

**Comment by lpatalas** [comment] 2021-04-01 10:52
`RemoteExecutorTests`  fail in Visual Studio because [this expression](https://github.com/dotnet/arcade/blob/3094b88d3bba32aca46b0bf16a84368d1cfb0c66/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs#L48) returns `C:\Proj\arcade\artifacts\bin\Microsoft.DotNet.RemoteExecutor.Tests\Debug\netcoreapp3.1\testhost.exe` inside Visual Studio but `C:\Proj\arcade\.dotnet\dotnet.exe` when run from console.

I'm not sure what is the correct solution here. I guess it's either a bug if `RemoteExecutor` is meant to support `testhost.exe` or we should just skip those tests inside Visual Studio if it's by design.

@ViktorHofer, I saw that you were working on this code in the past. Do you know by any chance what should be the correct behavior here?

**Comment by lpatalas** [comment] 2021-04-01 16:04
I'm off the FR next week so the next person would have to pick it up where I left. The remaining work is to fix the two last items in the above table.

**Comment by ChadNedzlek** [comment] 2021-04-12 21:13
It sounds like the only bits left are "RemoteExecutor"... But it's not really something we own.  Is FR a place where we clean up every test failure in code that people check into arcade? That's... a pretty intense burden, and not particularly sustainable (people check in broken code to arcade, and we have to deal with it)

I'd probably just slap "ignored" on all these tests as part of FR.

Triage, thoughts?

**Comment by jakubstilec** [comment] 2021-04-15 08:39
[Async Triage]: @markwilkie do we have an epic for Arcade code improvements?

**Comment by MattGal** [comment] 2021-04-15 16:49
[Async Triage] I favor closing this as fixed, with perhaps just the last step being adding a "skip if in VS" and perhaps some comments on these remote executor tests that it E_FAIL's when run from VS.  The tests work from the console, so arcade users _can_ run the tests locally before submitting PRs, and it's a special component for IPC and other cross process scenarios for the runtime team, not really shared infra for everyone (various things in Arcade are like this)

**Comment by riarenas** [comment] 2021-04-15 19:28
I agree with disabling the failing tests and closing. We can open an issue for the remaining tests. RemoteExecutor is not something we own, so a separate issue for dealing with those tests makes sense.

**Comment by jakubstilec** [comment] 2021-04-22 08:43
[Async Triage]: @MattGal can we disable falling tests as part of FR?

**Comment by jakubstilec** [comment] 2021-04-29 08:35
[Async Triage]: @MattGal @ilyas1974 can we disable falling tests as part of FR?

**Comment by ilyas1974** [comment] 2021-04-29 14:20
I have no problem taking this on in FR. 

We will do the following 
- Disable the RemoteExecutorTest for arcade is recommended above. 
- Create an issue for the team that owns the Remote Executor functionality to address the issue we are seeing.

**Closed** 2021-05-03 18:53 UTC
Labels: Detected By - Customer, First Responder
