### ISSUE TITLE
Add parallel Helix test jobs to the Helix SDK

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/arcade#1443] opened 2018-12-04 20:47 UTC
<S>There is no way to create multiple Helix test jobs that will be running **in parallel** directly from MSBuild.</s> There is no way to submit multiple Helix test jobs from MSBuild and wait on all of them to finish. The only way to do this is by using task batching (which is sequential).

It is possible to workaround this by running several instances of MSBuild - but this requires passing all the information needed to parametrize a Helix job via command line arguments.

/cc @chcosta @jonfortescue

**Comment by markwilkie** [comment] 2018-12-04 22:05
Could we understand better the scenario?  Usually the way to think about this is to let Helix itself do the parallelism...

**Comment by alexperovich** [comment] 2018-12-04 23:38
The issue here is in the MSBuild. When you have a project that sends to multiple queues it builds itself once per queue. Due to msbuild constraints it doesn't build itself in parallel (msbuild doesn't allow building the same project with different properties in parallel). We also don't upload work items in parallel.

This lack of parallelism causes slowness because the zipping and uploading of payloads isn't done in parallel.

**Comment by echesakovMSFT** [comment] 2018-12-05 01:10
Thanks @alexperovich for describing the issue.

The issue with MSBuild for submitting jobs to Helix. Right now it only allows creating multiple Helix work items and submitting them as a "job" to a Helix queue. What could be interested for coreclr to have is to submit multiple such jobs (each of them would correspond to a particular stress scenario) simultaneously and wait for all of them to complete.

**Comment by echesakovMSFT** [comment] 2018-12-05 01:36
@markwilkie I am trying to explain here where this can be used. Please let me know if the desciption below is unclear.

We have hundreds of test scenarios in coreclr based on the matrix of different parameters such as

Build OS: Windows_NT, Linux, OSX
Build Architecture: x64, x86, arm, arm64
Build Configuration: Checked, Release
Stress Mode: jitstress1, jitstress2, gcstress0xc, etc. (20-30 items)

Right now I am trying to split all of these scenarios into YAML defined jobs (each of them would be composed of 10-20 different test runs). For example, "Windows_NT x64 Checked Jit Stress Scenarios" **job** would start "Windows_NT x64 Checked JitStress1" "Windows_NT x64 Checked JitStress2" etc **test runs**. Each of the test runs would submit 10-100 of Helix work items (one for a given test assembly and for a Helix queue).

Ideally, we want to be able to submit all of these test runs simultaneously during one of the steps in a YAML defined job. As an example, you can see this *(partly working)* setup https://dnceng.visualstudio.com/public/_build/results?buildId=52390

**Comment by jonfortescue** [comment] 2018-12-05 01:38
Putting this in the "Helix functionality complete" epic for now; leaving it up to @markwilkie and co. to determine if this is something we will support.

**Comment by markwilkie** [comment] 2018-12-06 22:46
ASP needs this now too.  Upping priority.

**Comment by alexperovich** [comment] 2019-01-23 21:34
Dupe of #1642

**Closed by alexperovich** 2019-01-23 21:34 UTC
