### ISSUE TITLE
Improve commit msg

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#5453] opened 2020-05-11 20:15 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Improve commit message 

Actual issue - dotnet/arcade#3328

The commit message for the dependency update PRs are really long.  So in order to condense it, this is part one change for the issue which was initially created (#3328). Basically removing the redundancy in the commit message especially related to the from version and to version. 

The second part of the issue which deals with the : Dependency update is from the same repo and the builds differ then just get the latest build number and discard the older ones. ( Eg : dotnet/arcade-validation@e788b97) will be worked on as part of #3328 

```
Currently the commit message looks like this  :

Update dependencies from https://github.com/dotnet/aspnetcore-tooling build 20200507.9
Microsoft.AspNetCore.Mvc.Razor.Extensions: 5.0.0-preview.5.20257.7 -> 5.0.0-preview.5.20257.9
Microsoft.AspNetCore.Razor.Language: 5.0.0-preview.5.20257.7 -> 5.0.0-preview.5.20257.9
Microsoft.CodeAnalysis.Razor: 5.0.0-preview.5.20257.7 -> 5.0.0-preview.5.20257.9
Microsoft.NET.Sdk.Razor: 5.0.0-preview.5.20257.7 -> 5.0.0-preview.5.20257.9

After this change

Update dependencies from https://github.com/dotnet/aspnetcore-tooling build 20200507.9
Microsoft.AspNetCore.Mvc.Razor.Extensions , Microsoft.AspNetCore.Razor.Language , Microsoft.CodeAnalysis.Razor , Microsoft.NET.Sdk.Razor
From Version 5.0.0-preview.5.20257.7 -> To Version 5.0.0-preview.5.20257.9
```

**Comment by riarenas** [comment] 2020-05-11 20:19
@epananth This issue just looks like a duplicate of the other, and you're just mentioning what you did in a PR. I don't see a reason to create multiple issues for the same work. You can just keep the issue open while you have all the PRs necessary to fix it.

**Comment by riarenas** [comment] 2020-05-11 20:19
Also, which part of this is causing unreasonable pain?

**Comment by epananth** [comment] 2020-05-11 20:23
I wanted an issue related to the PR, cos I had seen earlier(especially during the release notes) I would put in a fix with no issue number. So I thought I will create an issue for this PR just keep track of it.

Also pain in the sense the commit message is really long.

**Comment by riarenas** [comment] 2020-05-11 20:30
If you want to use a separate issue that's fine, but it probably needs context / description of the actual issue you plan to fix than what is present here. I don't think it makes sense to create a PR, and then retroactively create an issue just to track the PR flow. 

The two checkboxes are there for us to be able to determine the priority of an issue. If you're going to mark either checkbox, it should include an explanation of what is being blocked, or what exactly is the unreasonable pain that the issue is causing on the users. 

Nowhere in this issue does it mention that the commit message is really long, and that we'll be condensing the versions. You are just adding the description of your current PR to the issue.

**Comment by epananth** [comment] 2020-05-11 20:36
Sure, I can add more context to this issue :)

**Closed** 2020-07-08 20:31 UTC
