### ISSUE TITLE
Enable parallel work item uploads to helix sdk

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#1483] opened 2018-12-06 22:56 UTC
The Helix SDK currently doesn't do work item payload uploads in parallel. Change this to be run in parallel to increase performance for large amounts of payloads.

**Comment by markwilkie** [comment] 2018-12-06 23:43
@Chrisboh - here's another item which may need to be done sooner than later for ASP.

**Comment by jonfortescue** [comment] 2019-02-08 02:32
Waiting on updates from ASP.NET before marking as closed.

**Comment by jonfortescue** [comment] 2019-02-18 21:18
@HaoK tested this change in https://github.com/aspnet/AspNetCore/pull/7373 and it seems to have worked. Closing.

**Comment by HaoK** [comment] 2019-02-18 21:30
No, we weren't able to upgrade to newest SDKs due to the helix errors (unable to find any jobs), I only tested the workaround for the warning

**Comment by HaoK** [comment] 2019-02-18 21:30
We are still using a really old sdk build

**Comment by jonfortescue** [comment] 2019-02-18 21:31
Oh, nvm then! Reopening.

**Comment by HaoK** [comment] 2019-02-18 21:37
I can open a new PR with just SDK version update

**Comment by jonfortescue** [comment] 2019-02-18 21:37
@HaoK I think that'd be great. Link me to it and I'll see if I can help sort out the update issues.

**Comment by HaoK** [comment] 2019-02-18 21:40
What's the best sdk version to try, we are still on 2.0.0-beta.19073.6

**Comment by jonfortescue** [comment] 2019-02-18 21:42
Probably 2.0.0-beta.19105.2 would be best.

**Comment by HaoK** [comment] 2019-02-18 21:44
Ok we can use https://github.com/aspnet/AspNetCore/pull/7692 for this

**Comment by HaoK** [comment] 2019-02-18 22:49
Yeah something changed that we need to react to in the sdk
```
D:\a\1\s\.nuget\packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19105.2\tools\Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(51,5): error : SendHelixJob given no WorkItems to send. [D:\a\1\s\eng\helix\helix.proj]
```

**Comment by jonfortescue** [comment] 2019-02-28 22:52
Confirmed that this is now working for ASP.NET. Closing.

**Closed by jonfortescue** 2019-02-28 22:52 UTC
