### ISSUE TITLE
TimelineRecords kusto table is missing dnceng-public records

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#10768] opened 2022-09-07 23:12 UTC
We don't have any rows from dnceng-public in TimelineRecords, whatever services adds the rows needs to monitor our new AzDo instance

**Comment by garath** [comment] 2022-09-07 23:14
FYI to avoid accidental double-work, @epananth was asking me about this the other day.

**Comment by riarenas** [comment] 2022-09-07 23:24
I think it's this? https://github.com/dotnet/arcade-services/blob/main/src/Telemetry/AzureDevOpsTimeline/.config/settings.json#L5-L8

**Comment by garath** [comment] 2022-09-07 23:27
More generally [this](https://github.com/dotnet/arcade-services/tree/main/src/Telemetry/AzureDevOpsTimeline) is the project. It will need to be taught how to look at more than one Organization.

**Comment by missymessa** [comment] 2022-09-07 23:28
@epananth and I talked about how we implemented the multi AzDO org support in Helix Services, because she said she needed to do the same in Arcade-Services. I'm assuming this work is related to that discussion.

**Comment by ulisesh** [comment] 2022-09-07 23:31
Good, thanks everyone!

cc @Chrisboh as some reports are missing data

**Comment by garath** [comment] 2022-09-07 23:31
I'm probably the last person to touch this code (having it get all timelines instead of just the latest). Let me know if I can help at all.

**Comment by ulisesh** [comment] 2022-09-07 23:32
I think this should be part of the epic in charge of moving to the new instance

**Comment by epananth** [comment] 2022-09-07 23:32
I was talking to @Chrisboh about this a few mins ago. We need to update this support both orgs, so that CI council dashboards work.

**Comment by epananth** [comment] 2022-09-07 23:33
Yes, I was tracking this as a part of dashboard work, but I can use this instead

**Comment by ulisesh** [comment] 2022-09-07 23:33
Feel free to take this issue to track the work or close it as a dupe if there is another one already 😄

**Comment by riarenas** [comment] 2022-09-08 18:12
As I think about this issue more, I'm starting to think this is the root cause for the Queue Insights alert as well: https://github.com/dotnet/arcade/issues/10710. 

@dkurepa can probably confirm it best, but if we're not ingesting builds from dnceng-public, the matrix of truth doesn't have information from those builds, and then queue insights won't record some of the needed entries for queue insights to work correctly.

**Comment by epananth** [comment] 2022-09-08 22:37
I have the code changes, I am currently testing it. Once that is successful I will have my PR for this

**Comment by epananth** [comment] 2022-09-08 22:49
@garath gave me some suggestions to test this, trying that now

**Comment by alexperovich** [comment] 2022-10-03 21:58
This is now fixed.

**Closed by alexperovich** 2022-10-03 21:58 UTC
