### ISSUE TITLE
Darc doesn't use command line PAT if darc authentication file exists

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#5463] opened 2020-05-12 22:15 UTC
Darc doesn't respect PATS passed in as parameters if there is a darc authentication file present on the machine. This causes a lot of chaos when running test cases locally, which may require PATs other than the ones set by the user (or if the user's are expired).

**Comment by riarenas** [comment] 2020-05-12 22:29
Closing as dupe of https://github.com/dotnet/arcade/issues/5454. I added your comment to that one.

**Closed by riarenas** 2020-05-12 22:29 UTC
