### ISSUE TITLE
Grafana dashboard import tool not working in local env

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#12370] opened 2023-01-31 13:22 UTC
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

### Problem / repro
Follow the docs on how to export JSON of a Grafana dashboard: https://github.com/dotnet/arcade-services/blob/8c1b8dc54327d354a31d265144835101137811f6/src/Monitoring/Sdk/README.md

Pick any dashboard and try to export its JSON. You will have to run a command like this eventually:
> dotnet build .\src\Monitoring.HelixService\Monitoring.HelixService.proj -t:ImportGrafana -p:GrafanaHost=https://dotnet-eng-grafana-staging.westus2.cloudapp.azure.com/ -p:ParametersFile=parameters.json -p:GrafanaAccessToken=GRAFANA_ADMIN_API_KEY -p:Environment=Staging -p:DashBoardId=buildAnalysis -v:normal

This will fail with:
> error MSB4062: The "MonitoringImport" task could not be loaded from the assembly C:\Users\mistucke\.nuget\packages\microsoft.dotnet.monitoring.sdk\1.1.0-beta.23074.2\Sdk\/../../../../artifacts/bin/Microsoft.DotNet.Monitoring.Sdk//net6.0/publish/Microsoft.DotNet.Monitoring.Sdk.dll. Could not load file or assembly 'C:\Users\mistucke\.nuget\artifacts\bin\Microsoft.DotNet.Monitoring.Sdk\net6.0\publish\Microsoft.DotNet.Monitoring.Sdk.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\mistucke\Projects\dotnet-helix-service\src\Monitoring.HelixService\Monitoring.HelixService.proj]

This does work in the pipeline though so it's about fixing it locally.

### Temporary workaround

You can change the path to the DLL by pointing the `MicrosoftDotNetMonitoringSdkTasksAssembly` property in `...\.nuget\packages\microsoft.dotnet.monitoring.sdk\1.1.0-beta.23074.2\sdk\Sdk.props` file and it will work. Point it to the DLL that is next to it:
```
.nuget\packages\microsoft.dotnet.monitoring.sdk\1.1.0-beta.23074.2\tools\net6.0\Microsoft.DotNet.Monitoring.Sdk.dll
```

That is also the probable fix for this issue.

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Grafana Import tool

**Comment by garath** [comment] 2023-01-31 23:19
Duplicate of dotnet/arcade#12375. It looks like fixing that issue will make local runs better. Or "better" at least.

**Closed by garath** 2023-01-31 23:19 UTC
Labels: FROps
