### ISSUE TITLE
GenFacades fails for methods which contain method local constants.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/arcade#1574] opened 2018-12-13 15:35 UTC
From https://github.com/dotnet/corefx/issues/29861, if you have a method with a method local constant you will currently get warnings such as (noting that we worked around these errors by making them normal constants in https://github.com/dotnet/corefx/pull/34057):
```
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600001F: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x06000020: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600003B: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600003C: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600003C: Invalid local constant signature: 'minAngle' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x06000059: Invalid local constant signature: 'EPSILON' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x06000072: Invalid local constant signature: 'FLT_EPSILON' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600008B: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
```

It looks like the error occurs when converting from Windows PDB to a Portable PDB due to invalid local constant signatures (NIL tokens) being generated.

**Comment by tannergooding** [comment] 2018-12-13 15:36
CC. @tmat, @weshaggard, @danmosemsft 

This is the new tracking bug for dotnet/corefx#29861 now that we have worked around the issue with https://github.com/dotnet/corefx/pull/34057

**Comment by tmat** [comment] 2018-12-14 22:40
I believe the root cause is in CCI emitting bad PDB.

https://github.com/dotnet/corefx/issues/29861#issuecomment-396102220

**Comment by ericstj** [comment] 2019-04-15 19:29
This is fixed by @Anipik's change to generate facade sources.  Given we want to move away from assembly rewiting I reccomend we "won't fix" this in the old GenFacades codebase.

**Closed by ericstj** 2019-04-15 19:29 UTC
