### ISSUE TITLE
Rerunning build from VSTS doesn't update the PR

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#1056] opened 2018-10-17 23:04 UTC
I noticed this when working on https://github.com/dotnet/arcade/pull/1030.

The PR build failed due to some infrastructure issue::
https://dnceng.visualstudio.com/public/_build/results?buildId=31854&view=logs

I chose to rebuild:
![image](https://user-images.githubusercontent.com/8918108/47121074-105e3600-d226-11e8-861a-7ec9db2f731a.png)

I noticed that while the rebuild was going on the PR badge didn't update to in-progress.
Once it completed the badge was updated.  Not sure if this is an issue with arcade or with DevOps, but wanted to file it.  /cc @chcosta @safern

**Comment by safern** [comment] 2018-10-17 23:13
Also, I would like to add that it is weird that you have to sign in in order to be able to rebuild the build when the build is under the public domain.

@chcosta is there any reason for that behavior? I would suspect for builds to know who kicked the new build?

**Comment by chcosta** [comment] 2018-10-17 23:16
I'm not sure I understand the scenario you're wanting. 

You want an "anonymous" build which knows who you are so that you can safely have a way to rebuild without authenticating?  I suspect that authenticating for rebuild is by design.

**Comment by chcosta** [comment] 2018-10-17 23:31
I'm not certain I can comment on features that don't yet exist.  Regarding build / rebuild, I think there's a strong desire to let authenticated users manage that operation.  

@vtbassmatt thoughts?

**Comment by vtbassmatt** [comment] 2018-10-18 15:03
Since someone can effectively trigger a build already (by pushing commits), we ought to support this using the comment syntax. Allowing anonymous users to push buttons in our UI is, for better or worse, out of scope right now. @DavidStaheli should also weigh in; he owns the "PR chat-ops" feature.

**Comment by markwilkie** [comment] 2018-10-24 16:36
@vtbassmatt - do you know David's GH handle?  (looks like the one above isn't resolving - at least for me)

**Comment by vtbassmatt** [comment] 2018-10-24 16:51
Hmm, resolves for me.
![image](https://user-images.githubusercontent.com/714283/47447429-7c432000-d78b-11e8-80ec-50bd01ab0bc1.png)

**Comment by markwilkie** [comment] 2018-10-29 16:38
@DavidStaheli - any insight?

**Comment by DavidStaheli** [comment] 2018-10-30 19:10
Hi @markwilkie .  We finished this feature several weeks ago, but it was hidden behind a feature flag pending additional testing.  We tested it last week and found a bug that we're working to fix.  @madhurig, can you please comment on how soon it will be fixed and potentially available to dotnet/arcade?

**Comment by markwilkie** [comment] 2018-10-30 20:15
Thanks @DavidStaheli - that's good news indeed.

**Comment by markwilkie** [comment] 2018-11-07 19:31
@madhurig and @DavidStaheli - Can you guys confirm this is already sorted?

cc/ @chcosta

**Comment by safern** [comment] 2018-11-13 00:40
It seems like this was fixed. Just worked in a PR of mine.

**Closed by safern** 2018-11-13 00:40 UTC
