### ISSUE TITLE
Try to split Maestro.Contracts so Darc doesn't need it

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade#9192] opened 2022-04-26 22:30 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Darc is trying to use some of the classes that are found in Maestro.Contracts, but Maestro.Contracts needs to be win7-x64 because of ServiceHost. Assuming Darc doesn't require ServiceHost, we should move everything in Maestro.Contracts out into a different project (existing or new, depending on what it is) so that darc can be any.

### Release Note Description
Split Maestro.Contracts so Darc doesn't need it

**Comment by dkurepa** [comment] 2022-12-22 16:02
I did some investigation on this topic:
Dark uses the following files/classes from the Maestro.Contracts project:
- MergePolicyConstants
- MergePolicyEvaluationResult
- MergePolicyEvaluationStatus

So naturally, we'd want to create a project MergePolicies and put these there.
However, we already have a Maestro.MergePolicies project that uses these classes. The problem is that it also uses some other classes (besides the ones listed above):
- IPullRequest
- DependencyUpdateSummary

Meaning that we'd also have to move these classes to avoid circular dependencies, and I don't think these classes belong in the MergePolicies project.

That leaves us with the option to create a new project, but I'm not sure what'd be a fitting name for it. Maybe it could just be named MergePolicyEvaluation

**Comment by dkurepa** [comment] 2022-12-22 16:45
I have created a PR for the new MergePolicyEvaluation project https://github.com/dotnet/arcade-services/pull/2161

**Comment by dkurepa** [comment] 2023-02-07 10:50
The pr has been merged. Darc should be useable on non win-x64 machines now

**Closed by dkurepa** 2023-02-07 10:50 UTC
