### ISSUE TITLE
Package signatures are not timestamped

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#2304] opened 2019-03-21 02:03 UTC
When restoring recently published packages from the windowsdesktop feed, I see the following error:

```
error NU3027: Package 'Microsoft.DotNet.Wpf.GitHub 4.8.0-preview4.19170.11' from source 'https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json': Th e signature should be timestamped to enable long-term signature validity after the certificate has expired.
```

Is there a potential problem with the related build-pool perhaps (`dotnet-internal-vs2019-preview`) ?

![image](https://user-images.githubusercontent.com/20246435/54729768-961e3e80-4b42-11e9-8df4-5297eb95c0b5.png)

/cc @jcagme @mmitche @JohnTortugo

**Comment by vatsan-madhavan** [comment] 2019-03-21 19:51
Can someone please take a look at this - this is blocking me and I'm not sure how to work around this in builds that consume packages built with these signatures. NoWarn=NU3027 works mostly, but eventually fails anyway during signing like it happened [in this build](https://dnceng.visualstudio.com/internal/_build/results?buildId=129934)

/cc @markwilkie

**Comment by mmitche** [comment] 2019-03-21 20:01
@tmat @JohnTortugo I'm not sure what to make of this.

**Comment by JohnTortugo** [comment] 2019-03-21 20:06
I'm also not quite sure if this is in the scope of SignTool; looks more like something about the certificate itself. Do you know anything about this @joeloff @RickKra ?

**Comment by tmat** [comment] 2019-03-21 20:07
@vatsan-madhavan What is the URL of the feed?

**Comment by tmat** [comment] 2019-03-21 20:08
Never mind, found it.

**Comment by vatsan-madhavan** [comment] 2019-03-21 20:11
https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json

**Comment by tmat** [comment] 2019-03-21 20:13
OT: Why is "GitHub" in the package name?

**Comment by vatsan-madhavan** [comment] 2019-03-21 20:19
> OT: Why is "GitHub" in the package name?

It's part of a prototype for a split build between a github repo and an internal repo. the transport package generated from the github repo has 'github' in the name.

**Comment by tmat** [comment] 2019-03-21 20:20
Where is the package build from? It doesn't have `repository` metadata :( It says ProjectUrl = https://github.com/dotnet/wpf but I can't find any projects in the repo that builds Microsoft.DotNet.Wpf.GitHub

**Comment by vatsan-madhavan** [comment] 2019-03-21 20:21
It builds form the _arcade_ branch

**Comment by tmat** [comment] 2019-03-21 21:25
@rrelyea Have you seen an issue like this?

**Comment by joeloff** [comment] 2019-03-21 21:58
Is this an internal test certificate perhaps? Otherwise, it's possible that PRSS has a misconfigured timestamp server, in which case you'll need to open an ICM ticket for them to investigate

**Comment by rrelyea** [comment] 2019-03-21 23:11
Talked with @dtivel -- he is not aware of a case like this happening. PRSS should be properly timestamping things.
(cc'ing @rido-min)

agree with @joeloff that you should have any problem like this investigated, if you had PRSS sign these packages.

**Comment by rido-min** [comment] 2019-03-21 23:32
The package [microsoft.dotnet.wpf.github.4.8.0-preview4.19170.11.nupkg](https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.dotnet.wpf.github/4.8.0-preview4.19170.11/microsoft.dotnet.wpf.github.4.8.0-preview4.19170.11.nupkg) has not been signed with the *oficial* Microsoft cert. I'm wondering if this was produced by PRSS.

```
Verifying Microsoft.DotNet.Wpf.GitHub.4.8.0-preview4.19170.11

Signature Hash Algorithm: SHA256
WARNING: NU3027: The signature should be timestamped to enable long-term signature validity after the certificate has expired.
Signature type: Author
Verifying the author primary signature with certificate:
  Subject Name: CN=VS Bld Lab Nuget Sign, OU=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA1 hash: 7AD3D7E3DB673953F589945259270FEA59434706
  SHA256 hash: 7143926839B3662D2394BBE656D374658DC1185CAA394FF6215088F644337994
  Issued by: CN=VS Bld Lab Nuget Sign Root, OU=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  Valid from: 11/6/2018 10:07:32 PM to 12/31/2039 3:59:59 PM

NU3018: The author primary signature found a chain building issue: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
WARNING: NU3018: The author primary signature found a chain building issue: The revocation function was unable to check revocation because the revocation server could not be reached. For more information, visit https://aka.ms/certificateRevocationMode.
WARNING: NU3018: The author primary signature found a chain building issue: The revocation function was unable to check revocation for the certificate.
Finished with 1 errors and 3 warnings.

Package signature validation failed.
```

**Comment by vatsan-madhavan** [comment] 2019-03-21 23:56
@rido-min, that's a great clue! 

I found a bug in my pipeline.yml and fixed it here: [70e72bf6](https://dnceng.visualstudio.com/internal/_git/6c03b454-12c7-4c55-add0-b4ac2ab19c36/commit/70e72bf61135df292780c9f76af929f85477245d/). 

I was real-signing everything, but for some inexplicable reason I had publishing set to test-signing. I just fixed this and now the package looks right! 

![image](https://user-images.githubusercontent.com/20246435/54792174-43a05900-4bfa-11e9-9a5e-23ef87c5db08.png)

**Comment by vatsan-madhavan** [comment] 2019-03-21 23:58
Thanks everyone for pitching in and helping - looks like my immediate problem is solved - and it turned out to be own error :/, though I don't think I'd been able to figure it out on my own. 

Now, shouldn't test-signed packages also have consistent time-stamping per Nuget guidelines? Should that be tracked in this issue or as a separate issue, or is that just by-design and not worth tracking at all?

**Comment by rido-min** [comment] 2019-03-22 00:01
I dont see any reason to do not include a timestamps in test-signed packages. But I don't know the details/owners of test-sign tasks.

**Comment by jcagme** [comment] 2019-03-22 00:12
@JohnTortugo @tmat thoughts on @vatsan-madhavan comment?

**Comment by JohnTortugo** [comment] 2019-03-22 00:17
I don't know the answer to that. I'll need to loop that through the Microbuild folks.

**Comment by tmat** [comment] 2019-03-22 00:17
Me neither.

**Comment by joeloff** [comment] 2019-03-22 04:03
Timestamping only helps to validate that a file was signed prior to the certificate's revocation time. Without a timestamp, the signature can only be trusted until the revocation time. After that, regardless of when the file was actually signed, you cannot trust the certificate/signature.

The problem is that the timestamp itself needs to be trusted - the time stamp usually have a counter signature and needs to come from a trusted timestamping service. I'd be surprised if PRSS sets those up for test certificates.

AFAIK, the test certificates are mostly there to speed up a build while still trying to go through the signing process, albeit "fake". If you're going to hit a real service for timestamping, you might as well just always do full signing.

**Comment by JohnTortugo** [comment] 2019-03-22 18:03
@vatsan-madhavan I'm closing the issue as resolved - feel free to reopen it in case you think it's not resolved. If you want ping me in private and I can share more info about how test sign is performed.

**Closed by JohnTortugo** 2019-03-22 18:03 UTC
