### ISSUE TITLE
[Maestro] Subscriptions should be manually triggerable

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1076] opened 2018-10-19 18:23 UTC
We need to be able to trigger a subscription manually. For instance, let's say I make a change in arcade which needs to be immediately pulled into a repo.  The repo already has a subscription, I just want to trigger it based on a new build.  Should:
- Trigger immediately or
- Trigger when next build is available?

**Comment by alexperovich** [comment] 2018-10-19 21:11
We can fairly easily make an api that triggers an "EveryDay" subscription when called. The "trigger when next build is available" bit is just an "EveryBuild" subscription.

**Comment by jcagme** [comment] 2018-11-19 18:21
https://github.com/dotnet/arcade/pull/1231 solves this. Assigning to @mmitche so the issue is closed when PR is merged

**Closed** 2019-01-09 15:43 UTC
