### ISSUE TITLE
Investigate why blazor-wasm inter-branch merges aren't working from 3.1

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4426] opened 2019-11-22 21:16 UTC
The inter-branch merges for blazor-wasm are working for some repos, like aspnetcore-tooling, but don't appear to be working for aspnetcore

https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json#L1280-L1297 should be saying that this should be happening, but is not.

https://github.com/aspnet/AspNetCore/commits/blazor-wasm
https://github.com/aspnet/AspNetCore/commits/release/3.1

PRs like https://github.com/aspnet/AspNetCore-Tooling/pull/1359 shows an example of what these should look like.

**Comment by riarenas** [comment] 2019-11-22 21:21
Would the double slashes have anything to do with it? 
https://github.com/dotnet/versions/blob/be4b1fde84990ed03a597642767c97aab0d028aa/Maestro/subscriptions.json#L1283

`https://github.com/aspnet/AspNetCore/blob/release/3.1//**/*"`

**Comment by riarenas** [comment] 2019-11-22 21:25
AspNetCore-Tooling has the same `//` so probably not the cause :(

**Comment by mmitche** [comment] 2019-11-22 21:35
No, that was intentional I think

**Comment by mmitche** [comment] 2019-11-22 22:00
@MattGal Setting to first responder

**Comment by riarenas** [comment] 2019-12-11 18:01
Grabbing this one.

**Comment by riarenas** [comment] 2019-12-12 16:53
I see that there's PRs for inter branch merges from release/3.1 to the blazor-wasm now, such as https://github.com/aspnet/AspNetCore/pull/17637

I'll close this as no repro, and if it starts happening again we'll have more data to look at logs and look at the pipeline that does the actual work.

**Closed by riarenas** 2019-12-12 16:53 UTC
Labels: First Responder
