### ISSUE TITLE
NotSupportedAssemblyGenerator does not work correctly with types without default contructor

### ISSUE THREAD

**Issue by marek-safar** [dotnet/arcade#7059] opened 2021-03-06 08:34 UTC
NotSupportedAssemblyGenerator does now work correctly with types without default constructor. This creates a bad user experience when they use such types either directly or indirectly.

It looks like the NotSupportedAssemblyGenerator cannot handle
	- static classes
	- classes with no explicit constructor

Here is an [sample](https://gist.github.com/marek-safar/d478d2dcf9dce7d807d40aca98d294d8) of generated code that has missing PNSE

This was found as part of https://github.com/dotnet/runtime/issues/49201 investigation.

@Anipik @ericstj

**Comment by jeffhandley** [comment] 2021-03-12 17:27
The challenge here is that the generated code ends up with `throw null` instead of throwing PNSE. This gives a very misleading exception/stack trace and the impression that this API should work on the targeted platform.

**Comment by ericstj** [comment] 2021-03-12 20:47
Oh, it's due to how PNSE's are now a transformation from reference source.  This is happening because System.Net.Quic is using hand-authored reference source that makes use of [expression bodies](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members) and the PNSE transformation misses them.

**Comment by safern** [comment] 2021-03-12 20:54
This seems like a dupe of: https://github.com/dotnet/arcade/issues/6509 ?

**Comment by ericstj** [comment] 2021-03-12 20:59
Indeed.  Closing

**Closed by ericstj** 2021-03-12 20:59 UTC

**Comment by safern** [comment] 2021-03-12 21:00
Seems like the fix might be trivial. Just clearing the expression body here: https://github.com/dotnet/arcade/blob/77daa47917f98e213e0412cbf36ff0ff50475691/src/Microsoft.DotNet.GenFacades/NotSupportedAssemblyGenerator.cs#L127 

Or we could always clear the method body and always return the method declaration syntax with an expression body instead:https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.methoddeclarationsyntax.withexpressionbody?view=roslyn-dotnet#Microsoft_CodeAnalysis_CSharp_Syntax_MethodDeclarationSyntax_WithExpressionBody_Microsoft_CodeAnalysis_CSharp_Syntax_ArrowExpressionClauseSyntax_

or just handle each case separately tehre.

**Comment by ericstj** [comment] 2021-03-12 21:04
Yeah, I think @Anipik suggested something similar.
