### ISSUE TITLE
AzDo Issue #2968

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#9965] opened 2022-07-12 21:35 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

[Azure Boards WorkItem](https://dev.azure.com/dnceng/internal/_workitems/edit/2968)

**Comment by adiaaida** [comment] 2022-07-12 21:35
(Created manually because the issue wasn't put in the correct area path on creation)

**Comment by ilyas1974** [comment] 2022-07-28 15:07
Duplicate of what is already in scope for the epic this issue refers to.

**Closed by ilyas1974** 2022-07-28 15:07 UTC
