### ISSUE TITLE
Move xharness testing to separate, triggerable job

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#13250] opened 2023-04-21 16:30 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The rate of xharness changes is pretty low, the time spent per PR is quite high, and available device resources are pretty low. We should move these out into a separate job that runs on commit and on-demand when a specific PR command is run. Alternatively, if we can identify specific paths that should run the xharness job, that would work too.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by premun** [comment] 2023-04-24 15:15
I think it should be easy to identify paths for which the build should queue

**Comment by premun** [comment] 2023-06-15 21:47
@missymessa yeah, this is a dupe of https://github.com/dotnet/arcade/issues/13044

The PR is here - https://github.com/dotnet/arcade/pull/13751

**Closed by premun** 2023-06-15 21:47 UTC
