### ISSUE TITLE
Microsoft.DotNet.Build.Tasks.Feed's "CheckIfBlobExistsAsync" was copy/pasted from build tools before retry logic was added

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#2057] opened 2019-02-20 00:47 UTC
This issue comes from @mikem8361 , this build failed: https://dev.azure.com/dnceng/internal/_build/results?buildId=99603&view=logs  

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeed.cs#L44

The cheapest fix is to port the changes made after this copy/paste operation that added retry:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/BlobFeed.cs#L45

The best fix is to use the Azure Storage Client Libraries which provide their own implementation of this.

**Comment by JohnTortugo** [comment] 2019-03-04 19:45
Looks related to this one: https://github.com/dotnet/arcade/issues/563

**Comment by chcosta** [comment] 2019-05-01 18:16
This looks like a duplicate of https://github.com/dotnet/arcade/issues/563 which is currently being worked on.

**Closed by chcosta** 2019-05-01 18:16 UTC
