### ISSUE TITLE
[darc/maestro++] [post-build improv] Update publishing / post-build documentation AND send notification to partners

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5306] opened 2020-04-20 19:06 UTC
Related to the plan discussed here: https://github.com/dotnet/arcade/issues/4283 

Lost of change are coming. We need to keep the docs update & notify partners of new/deprecated features.

**Comment by epananth** [comment] 2020-09-03 02:24
closing this as its a duplicate of -> https://github.com/dotnet/core-eng/issues/10629

**Closed by epananth** 2020-09-03 02:24 UTC
