### ISSUE TITLE
Remove dependency of Microsoft.DotNet.VersionTools

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#1985] opened 2019-02-05 22:56 UTC
https://github.com/dotnet/arcade/blob/e23b306673e647c087e629bbb2ef00ebb23938fb/src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj#L18

Microsoft.DotNet.VersionTools's source is in https://github.com/dotnet/buildtools/tree/master/src/Microsoft.DotNet.VersionTools
dotnet/buildtools it is not very well updated (still uses project.json). Arcade should not depend on such an old repo.

it should help issue https://github.com/dotnet/arcade/issues/1965 greatly.

**Comment by JohnTortugo** [comment] 2019-02-05 22:59
I think Tasks.Feed is the only thing that uses VersionTools right now. If so I think it would be good to make this issue part of the publishing redesign epic.

cc @mmitche @markwilkie

**Comment by wli3** [comment] 2019-02-20 22:22
ping. @mmitche @markwilkie I don't think this task should be in backlog. The new build framework should not have a dependency on an obsolete code base. I could not make contribution when I want/have to.

We workaround Arcade in nuget breaking change case eventually and made a product change instead. But that should not happen.

**Comment by markwilkie** [comment] 2019-02-20 22:53
cc/ @riarenas and @chcosta who's looking at this from another context as well.

Yes @wli3  - we should not be depending on buildtools.

**Comment by riarenas** [comment] 2019-02-20 22:59
I'll see how this is being used, and if it's straightforward to remove as part of the publishing redesign we're already doing. If it takes additional changes, I probably won't touch this until the first part of the publishing pipeline is deployed and in use.

@wli3 Backlog simply means "we're not actively working on this right this instant." The issue is being taken into consideration as part of the completion criteria for https://github.com/dotnet/arcade/issues/1179

**Comment by dagood** [comment] 2019-03-06 19:01
FYI there's a plan to move VersionTools to Arcade (https://github.com/dotnet/arcade/issues/1818#issuecomment-470204164). The Feed project could start depending on that instead of the version built by BuildTools, although continuing ahead with dependency removal might also be ok.

**Comment by dagood** [comment] 2019-03-15 21:20
VersionTools was added to Arcade by https://github.com/dotnet/arcade/pull/2213. You should be able to move to that now.

**Comment by jcagme** [comment] 2019-03-20 22:41
Fixed by https://github.com/dotnet/arcade/pull/2299

**Closed by jcagme** 2019-03-20 22:41 UTC
