### ISSUE TITLE
[darc/maestro++] Dependency updates will apply builds in the order they finish, even if an older build finishes last

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2349] opened 2019-03-26 23:07 UTC
This happened today:

[Build 1](https://dev.azure.com/dnceng/internal/_build/results?buildId=133984) started at 12:41:12 PM
[Build 2](https://dev.azure.com/dnceng/internal/_build/results?buildId=134057) started at 1:13:12 PM

Build 1 had a slow signing leg, and finished after Build 2.

Build 2 had already opened a PR to update Arcade-Validation https://github.com/dotnet/arcade-validation/pull/221 to update the Arcade SDK version to version 1.0.0-beta.19176.9

Once Build 1 finished, it updated the PR, and tried to change the version to  1.0.0-beta.19176.7

Since we depend on some asynchronous processes (Signing and Feed publishing), and we run multiple builds at once, we can't really depend on the order the builds finish to determine if we should apply a dependency update.

We should see if there's something that we can check to determine if a build is "newer" than another build that we're trying to update dependencies for.

Adding to the "Go Live" epic as this hasn't happened a lot. Will need to bump priority if we hit this more consistently.

**Comment by mmitche** [comment] 2019-08-21 21:50
Dupe of #2583, also closed

**Closed by mmitche** 2019-08-21 21:50 UTC
