### ISSUE TITLE
dotnet process gets oomkilled

### ISSUE THREAD

**Issue by Maoni0** [dotnet/arcade#13788] opened 2023-06-10 07:04 UTC
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=302240

### Build leg reported

System.Runtime.Numerics.Tests.WorkItemExecution

### Pull Request

https://github.com/dotnet/runtime/pull/87311

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-87311-merge-d9da7ca632f4437ebb/System.Runtime.Numerics.Tests/1/console.39bea065.log?helixlogtype=result

[ 3136.972541] [  26902]  1000 26902 68227995  1831884 15142912        0             0 dotnet
[ 3136.972542] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=ceecee32040832a59cb907e82ab25072933c1871f29778f9088e2d69b07a6358,mems_allowed=0,global_oom,task_memcg=/docker/ceecee32040832a59cb907e82ab25072933c1871f29778f9088e2d69b07a6358,task=dotnet,pid=26902,uid=1000
[ 3136.972597] Out of memory: Killed process 26902 (dotnet) total-vm:272911980kB, anon-rss:7309332kB, file-rss:4kB, shmem-rss:18200kB, UID:1000 pgtables:14788kB oom_score_adj:0

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by missymessa** [comment] 2023-07-27 17:49
@Maoni0 What error message do you want to use for this Known Issue to track down other errors like it?

**Comment by epananth** [comment] 2023-08-02 22:45
@Maoni0 pinging again :)

**Comment by AlitzelMendez** [comment] 2023-08-10 22:22
closing this issue as there is no known issue error message and is unclear if the issue is an infrastructure issue or a repository issue.
Please feel free to reopen this issue if you are still facing this problem.

**Closed by AlitzelMendez** 2023-08-10 22:22 UTC
Labels: First Responder, Detected By - Customer, Known Build Error
