### ISSUE TITLE
Roslyn is failing to publish

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4660] opened 2020-01-21 18:59 UTC
**-  Is this issue blocking: yes**
**-  Is this issue causing unreasonable pain: yes**

@tmat reported that official Roslyn builds are failing to publish with the following failure(s):

```
WARNING: The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20068.1\tools\SdkTasks\PublishArtifactsInManifest.proj(65,5): error : Failed to determine whether an existing package on the feed has the same content as 'd:\a\1\a/PackageArtifacts/Microsoft.CodeAnalysis.CSharp.CodeStyle.3.5.0-beta3-20071-01.nupkg': Response status code does not indicate success: 404 (Not Found).
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20068.1\tools\SdkTasks\PublishArtifactsInManifest.proj(65,5): error : Failed to determine whether an existing package on the feed has the same content as 'd:\a\1\a/PackageArtifacts/Microsoft.CodeAnalysis.CSharp.CodeStyle.3.5.0-beta3-20071-01.nupkg': Response status code does not indicate success: 404 (Not Found).
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20068.1\tools\SdkTasks\PublishArtifactsInManifest.proj(65,5): error : Failed to push 'Microsoft.CodeAnalysis.CSharp.CodeStyle@3.5.0-beta3-20071-01'. Result code '1'.

```

Sample build here: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3401388&view=logs&j=0b850c37-f3ae-5bb9-a9fb-4f1e0fce2747&t=50d41e72-ce5e-50a3-efc7-c28c030be91c&l=828

**Comment by JohnTortugo** [comment] 2020-01-21 19:00
Might be / Probably is related to this: https://github.com/dotnet/arcade/issues/3942

**Comment by MattGal** [comment] 2020-01-21 23:22
I understand this now and believe it is indeed caused by https://github.com/dotnet/arcade/pull/4272/ .  From analyzing the binlogs, when this happens it's because the variables (such as VSS_NUGET_URI_PREFIXES) are the values set by the credential provider, NOT the overridden one from the PS1.  

Thus the failure makes sense and explains why the msbuild from the same time succeeds: (it's on a super-old arcade version)

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3403415&view=logs&j=0b850c37-f3ae-5bb9-a9fb-4f1e0fce2747&t=50d41e72-ce5e-50a3-efc7-c28c030be91c

I'm trying to figure out the issue w/ the PS1 now; I'll also ask @jaredpar if I can spin a build with a "mattgal-roslyn" branch to prove this worked (set up to publish to general testing)

**Comment by MattGal** [comment] 2020-01-21 23:46
I believe https://github.com/dotnet/arcade/pull/4661 is the fix, but I'm going to experiment by making a roslyn branch now first.

**Comment by MattGal** [comment] 2020-01-22 01:38
Previous build attempt got hit by the signing outage, spinning again now.

**Comment by MattGal** [comment] 2020-01-22 17:28
Update: That didn't work, the variables were still set to the defaults from the cred provider.  I'm trying again using the previous version of the enable-cross-org-publishing logging commands as used in the msbuild publish jobs.

**Comment by MattGal** [comment] 2020-01-22 22:42
Issue understood and PR is merged.  I've also shown via a private branch how this solves the issue for roslyn.  I'll keep it in validate til it gets to their repo.

**Comment by MattGal** [comment] 2020-01-23 17:55
Just to be 100% sure before I close this, I've kicked off one more build with exactly the change I made to Arcade, to prove this will be unblocked when the Arcade bits flow to that branch:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3409925&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=20fcf628-b65c-5865-625a-1cef81cda63b

Once this completes successfully I will close the issue.

**Closed** 2020-01-23 18:51 UTC
Labels: First Responder
