### ISSUE TITLE
restore.sh fails on arm64 Macs

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/arcade#10423] opened 2022-08-12 22:57 UTC
1. Use macOS on an arm64 device.
2. Uninstall any system .NET SDKs.
3. Run `./restore.sh` from a clean Roslyn checkout.

Not sure whether this is a bug in Roslyn's build scripts, Arcade, or `dotnet-install`. It is trying to install the 3.1.0 runtime, which is fine, but it is trying to find an arm64 version, which has never existed (macOS arm64 support was added in .NET 5). This should be installing the x64 3.1.0 runtime instead.

```Attempting to install dotnet from public_location.
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.0/dotnet-runtime-3.1.0-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.0/dotnet-runtime-3.1.0-osx-arm64.tar.gz' is not available.
dotnet-install: Attempting to download using legacy link https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.0/dotnet-osx-arm64.3.1.0.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at legacy link 'https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.0/dotnet-osx-arm64.3.1.0.tar.gz' is not available.
dotnet-install: Attempting to download using primary link https://dotnetbuilds.azureedge.net/public/Runtime/3.1.0/dotnet-runtime-3.1.0-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://dotnetbuilds.azureedge.net/public/Runtime/3.1.0/dotnet-runtime-3.1.0-osx-arm64.tar.gz' is not available.
dotnet-install: Attempting to download using legacy link https://dotnetbuilds.azureedge.net/public/Runtime/3.1.0/dotnet-osx-arm64.3.1.0.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at legacy link 'https://dotnetbuilds.azureedge.net/public/Runtime/3.1.0/dotnet-osx-arm64.3.1.0.tar.gz' is not available.
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.0
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
Failed to install dotnet from public_location.
Attempting to install dotnet from dotnetbuilds.
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Attempting to download using primary link https://dotnetbuilds.azureedge.net/public/Runtime/3.1.0/dotnet-runtime-3.1.0-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://dotnetbuilds.azureedge.net/public/Runtime/3.1.0/dotnet-runtime-3.1.0-osx-arm64.tar.gz' is not available.
dotnet-install: Attempting to download using legacy link https://dotnetbuilds.azureedge.net/public/Runtime/3.1.0/dotnet-osx-arm64.3.1.0.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at legacy link 'https://dotnetbuilds.azureedge.net/public/Runtime/3.1.0/dotnet-osx-arm64.3.1.0.tar.gz' is not available.
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.0
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
Failed to install dotnet from dotnetbuilds.
Failed to install dotnet SDK from any of the specified locations.
/Users/sandy/.nuget/packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22411.2/tools/InstallDotNetCore.targets(15,5): error : dotnet-install failed [/Users/sandy/.nuget/packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22411.2/tools/Tools.proj]

Build FAILED.

/Users/sandy/.nuget/packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22411.2/tools/InstallDotNetCore.targets(15,5): error : dotnet-install failed [/Users/sandy/.nuget/packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22411.2/tools/Tools.proj]
    0 Warning(s)
    1 Error(s)
```

**Comment by adiaaida** [comment] 2022-08-30 17:46
I am looking into this. We can easily implement a workaround, however, I'm wondering why the official install script doesn't handle this case correctly (the one in eng/common is simply a wrapper that downloads and calls the official install script). @YuliiaKovalova is there any reason dotnet-install.sh doesn't recognize that on OSX arm64, any version that is pre-6.0 will need to install an x64 version?

Additionally, I am curious about this setup for roslyn altogether. Can you really have an x64 runtime with an arm64 sdk? That seems like it could be an issue. Why does roslyn rely on a 3.1.0 runtime?

**Comment by YuliiaKovalova** [comment] 2022-08-30 18:00
Hi @adiaaida,

This case hasn't been handled by install scripts. I suspect that nobody has known in our team about the corner case.
We use a common approach for recognizing OS architecture:
```
get_machine_architecture() {
    eval $invocation

    if command -v uname > /dev/null; then
        CPUName=$(uname -m)
        case $CPUName in
        armv*l)
            echo "arm"
            return 0
            ;;
        aarch64|arm64)
            echo "arm64"
            return 0
            ;;
        s390x)
            echo "s390x"
            return 0
            ;;
        esac
    fi

    # Always default to 'x64'
    echo "x64"
    return 0
}
```

**Comment by adiaaida** [comment] 2022-08-30 18:04
@YuliiaKovalova I will open an issue in install-scripts for this corner case.

**Comment by YuliiaKovalova** [comment] 2022-08-31 12:49
Hi @sandyarmstrong,

Do you have a pipeline or remote machine where I can test the fix?
Thank you!

**Comment by YuliiaKovalova** [comment] 2022-08-31 14:22
@sandyarmstrong,
yes, please https://raw.githubusercontent.com/dotnet/install-scripts/dev/ykovalova/fix_version_def_for_macos/src/dotnet-install.sh

**Comment by adiaaida** [comment] 2022-08-31 16:04
I also have an M1 so I will test it out for you

**Comment by adiaaida** [comment] 2022-08-31 16:41
Confirmed this works in a few different scenarios

**Comment by YuliiaKovalova** [comment] 2022-08-31 16:42
@adiaaida , thank you!!!

**Comment by adiaaida** [comment] 2022-09-01 14:46
Update: @YuliiaKovalova has checked in the change to install-scripts, and those should deploy next week. I am going to close this issue.

**Closed by adiaaida** 2022-09-01 14:46 UTC
Labels: First Responder, Area-Infrastructure

**Comment by davidwengier** [comment] 2022-10-27 10:01
@michellemcdaniel How does the `dotnet-install.sh` script deploy? Razor doesn't build on my M1, and it looks like the `dotnet-install.sh` that is linked above, which presumably fixes the issue, is not what is  in `eng/common/dotnet-install.sh` in this repo, and hence not in the Razor repo.

**Comment by michellemcdaniel** [comment] 2022-10-27 14:08
the dotnet-install.sh script in eng/common is just a wrapper for the one that comes out of install-scripts. It simply downloads the one published by install-scripts from the internet.
