### ISSUE TITLE
Randomly missing files in helix correlation payload

### ISSUE THREAD

**Issue by radical** [dotnet/arcade#9025] opened 2022-04-11 20:35 UTC
- [x] This issue is blocking 

This is currently blocking https://github.com/dotnet/runtime/pull/67771 .

Details:
- [WasmBuildTests](https://dev.azure.com/dnceng/public/_build/results?buildId=1711187&view=logs&j=6f051c1a-c3e7-5cde-411e-64125624a208&t=961bb5d4-39cc-55d0-23ed-82f28319785b) has some tests failing because they [can't find `emcc`](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67771-merge-78fc9cd3a30a419e98/EMSDK-.BuildPublishTests/1/console.1638be58.log?sv=2019-07-07&se=2022-05-01T18%3A23%3A29Z&sr=c&sp=rl&sig=cwVJr7WCm%2BzDnJWixw5TE2mJFfOOHaAdKuiMekQEi%2FM%3D).
  - `emcc` should be in a correlation payload copied to `build/emsdk`, in `build/emsdk/upstream/emscripten/emcc`.
     (from `SendToHelix.binlog`: `Adding Correlation Payload Directory '/__w/1/s/src/mono/wasm/emsdk/', destination 'build/emsdk' (TaskId:1662)`)
  - But checking the payload for the job, that file (among lot of others) seem to be missing.
  - We have seem this a few times - https://github.com/dotnet/runtime/issues/65956 . 
  - [This](https://github.com/radical/runtime/commit/1711d6dd9f03cea5ae385a72a1a124a608794b37) was a fix that I had tried earlier, but have been seeing the issue even after that.

- [x] This issue is causing unreasonable pain

cc @lewing @akoeplinger

**Comment by MattGal** [comment] 2022-04-12 01:17
I poked at these assertions, and I don't think this is random (though it absolutely might be a race), it's a problem constructing the payloads.   For instance, bullet 1, [the actual payload ](https://helixde8s23ayyeko0k025g8.blob.core.windows.net/helix-job-a3740489-34fc-4f79-86c8-deec5dd3634ad9931be166d44a6a6/46b881aa-07db-48f2-8107-172caf73baaa.zip?sv=2019-07-07&se=2022-05-01T18%3A21%3A43Z&sr=c&sp=rl&sig=dT%2F%2B46q14fXSiVkHeDaWRyYaYy2zlHEh8O3i5qfpbqs%3D) contains an "upstream" folder but no emscripten.  If you download the original payload that was uploaded and the file is missing, it's not random; the archive was made without the appropriate files.

Reading the doc https://github.com/dotnet/runtime/tree/main/src/mono/wasm , it sounds like this payload is fetched at build time and constructed in part of the build, is that correct?  If so it's likely the race condition you already tried to address may have come back.

@ilyas1974 FYI  for FR stuff and @jonfortescue FYI in case this relates to the init-native-tools stuff you tweaked (I think not?)

**Comment by radical** [comment] 2022-04-12 15:57
> it sounds like this payload is fetched at build time and constructed in part of the build, is that correct? 

We [copy emscripten](https://github.com/dotnet/runtime/blob/439a9fbecb80fa28fae684ebab9ddb1753f4a325/src/libraries/sendtohelix-wasm.targets#L226-L237) from `/usr/local/emscripten` to $repoRoot/src/mono/wasm/emsdk` in `StageEmSdkForHelix` target.

And then use [emsdk](https://github.com/dotnet/runtime/blob/439a9fbecb80fa28fae684ebab9ddb1753f4a325/src/libraries/sendtohelix-wasm.targets#L20) as a [correlation payload](https://github.com/dotnet/runtime/blob/main/src/libraries/sendtohelix-wasm.targets#L131). So, it shouldn't have the race, AFAICS. But maybe I missed something.

>  If you download the original payload that was uploaded and the file is missing, it's not random; the archive was made without the appropriate files.

By "random" I meant this is only happening on *some* builds, like https://github.com/dotnet/runtime/issues/65956 . Though with the https://github.com/dotnet/runtime/pull/67771 it seems to be getting hit consistently.

**Comment by jonfortescue** [comment] 2022-04-12 17:36
Very certain it's not related to the native tools changes as runtime doesn't seem to be using that functionality at all.

**Comment by MattGal** [comment] 2022-04-21 21:13
@radical in conversations with various folks, it seems clear that there's not a bug being implied here.  We construct tens of thousands of payloads per day with the same, simple code and payloads are not being randomly lost.

If you feel I am mistaken, feel free to boil down some kind of a repro with the traditional "Expected Behavior", "Actual Behavior", and "Repro steps" sections, store it somewhere I can get at, and I'll personally handle investigation of the issue.  Until then I am closing this issue.

**Closed by MattGal** 2022-04-21 21:13 UTC
