### ISSUE TITLE
Investigate odd coherency update

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7720] opened 2021-08-05 16:48 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In this PR, https://github.com/dotnet/installer/pull/11414 the system downgraded the roslyn build from 4.0.0-4.21404.8 to 4.0.0-4.21404.3. This is odd because strict coherency says that the version should have stayed at .8. A manual attempt to update based on coherency substitutes the right version.

**Comment by riarenas** [comment] 2021-08-05 20:38
I see three points where we updated this asset in that PR
```
8/4/2021, 6:43:13.753 PM | Attempting to disambiguate Microsoft.Net.Compilers.Toolset@4.0.0-4.21404.3 based on nuget.config at https://github.com/dotnet/sdk@0ae29000c547e8786f38346ebce0dbeba4c3b11c
8/4/2021, 6:43:13.753 PM Dependency Microsoft.DotNet.DarcLib.DependencyDetail will be updated to 4.0.0-4.21404.3 from https://github.com/dotnet/roslyn@ff69f82ec3ae9e05c305120da32668a05d207782
```
This corresponds to PR: https://github.com/dotnet/installer/pull/11412 which updated to sdk build 20210804.24

```
8/4/2021, 7:49:35.948 PM | Attempting to disambiguate Microsoft.Net.Compilers.Toolset@4.0.0-4.21404.8 based on nuget.config at https://github.com/dotnet/sdk@6e5a98699fc108e04d434cc39cb459189ebc2bdc
8/4/2021, 7:49:35.948 PM Dependency Microsoft.DotNet.DarcLib.DependencyDetail will be updated to 4.0.0-4.21404.8 from https://github.com/dotnet/roslyn@38582c4d3f32679e5cc29bf86c4bde012ed2baee
```
This corresponds to PR: https://github.com/dotnet/installer/pull/11413 which updated to sdk build **20210804.26**

```
8/4/2021, 8:32:20.031 PM Attempting to disambiguate Microsoft.Net.Compilers.Toolset@4.0.0-4.21404.3 based on nuget.config at https://github.com/dotnet/sdk@915b3ea3e528a813beaeaff962aa1237c80c07c8
8/4/2021, 8:32:20.030 PM | Dependency Microsoft.DotNet.DarcLib.DependencyDetail will be updated to 4.0.0-4.21404.3 from https://github.com/dotnet/roslyn@ff69f82ec3ae9e05c305120da32668a05d207782
```
This is the one that corresponds to commit https://github.com/dotnet/installer/pull/11414/commits/49b5ef8d2dee65ae4c95d25b950b66a321b68df7 in the affected PR, which updated (downgraded?) to build **20210804.25**

I haven't yet found a reason why we would process build 20210804.26 before 20210804.25, which is the source of the downgrade. 

These logs show that we have a logging bug "Microsoft.DotNet.DarcLib.DependencyDetail" for every coherency update, but I can't find any evidence that the legacy coherency mode ever went into effect for any of these. All the operation IDs for these logs only mention attempting to use the strict algorithm, with no logging of failures or fallback to legacy that I was able to find.

I think the two questions to answer are:

* Why did we process build 20210804.25 after we had already created and merged a dependency update PR for build 20210804.26?
* Why haven't we tried to bring the coherency back in line with the subsequent commits in the stuck PR? Are we only running the coherency updates during PR creation and not on each commit?

**Comment by MattGal** [comment] 2021-08-19 16:59
[Triage]: If this is a one-off, it may not be worth investigating until a similar issue crops up post-Ricardo's-extra-logging change

**Comment by riarenas** [comment] 2021-08-19 19:43
Yep, I think the root cause for this is clear, an older build was processed days after it had actually completed. IF we see this again, we can try to tweak when we determine a build should open a PR. I'm closing it for now. @mmitche feel free to reopen if you see again or if you think we should dig deeper on this now.

**Closed by riarenas** 2021-08-19 19:43 UTC
Labels: Needs Triage
