### ISSUE TITLE
We need to review all AzDO logging commands used for RO/RW-ness of variables

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#5085] opened 2020-03-17 19:47 UTC
- [ ] This issue is blocking : Not blocking but only because the feature flag was turned off
- [ ] This issue is causing unreasonable pain : Same as above, only not unreasonably painful because it's turned off.

As noted in [this build](https://dev.azure.com/dnceng/public/_build/results?buildId=562435&view=logs&jobId=fb000423-50a9-5897-1483-627612d50fb2&j=fb000423-50a9-5897-1483-627612d50fb2&t=0db499c2-6fe8-5392-f998-4ee23307441b), we've started to run afoul of this by-design security improvement change described [here](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md).

This was thankfully turned off quickly after it broke us, but _will definitely_ be turned on again.

What we need to do:
- Review everywhere Arcade functionality is writing output variables 
- Everywhere we are writing one, if there is any chance of it being written multiple times it needs to have `isReadonly=false` set.
- Output variables are as noted automatically read-only, if these are set multiple times they will likely need to be refactored in some way.

@ilyas1974  / @markwilkie  this isn't urgent but maybe a candidate for FR.  It's going to be non-trivial amounts of work and it's not urgent as we've gotten the flag turned off for now.

**Comment by MattGal** [comment] 2020-03-17 19:53
Just for historical detail, this rolled out today with the new AzDO Agent version which went live around 9:45 AM PST today (3/17/2020)

**Comment by vtbassmatt** [comment] 2020-05-01 20:00
The default for `##vso[task.setVariable]` is not to create readonly variables. You shouldn’t have to say “isReadonly=false”.

The things you’ll have to get updated are:
- You can’t overwrite a queue-time variable. Those are just always readonly now. This is a breaking change, but I decided it was worth it from a security standpoint.
- You can’t overwrite system variables anymore. It was always documented this way, but our enforcement was lax/non-existent.

Hopefully that’s a much smaller surface area.

**Comment by riarenas** [comment] 2020-05-06 15:55
Worth noting here that even once we make the changes in our repos, we need to sync up with partners and let them know with enough time for them to also do any work in their repos before the feature flag is turned on again.

**Comment by missymessa** [comment] 2020-05-06 16:03
Issues created for the following repos: 
- arcade
- dotnet-helix-services
- dotnet-helix-machines
- arcade-services
- arcade-validation (added to Validation epic backlog since it's stuff that I'm currently working on). 

Checked arcade-pool-provider and all the references to `task.setvariable` should be fixed by Arcade.

**Comment by missymessa** [comment] 2020-05-08 18:11
@vtbassmatt Is there a way we can turn this feature on for a build so we can get a repro? I want to make sure I'm not missing anything in Arcade (and our other repos) by only setting the output variables to readonly to test what the change would look like.

**Comment by vtbassmatt** [comment] 2020-05-08 19:28
@missymessa  unfortunately it's an org-wide flag

**Comment by vtbassmatt** [comment] 2020-05-08 19:29
But you'll get warnings with the flag off. That should help detect if you got everything.

**Comment by missymessa** [comment] 2020-05-08 19:31
> But you'll get warnings with the flag off. That should help detect if you got everything.

@vtbassmatt that's nice! Is there documentation as to what the warning message would look like?

**Comment by vtbassmatt** [comment] 2020-05-08 19:40
Don't think so, since it was intended as a temporary measure 😋 It's a normal build warning though.

**Comment by missymessa** [comment] 2020-05-08 20:24
@vtbassmatt I think I found a build with the warning: 
![image](https://user-images.githubusercontent.com/47990216/81446183-39f3f080-912f-11ea-9032-e9e999061774.png)

**Comment by missymessa** [comment] 2020-05-08 20:50
I dug through all the pipelines in dnceng/internal only saw the warning message in one pipeline (not one that .NET Eng Services owns), so I don't think we'll need to make any changes. However, we still need to issue a message to partners about the impending feature being switched on, and give guidance about how these variables will need to be addressed in the future. 

Only dnceng/internal job with the warnings: https://dnceng.visualstudio.com/internal/_build?definitionId=702&_a=summary

**Comment by missymessa** [comment] 2020-05-13 16:15
Communications have been sent out to Partners and the Perf team to refactor their variables that will be affected by this security feature. No changes required on our end. Going to close this issue.

**Closed by missymessa** 2020-05-13 16:15 UTC
Labels: First Responder

**Comment by riarenas** [comment] 2020-05-13 16:21
Should we keep this open until the feature is turned back on? Or have a separate issue to track that?
