### ISSUE TITLE
Root cause why maestro bot published a Arcade update that deleted a file that's still in use

### ISSUE THREAD

**Issue by pranavkm** [dotnet/arcade#4193] opened 2019-10-23 22:18 UTC
Sample PR: https://github.com/aspnet/AspNetCore-Tooling/pull/1257/files.

A recent Maestro update to a host of AspNetCore repos removed the `setup-maestro-vars.ps1` file. The file existed in the corresponding commit in `dotnet/arcade`: https://github.com/dotnet/arcade/blob/a42a124635ce1a218309ecb31ec59d559cacb886/eng/common/post-build/setup-maestro-vars.ps1. Deleting this file impacted the `_internal` build, so it took a fairly long time to identify this was incorrect.

It's not very clear why this happened, and we'd should understand this to avoid a recurrence.

**Comment by riarenas** [comment] 2019-10-23 22:42
This one is strange and interesting in that:

* The PR to arcade-validation for the same arcade SHA did not delete this file, but ALL of the PRs to the aspnet repos deleted the file.
* The PRs are not reflecting the state of the Arcade scripts at the commit SHA that the update is saying it brings in. Arcade commit a42a124635ce1a218309ecb31ec59d559cacb886 still has the file present.
* It doesn't repro with a manual `darc update-dependencies --channel ".NET 3 tools"

**Comment by riarenas** [comment] 2019-11-06 16:03
Looks like this is happening again:
Arcade-validation official build for release/3.x branch is broken:
https://dev.azure.com/dnceng/internal/_build/results?buildId=417080&view=results 

because https://github.com/dotnet/arcade-validation/pull/992 deleted the eng/common/setup-maestro-vars.ps1 script.

Same symptoms as before. It's not repro-able with the darc update-dependencies flow, and the file is still present in the Arcade branch.

I'll take a look at this now that we can't call it a one-off anymore.
(I wonder if it's somehow related to the GitHub outage yesterday)

**Comment by riarenas** [comment] 2019-11-06 16:10
Also looks like Arcade-validation is missing some files from Arcade's master branch that I just noticed by running a local `darc update-dependencies -c ".NET Tools - Validation"`

https://github.com/dotnet/arcade/blob/master/eng/common/SetupNugetSources.ps1
https://github.com/dotnet/arcade/blob/master/eng/common/SetupNugetSources.sh

which were deleted by https://github.com/dotnet/arcade-validation/pull/980

**Comment by riarenas** [comment] 2019-11-06 16:13
The setupNugetSources files are present in other repos I have manually spot-checked in the dotnet and aspnet orgs. So even though the Dependency update PR deleted them from arcade-validation, it didn't do it for the other repos. 😕

**Comment by riarenas** [comment] 2019-11-06 21:33
I tried to repro this in many different ways without any luck. I'm going to add some logging to the code path to see if I can make some more progress the next time it happens.

**Comment by riarenas** [comment] 2019-11-07 15:46
I added some additional logging to the dependency update codepath to find whenever we are attempting to delete a file from eng/common as part of an arcade update.

https://github.com/dotnet/arcade-validation/pull/998/files deleted the two files again before the deployment had finished, and then https://github.com/dotnet/arcade-validation/pull/999 brought them back and they haven't been deleted since.

We'll have some additional information next time this happens.

**Comment by riarenas** [comment] 2019-11-07 15:49
Sorry, off by one error on which PR did what.

* dotnet/arcade-validation#998 tried to delete the files. This was a documentation only change and I caught it and closed the Pull request without merging. We did not have logging by then.

* dotnet/arcade-validation#999 deleted the files before we had the deployment with additional logging.

* dotnet/arcade-validation#1000 brought the files back.

**Comment by riarenas** [comment] 2019-11-07 15:50
As of today, the logs show no PR deleted any files it shouldn't.

**Comment by riarenas** [comment] 2019-11-13 16:49
We haven't had any more unwanted deletions since adding the extra logging. My hunch is that this will come back at some point soon after we deploy Arcade-Services again. Will keep monitoring the logs in the morning until we get a hit.

**Comment by riarenas** [comment] 2019-11-18 16:02
We got a report that this happened again in https://github.com/dotnet/winforms/pull/2378/ over the weekend.

Curiously, I don't see any of the logs we introduced to diagnose this for that PR. I do see logs where we are deleting files in https://github.com/dotnet/source-build-reference-packages/pull/87/commits/0514baf675d38ac7f57230b7b55e8c7ab08ad927

and in https://github.com/dotnet/CliCommandLineParser/pull/174/commits/8d30fac4a7f17f7406fa889eb599c83bba8d4f14

But it's not deleting the same set of files that the winforms PR is.

**Comment by dougbu** [comment] 2019-11-18 18:03
See also https://dnceng.visualstudio.com/internal/_build/results?buildId=430781

**Comment by riarenas** [comment] 2019-11-18 18:03
Another instance in https://github.com/aspnet/Extensions/pull/2677. Same situation as winforms, no logs.

I wonder if some of the actors are somehow running old code?

**Comment by dougbu** [comment] 2019-11-18 18:04
Nice. that's the same issue @riarenas 

Should we manually revert part of aspnet/Extensions#2677 or wait for a fix (then trigger another dependency update)?

**Comment by riarenas** [comment] 2019-11-18 18:19
Since we've never seen this during local dependency updates, the workaround I recommend while we get to the root cause is:
	
* Downgrade the version of the microsoft.dotnet.arcade.sdk dependency in eng/version.details.xml
* Run darc update-dependencies --channel ".NET tools - latest

That will ensure you keep arcade up to date, and should bring back the files that the service deleted by mistake.

**Comment by riarenas** [comment] 2019-11-19 18:21
I was finally able to get a repro locally that I can debug through!!!

https://github.com/maestro-auth-test/maestro-test3/pull/484 is supposed to be bringing in https://github.com/dotnet/arcade/commit/62aff50bfb515b287487f41fccf4d83b8683a57b

but it's trying to delete two files that are present at that commit:

* https://github.com/dotnet/arcade/blob/62aff50bfb515b287487f41fccf4d83b8683a57b/eng/common/3.txt
* https://github.com/dotnet/arcade/blob/62aff50bfb515b287487f41fccf4d83b8683a57b/eng/common/test2

I believe I can make a lot more progress now that I can see what's going on under a debugger.

**Comment by riarenas** [comment] 2019-11-20 00:23
https://github.com/dotnet/arcade-services/pull/790

**Comment by RussKie** [comment] 2019-11-20 12:24
Looking forward to the fix

**Comment by riarenas** [comment] 2019-11-20 17:56
Root cause:

We keep an in-memory cache of the files that we will be serving repos during an update. We always inserted the files to the cache with an "add operation".

If at any point a file shouldn't have been part of an arcade update, we delete it from the repo's eng/common, and when doing so, we were modifying the entry in the cache to have its operation as a "delete" for the remainder of the file's existence in the cache. The problem went away as soon as the file was changed, a node was restarted, or the file was removed from the cache by exceeding the cache's size limit.

dotnet/arcade-services#790 makes it so we can't modify any of the files already in the cache, and instead we modify a copy. Once rolled out it should prevent this situation from happening anymore.

**Comment by RussKie** [comment] 2019-11-21 05:05
To confirm, will the fix restore the deleted files, or do we need to rollback the original bad change first?

**Comment by mmitche** [comment] 2019-11-21 14:33
I believe the fix should restore the deleted files.  That said, the fix will probably not be rolled out for a bit (need to get our deployment story in order again after some changes), so better to restore yourself for now (you can do update-dependencies and it will restore them locally).

**Comment by riarenas** [comment] 2020-01-10 14:58
This has been rolled out

**Closed by riarenas** 2020-01-10 14:58 UTC
