### ISSUE TITLE
Servicing exercise for .NET Core 3

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3868] opened 2019-09-05 20:10 UTC
In order to test the new publishing infrastructure that relies on stages, we're performing a servicing exercise to make sure that packages and blobs are published to the correct private feeds/storage, and there isn't a risk of publishing private bits to any of the public locations.

The process for this will be:

* Create internal/servicing-test branch on the repos that will be part of the exercise
* Update to the latest arcade version that enables publishing to private azure devops artifact feeds for internal builds
* Create subscriptions between the repos involved from the internal-servicing channel targetting the internal/servicing-test branch
* Run a build from the test branch and validate that no assets were published to any publicly accessible locations
* Check that Dependency update PRs get created based on the subscription structure
* Repeat on our way up the stack.

## Status for PAT-based exercise:

![flow-graph dot](https://user-images.githubusercontent.com/2249648/67797579-388a9280-fa3f-11e9-8ef3-61d112fb8218.png)

**Comment by riarenas** [comment] 2019-09-05 20:29
This is waiting for an Arcade SDK version that includes the changes from https://github.com/dotnet/arcade/pull/3792, which are currently blocked due official build breaks. I'll keep preparing the branches and subscriptions while the issues are resolved.

**Comment by JohnTortugo** [comment] 2019-09-05 20:42
Are these the repos (flow) that are going to participate in the exercise, right?

Arcade -> CoreFX -> Core-Setup -> Core-SDK

**Comment by riarenas** [comment] 2019-09-05 20:47
Is there a reason to include Arcade?

**Comment by JohnTortugo** [comment] 2019-09-05 20:59
If we trigger a subscription from Arcade to a new branch in CoreFX then the changes will be propagated automatically, right? We can start it on CoreFX too but we'll need to keep updating the branch in CoreFX anyway. Correct?

**Comment by riarenas** [comment] 2019-09-05 21:07
That would involve setting up a branch in Arcade that publishes to the servicing channel. For this first exercise I want to keep it contained to product repos.

**Comment by JohnTortugo** [comment] 2019-09-05 21:07
Talked offline. We don't have CI for the internal branches. We'll need to trigger the builds manually.. so starting from CoreFX may be easier.

**Comment by riarenas** [comment] 2019-09-05 21:29
Subscriptions and default channels targetting the internal servicing channel have been created for

* CoreFX
* Core-Setup
* Core-SDK

Will start running the builds as soon as the Arcade SDK with the necessary changes is available in the "tools - latest" channel.

**Comment by riarenas** [comment] 2019-09-05 22:04
To work around the arcade build break, I'm going to:

* Add the arcade-validation feed to the repos' NuGet.config
* Copy the state of the eng/common folder from arcade master
* Update the global.json to use the newest arcade SDK in the arcade-validation feed

**Comment by riarenas** [comment] 2019-09-06 14:21
Builds failed with:

`##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19455.13\tools\SdkTasks\PublishArtifactsInManifest.proj(65,5): error : Azure DevOps NuGetFeed was not in the expected format 'https://pkgs.dev.azure.com/(?<account>[a-zA-Z0-9]+)/(?<visibility>[a-zA-Z0-9-]+/)?_packaging/(?<feed>.+)/nuget/v3/index.json'`

We are attempting to use `https://dnceng.pkgs.visualstudio.com/_packaging/dotnet-core-internal/nuget/v3/index.json` as the feed URL.

`https://pkgs.dev.azure.com/dnceng/_packaging/dotnet-core-internal/nuget/v3/index.json` points to the same feed and matches the expected regex, so I'll build an Arcade SDK with the change,

**Comment by riarenas** [comment] 2019-09-06 16:24
successful Core-setup build: https://dev.azure.com/dnceng/internal/_build/results?buildId=341374&view=results

Triggered: https://dev.azure.com/dnceng/internal/_git/dotnet-core-sdk/pullrequest/2939?path=%2Feng%2FVersion.Details.xml&_a=overview

Going to see if any packages or blobs are outside the expected private locations, and will test if core-sdk is able to restore packages from the internal feed

**Comment by riarenas** [comment] 2019-09-06 19:47
Core-Setup does not use job.yml at all for their building, so the nugetAuthenticate task is not being ran, causing failures to restore from the internal azure devops feed.

**Comment by riarenas** [comment] 2019-09-06 21:02
Summary of latest attempts:

* CoreFX internal build published all their packages to the expected private locations 
* Core-Setup wasn't able to restore these packages, because they are missing the NugetAuthenticate task (Which we hoped repos would get for free by sticking it in Arcade templates, but the templates are not used in core-setup)
* Core-sdk tries to always download the installers from aspnetcore and core-setup from https://dotnetcli.azureedge.net/dotnet/ For internal builds, these installers should be downloaded from the dotnetclimsrc storage account instead. Investigating the best way to achieve this.

**Comment by riarenas** [comment] 2019-09-06 21:42
New build of core-setup with the NuGetAuthenticate task: https://dev.azure.com/dnceng/internal/_build/results?buildId=342082&view=results

All the Linux and OSX legs, and one windows leg (?) failed to restore some of the packages from the feed. Smells like an auth issue. Investigating.

**Comment by riarenas** [comment] 2019-09-09 20:34
Update:

* **Corefx**: https://dnceng.visualstudio.com/internal/_build/results?buildId=342183&view=results
  * Packages are being published to the correct locations. Haven't found issues.

* **Core-Setup**: https://dnceng.visualstudio.com/internal/_build/results?buildId=345789&view=results
  *  Failing to be able to authenticate against the azdo feed from within docker containers. I'm exploring passing the environment variables documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#how-does-this-task-work) to the container
  * Windows and OSX builds (and presumably Linux once the above is fixed) failing to restore the test asset projects:
[This uses its own restore sources](https://github.com/dotnet/core-setup/blob/master/src/test/Assets/TestProjects/Directory.Build.props#L4-L10
) instead of using the feeds from NuGet.config, and [also calls the msbuild restore task directly](https://github.com/dotnet/core-setup/blob/9a817feb375eb5e894398ad1d4665e585c066cfa/src/test/PrepareTestAssets/PrepareTestAssets.proj#L39-L48)  which is causing authentication issues against the feed.

* **Core-SDK**: 
  * Working on attempting to conditionally restore installers from dotnetclimsrc as a fallback from internal branches if the given installer is not available in the public dotnetcli container

**Comment by JohnTortugo** [comment] 2019-09-17 01:19
Update:

- I added a table to the issue description to keep track of which repos & subscriptions were tested.
- Got two problems in the test build for CoreFX: 1) Some 401 issues and 2) some NuGet timeouts. I'm still investigating what's going on here. [This is the build](https://dnceng.visualstudio.com/internal/_build/results?buildId=356915&view=logs).

**Comment by riarenas** [comment] 2019-09-17 14:53
Are we making sure to update arcade dependencies on these branches before running the builds? These all seem like flakiness and reliability bugs we fixed over the last week.

**Comment by riarenas** [comment] 2019-09-18 15:15
After an arcade update, the wpf-int build seems to be working well: https://dev.azure.com/dnceng/internal/_build/results?buildId=357911&view=results

CoreFX is still seeing issues during toolset restore. I'm examining if the workarounds we are using to make private feed restoring more sturdy are not being applied for this job (ie, it's not going through the Arcade codepath that sets the env variables and clears the cache)

**Comment by riarenas** [comment] 2019-09-18 22:07
Contacted Azure Artifacts team about the failures in CoreFX. I updated Arcade again because the branch was missing some changes, and we got a couple new failure modes when restoring.

**Comment by JohnTortugo** [comment] 2019-09-19 00:13
Update:

**AspNetCore:**

  - [TaskCanceled exception](https://dnceng.visualstudio.com/internal/_build/results?buildId=359438&view=logs&j=84e1ef63-b880-5b9e-d854-397c4b952259&t=fa5725a6-a173-58a1-b999-aaff2bc14461&l=51)
  - [Unauthorized messages ](https://dnceng.visualstudio.com/internal/_build/results?buildId=359438&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=39263dad-2be6-5f40-bde4-1bab0d7931b4&l=750)(aka 401)
  - [Problem starting the plugin ](https://dnceng.visualstudio.com/internal/_build/results?buildId=359438&view=logs&j=b72e85ab-3386-5aa9-6405-3837662d9688&t=f7506d25-98a6-55c7-2099-fa268bf83c45&l=52)'/home/vsts/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll'  -

**Comment by riarenas** [comment] 2019-09-19 14:19
AspNetCore branch doesn't have current arcade updates, so it's missing most of the workarounds. Will update the branch and kick off another build...

**Comment by riarenas** [comment] 2019-09-19 16:37
New build of aspnetCore still has issues, but they look more in line with what I expected could fail:
https://dev.azure.com/dnceng/internal/_build/results?buildId=360061

* Cannot authenticate against private feeds from docker. Will need the same treatment as the core-setup and core-sdk docker builds to install the credential provider.
* One of the jobs is not using the Arcade job template, so it needs to add the NuGetAuthenticate task.

**Comment by riarenas** [comment] 2019-09-19 22:52
Update:
* Provided a repro of the coreFX failures to the NuGet and Azure artifacts teams.
* Along with @JohnTortugo we were able to determine most of the fixes required for ASPNETCore

**Comment by JohnTortugo** [comment] 2019-09-20 01:02
There are two remaining issues for AspNetCore builds:

1 - There is a 401 error happening in a [leg that execute this file](https://dnceng.visualstudio.com/internal/_git/aspnet-AspNetCore?path=%2Fsrc%2FSiteExtensions%2Fbuild.cmd&version=GBinternal%2Fcesar-servicing-exercise). I think the problem might be that this script spawn subprocesses and said subprocesses don't have a copy of needed authentication env. variables.

2. Other issue is in the CodeCheck job. I pinged @dougbu about this and I'm waiting his response. /cc @JunTaoLuo in case he can also help.

**Comment by dougbu** [comment] 2019-09-20 16:03
### About AspNetCore
The base branch for 'internal/internal/cesar-servicing-exercise' appears to be 'release/3.1' but the last shared commit was pushed on the 12th. Likely missing a number of important fixes since then.

Suggest rebasing on latest. Then we can discuss the possible issues in the build.

FYI 'release/3.1' builds have been pretty solid recently.

**Comment by JohnTortugo** [comment] 2019-09-20 17:35
Thanks Doug. I'll try that.

Update:  Some build [legs in core-setup are failing to authenticate](https://dnceng.visualstudio.com/internal/_build/results?buildId=360978&view=results). Looks like Docker related stuff. @dagood

**Comment by dagood** [comment] 2019-09-20 17:39
I suspect an Arcade fix didn't go in the way I expected it to (note: that step uses `eng/common/msbuild.sh` which I recently learned is not a "standard" Arcade script). I'll take a look.

**Comment by dagood** [comment] 2019-09-20 18:17
Looks like the fixes in https://github.com/dotnet/arcade/pull/3928 aren't present in this branch, or in `release/3.1`, `release/3.0`, or `master`.

**Comment by dagood** [comment] 2019-09-20 19:56
The unknown missing piece was a `--ci` flag on the tool init step--the http cache wasn't being cleared, leading to the auth error upon the second time tool init runs. I added notes to my last comment.

Submitting the fix to Core-Setup branches. (The Arcade fix will still be missing, though.) Test build with fix: https://dev.azure.com/dnceng/internal/_build/results?buildId=361711

**Comment by dagood** [comment] 2019-09-20 21:20
The build I started (https://dev.azure.com/dnceng/internal/_build/results?buildId=361711) got past the build and failed on `Signing Validation` while trying to access the feed in `sdk-task.ps1`. I only applied the `sh` fixes from https://github.com/dotnet/arcade/pull/3928 to my branch, so I imagine this is due to missing the `ps1` fixes.

I kicked the upgrade PR https://github.com/dotnet/core-setup/pull/8272 along to get the Arcade fixes into Core-Setup `master.` However, I don't see a `release/3.1` Arcade => Core-Setup update PR. @JohnTortugo can you look at this?

(You might also want to port over the `ps1` changes manually to kick off your own build that gets to the very end, I'm not 100% sure what the goal of your branch is.)

**Comment by riarenas** [comment] 2019-09-20 21:23
> However, I don't see a release/3.1 Arcade => Core-Setup update PR. @JohnTortugo can you look at this?

We haven't finished setting up the subscriptions / publishing for arcade for the 3.x branches, and the builds in that channel don't have all the needed fixes yet.

**Comment by JohnTortugo** [comment] 2019-09-20 21:29
@dagood I already started my test build and it passed the point where it was failing before: https://dnceng.visualstudio.com/internal/_build/results?buildId=361843&view=results The error now seems to be the known private AzDO feeds issues.

Your build failed because of the errors fixed by these PRs, BTW: https://github.com/dotnet/arcade/pull/3962 https://github.com/dotnet/arcade/pull/3994

**Comment by JohnTortugo** [comment] 2019-09-24 20:06
My latest core-setup test build failed with a few of the known errors related to CredProvider + Nuget + AzDO feeds:

- [Timeout](https://dnceng.visualstudio.com/internal/_build/results?buildId=361843&view=logs&j=71ffe38c-ed83-5650-b269-3e2a870c2d94&t=8201b6b4-8e39-5696-de16-00bbfc516cee&l=39)s			
- [Task cancelled](https://dnceng.visualstudio.com/internal/_build/results?buildId=361843&view=logs&j=71ffe38c-ed83-5650-b269-3e2a870c2d94&t=8201b6b4-8e39-5696-de16-00bbfc516cee&l=111)
- [401 (Unauthorized)](https://dnceng.visualstudio.com/internal/_build/results?buildId=361843&view=logs&j=71ffe38c-ed83-5650-b269-3e2a870c2d94&t=8201b6b4-8e39-5696-de16-00bbfc516cee&l=192)
- [A plugin protocol exception occurred](https://dnceng.visualstudio.com/internal/_build/results?buildId=361843&view=logs&j=13abda86-2028-5de5-3254-ca63f887785e&t=b918dda1-f5a2-5e08-6356-4bea58297bb0&l=2862)

**Comment by JohnTortugo** [comment] 2019-09-25 08:22
I used a private branch from AspNetCore to try and create a minimal case for some of the failure scenarios that we are facing. I got a pretty small sample case for the `Timeout` and `Task Cancelled` errors.

- [This build (+SHA) always succeeds](https://dnceng.visualstudio.com/internal/_build/results?buildId=365403)
- [This build (+SHA) always fail](https://dnceng.visualstudio.com/internal/_build/results?buildId=365402)

Both builds tries to restore the same .csproj file. The only difference is that in one the csproj has a `PackageReference` which has a version attribute and in the other the `PackageReference` doesn't have the attribute. Although I don't think the problem is the missing version attribute I think this sample case should be helpful to nail down what's the root cause of the problem.

/cc @markwilkie @riarenas

**Comment by markwilkie** [comment] 2019-09-25 16:52
This this repro on a dev box @JohnTortugo ?

**Comment by JohnTortugo** [comment] 2019-09-25 17:13
It's a Dockerfile + Hosted agents. I can migrate it to one of our build pools.

**Comment by JohnTortugo** [comment] 2019-09-30 19:05
Moving this to Tracking until we get a fix/workaround for the NuGet/CredProvider issues or another plan to perform the exercise.

**Comment by JohnTortugo** [comment] 2019-10-08 23:15
Update: Starting new tests, now using the PAT approach.

**Comment by JohnTortugo** [comment] 2019-10-11 05:45
@mmitche @riarenas - what do you think of this failure in CLI: https://dev.azure.com/dnceng/internal/_build/results?buildId=384877&view=logs&j=2102e824-8139-5a77-22fe-fae16e86028f&t=a527eb89-acf0-510e-eaae-b4ed90b17127&l=56 Looks like the build tried to download the files from DotnetCLI and failed. I don't know if core-setup published the files to DotnetCLI MSRC but AFAIU that should be the right location for these blobs, given that this is an internal build. Right?

**Comment by JohnTortugo** [comment] 2019-10-15 20:44
Status update below. Legend

- Green nodes/edges have been tested and passed.
- Red nodes build failed. Only CLI right now, there is a fix in progress.
- White nodes/black edges where not tested yet.

![flow-graph-pat-exercise](https://user-images.githubusercontent.com/2249648/66868264-dd8e7100-ef51-11e9-8409-ddd29c2182a6.png)

**Comment by mmitche** [comment] 2019-10-15 20:45
Awesome!

**Comment by JohnTortugo** [comment] 2019-10-22 17:48
Status update, servicing builds using PAT:

![flow-graph dot](https://user-images.githubusercontent.com/2249648/67313368-b555c380-f4b7-11e9-9027-6de445cbc09b.png)

Failures reason and next steps:

- AspNetCore-Tooling 
  - **Reason:** [some unit tests failed.](https://dnceng.visualstudio.com/internal/_build/results?buildId=393523&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=1f132584-ab08-5fbf-e5d0-5685de454342) 
  - **Next step:** Talked with @dougbu yesterday, he thinks @wtgodbe might know what this is about.
- EntityFramework6 
  - **Reason:** [some unit tests failed. ](https://dnceng.visualstudio.com/internal/_build/results?buildId=393686&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589)
  - **Next step:** Same as _Tooling_;
- Extensions 
  - **Reason:** [conflict between package versions](https://dnceng.visualstudio.com/internal/_build/results?buildId=394070&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=ceff01a8-9014-5eca-5c15-e3c3bce62c6c). 
  - **Next step:** Talked with @mmitche; I'll update and rebuild involved repos. 

- CLI
  - **Reason:** [conflict between package versions. ](https://dev.azure.com/dnceng/internal/_build/results?buildId=395654&view=results)
  - **Next step:** Same as _Extensions_.

- Core-SDK: 
  - **Reason:** [looking for public Runtime blob file in a private location. ](https://dnceng.visualstudio.com/internal/_build/results?buildId=396378&view=results)
  - **Next step:** I'm working on it #4164

**Comment by JohnTortugo** [comment] 2019-10-22 18:14
I'm triggering a new build from AspNetCore-Tooling with the base branch `/internal/release/3.1` to see if the icon problem was solved there. [Here is the build.
](https://dnceng.visualstudio.com/internal/_build/results?buildId=397222&view=results)

I'm seeing some weirdness with subscription updates. For instance, templating builds aren't creating PRs in CLI. @riarenas is helping investigate that.

**Comment by JohnTortugo** [comment] 2019-10-23 17:38
Update:

![flow-graph dot](https://user-images.githubusercontent.com/2249648/67419090-e1894700-f580-11e9-8144-e1d5dcae2271.png)

- AspnetCore-Tooling:
  - Status: now is building fine. 
  - Note: It's a clean copy of source branch. i.e., the branch didn't receive update from _Extensions_ yet.

- Core-SDK:
  - **Status**: now is building fine and running with the improved DownloadFile task.
  - **Note**: it's a clean copy of source branch. i.e., the branch didn't receive update from any repo.

- EntityFramework6:
  - **Status**: same as before.
  - **Next step:** I'll try a clean copy of the source branch. Then wait to get a clean build from Core-Setup.

- Extensions:
  - **Status**: same as before.
  - **Next step:** waiting for a clean build from Core-Setup.

- CLI:
  - **Status**: same as before.
  - **Next step:** waiting for a clean build from Core-Setup.

**Note:** Yesterday afternoon I didn't succeed getting a green build from Core-FX because: 1) I started a clean branch and missed to include the PAT fix in one of the stages; 2) later in the afternoon builds were timing out and 3) the builds take hours to finish. After I get a green build from Core-FX I'll need to get one for Core-Setup.

**Comment by JohnTortugo** [comment] 2019-10-24 01:55
The grass is looking much greener now:

![flow-graph dot](https://user-images.githubusercontent.com/2249648/67446643-1bc90780-f5c6-11e9-99f9-7db042a032e0.png)

Notes:

- SDK
  - Status: Failing because the build-def lost permission to sign binaries. [Tracking issue here.](https://github.com/dotnet/core-eng/issues/8104)

- [Core-SDK](https://dnceng.visualstudio.com/internal/_build/results?buildId=399879&view=results), [Extensions](https://dnceng.visualstudio.com/internal/_build/results?buildId=399837&view=results) & [EF6](https://dnceng.visualstudio.com/internal/_build/results?buildId=399802&view=results) are still building. But are past the critical point.

- PRs were created in Core-SDK to [fix a bug](https://github.com/dotnet/core-sdk/pull/5309) and to [improve the DownloadFile task](https://github.com/dotnet/core-sdk/pull/5310).

**Comment by markwilkie** [comment] 2019-10-24 13:57
This is great news - thanks @JohnTortugo ! 

Who's on point for the mixed (public/private) feed work?

cc/ @mmitche

**Comment by markwilkie** [comment] 2019-10-24 17:55
Is the plan to make the "check public first, then private" generic so it just works for all repos?

**Comment by riarenas** [comment] 2019-10-24 18:00
Let me think about it a bit. 

The change we did in Arcade to do that for the runtime benefits everyone, but I believe the way that repos download random blobs is not standard. (Core-SDK uses their own `downloadFile` task.

Maybe we can provide a set of tasks in Arcade and make sure repos use those tasks instead of anything they were previously using. I don't know if I want to mix that with this issue though, and it might overlap with any future plans to use universal packages (if they are actually ever usable by us)

**Comment by JohnTortugo** [comment] 2019-10-29 18:31
I think we have concluded the exercise here, at least using PAT tokens:

- [PR in progress in Arcade](https://github.com/dotnet/arcade/pull/4081) to add scripts to add feed credentials on the fly. This is the workaround while we don't have stable restore from AzDO private feeds while authenticating with the Credential Provider.

- All repos shown in the graph (description of the issue) have been tested and are building fine.

- Issue found while downloading .NET Runtime from private location was found and [fixed in Arcade](https://github.com/dotnet/arcade/pull/4122).

- Issue found while downloading blobs from private locations was found in Core-SDK and the fix [is in PR now](https://github.com/dotnet/core-sdk/pull/5352). I'll move this issue to "In PR" until we get the Core-SDK PRs merged.

- NuGet team is still investigating flakiness while restoring from AzDO private feeds when authenticating using Credential Provider.

**Comment by JohnTortugo** [comment] 2019-10-30 23:48
Closing this as the open PRs have their related issues.

**Closed by JohnTortugo** 2019-10-30 23:48 UTC
