### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by lbussell** [dotnet/arcade#9555] opened 2022-06-02 22:37 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When submitting pull requests to arcade, it is difficult to determine who owns what parts of the repo and who to request for review. Adding a CODEOWNERS file would allow listing different owners for each directory/project. The result would be that the proper project owners are automatically requested for review when a pull request is made. It would also be easier for anyone making changes to arcade to find the right people to talk to about potential changes.

See the documentation for CODEOWNERS files: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners?algolia-query=code%20owners

**Comment by garath** [comment] 2022-09-01 20:07
This has come up in the past, but the problem is that Arcade is in a lot of ways owned by everyone who does any build/infra work in .NET. I think the best way to approach this is to flip the ask: if anyone does need an "owner" and finds one, open a PR with the CODEOWNERS.

**Comment by garath** [comment] 2022-09-01 20:12
I'm going to close this with the suggestion to create/add to a CODEOWNERS as needed, but feel free to reopen for more discussion if there is a strong need.

**Closed by garath** 2022-09-01 20:12 UTC
