### ISSUE TITLE
aka.ms latest link generation is broken in Maestro build promotion

### ISSUE THREAD

**Issue by jander-msft** [dotnet/arcade#6940] opened 2021-02-10 18:11 UTC
- [x] This issue is blocking
- [ ] This issue is causing unreasonable pain

The Maestro Build Promotion pipeline for the dotnet-diagnostics repo did not generate any aka.ms links correctly . While the files were published to their respective feeds, the aka.ms links all redirect to microsoft.com.

Here's the example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=986939&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

This blocks dotnet-diagnostics' ability to notify dotnet-docker of newer builds thus preventing the update of the nightly images.

**Comment by riarenas** [comment] 2021-02-10 19:29
@MattGal @adiaaida Could this be related to the work you've been doing with aka.ms links?

**Comment by adiaaida** [comment] 2021-02-10 19:42
Taking a look. This probably has something to do with some of my work.

**Comment by MattGal** [comment] 2021-02-10 20:56
Super weird.  Grabbing one from the build: https://aka.ms/dotnet//daily/diagnostics/monitor5.0/dotnet-monitor.nupkg.version , it points to https://dotnetcli.azureedge.net/dotnet/diagnostics/monitor5.0/dotnet-monitor.5.0.0-preview.4.21109.1.nupkg.version which is totally valid.

**Comment by MattGal** [comment] 2021-02-10 21:06
(seems to be the double-/s)

**Comment by jander-msft** [comment] 2021-02-10 22:07
> Super weird. Grabbing one from the build: https://aka.ms/dotnet//daily/diagnostics/monitor5.0/dotnet-monitor.nupkg.version , it points to https://dotnetcli.azureedge.net/dotnet/diagnostics/monitor5.0/dotnet-monitor.5.0.0-preview.4.21109.1.nupkg.version which is totally valid.

@MattGal, that link wasn't working earlier today but seems to be working now. However, other links from that build are still not working for me at this time:

- aka.ms/dotnet//daily/assets/manifests/dotnet-diagnostics/MergedManifest.xml
- aka.ms/dotnet//daily/diagnostics/bundledtools/diagnostic-tools-linux-arm.zip
- aka.ms/dotnet//daily/diagnostics/bundledtools/diagnostic-tools-linux-arm64.zip

etc.

**Comment by adiaaida** [comment] 2021-02-10 22:09
Matt manually created the link. We are currently testing a fix in arcade, which I cc'd you on. Should be in shortly, and then when we update our arcade dependencies (nothing you need to do on your part), you'll start getting the fix.

**Comment by adiaaida** [comment] 2021-02-10 22:27
@jander-msft have you guys always been using the aka.ms links, or is that new for you? We've been making a few changes in this area (and have a few more to make), so it's actually unclear if the double slash is actually the cause of the issue (but it is ugly, and I still want to fix that). Matt mentioned that he also made himself an owner of the link, which make it have a valid owner, which may be the reason that it's working now where the others are not. We're still looking into it.

**Comment by jander-msft** [comment] 2021-02-10 23:09
> @jander-msft have you guys always been using the aka.ms links, or is that new for you? We've been making a few changes in this area (and have a few more to make), so it's actually unclear if the double slash is actually the cause of the issue (but it is ugly, and I still want to fix that). Matt mentioned that he also made himself an owner of the link, which make it have a valid owner, which may be the reason that it's working now where the others are not. We're still looking into it.

We've been relying on the aka.ms link generation since about June 2020. We are using it to inform a dependency updating pipeline in the dotnet-docker repository of what the latest nightly build is. That repo is currently not using dependency flow and relies on aka.ms links for discovering the latest version of assets that the repo consumes.

**Comment by adiaaida** [comment] 2021-02-10 23:17
Ok. Thanks for the info. We are in the process of making several adjustments to the aka.ms links. Only two should affect you: 1) we will no longer be creating aka.ms links for MergedManifest.xml files; and 2) we are flattening the paths in the links. So instead of `aka.ms/dotnet/diagnostics/monitor5.0/dotnet-monitor.nupkg.version`, the file would be at `aka.ms/dotnet/dotnet-monitor.nupkg.version.` Let me know if we can assist you with managing how these changes will affect you.

**Comment by jander-msft** [comment] 2021-02-10 23:21
cc: @hoyosjs

**Comment by hoyosjs** [comment] 2021-02-10 23:25
@adiaaida That won't work very well for how we use the aka.ms links.

1. There's several concurrent servicing lines (5.0 is one, hence the monitor5.0 part of the link)
2. We have assets under the same name for different architectures.

Also, does the flattening not include the "build quality" portion of this?

**Comment by jander-msft** [comment] 2021-02-10 23:26
We intentionally put "monitor5.0" in the name of the asset in order to allow multiple versions of dotnet-monitor to have nightly builds so that we could, for example, declare the latest dotnet-monitor 5.0 and the latest dotnet-monitor 6.0 package independently. So the complete flattening of the links would break that ability.

However, theoretically, we could use the AKAMSChannelName to differentiate this so we end up having something like:
- aka.ms/dotnet/monitor50/daily/dotnet-monitor.nupkg.version
- aka.ms/dotnet/monitor60/daily/dotnet-monitor.nupkg.version

Is that an appropriate use of the channel information?

**Comment by adiaaida** [comment] 2021-02-10 23:31
We should definitely be using the AkaMsChannelName for this, but that would require you to publish to different channels for the different monitoring packages. Adding @epananth, who is most knowledgeable about the publishing code.

Build quality would be used, but I've set it up with my latest PR to only include it in channels that use AkaMsChannelName. That is related to the work to get the install scripts to be able to download builds of different qualities (daily, which come out of official builds, signed and validated that come out of Stage-DotNet, etc). Post-flattening, it will still be part of the short link. The flattening is only related to paths that are part of the file path that we are publishing.

**Comment by hoyosjs** [comment] 2021-02-10 23:35
That's a hard one, that's hardcoded in `PublishingConstants.cs` I believe. Matt had expressed no qualms if I added a channel constant for `dotnet-tools`, which is where we publish to, but that won't be helpful for this use case.

**Comment by adiaaida** [comment] 2021-02-10 23:37
Do you publish 6.0 and 5.0 tools out of the same branch? Or do they come out of different branches? If different branches, we can just create a new channel to publish to, like we do for other channels, and then we can use the ChannelName. Also adding @mmitche to the conversation, as this wasn't a scenario we had considered.

**Comment by jander-msft** [comment] 2021-02-10 23:38
> Do you publish 6.0 and 5.0 tools out of the same branch? Or do they come out of different branches? If different branches, we can just create a new channel to publish to, like we do for other channels, and then we can use the ChannelName. Also adding @mmitche to the conversation, as this wasn't a scenario we had considered.

It's hypothetical at this point, but I would anticipate that 5.0 and 6.0 would be built from different branches in the same repository.

**Comment by hoyosjs** [comment] 2021-02-10 23:40
Different channels is possible for different branches, but then that adds complexity to the side on arcade, and couples us quite a bit there. Is it not possible for us to keep using a full path to asset if explicitly specified?

**Comment by adiaaida** [comment] 2021-02-10 23:41
I may be able to work something out where certain channels don't flatten. That actually sounds like it would make sense.

**Comment by adiaaida** [comment] 2021-02-10 23:43
Do you guys need the MergedManifest.xml file to be accessible via aka.ms links? I can modify that too, if you do.

**Comment by hoyosjs** [comment] 2021-02-10 23:45
No, we don't particularly use it. We do use the manifest that darc returns on a gather-drop

**Comment by jander-msft** [comment] 2021-02-10 23:48
@adiaaida, for my understanding, what's the intended purpose of flattening the aka.ms links?

**Comment by adiaaida** [comment] 2021-02-10 23:53
It is part of this epic: https://github.com/dotnet/arcade/issues/5757. Basically, we want to simplify the knowledge that the install scripts need to have of the paths involved in a given dotnet drop, and the desire for the aka.ms links to be as minimal as possible. In general, we want our links to be of the format `aka.ms\dotnet\<channel>\<quality>\<product>-<sdk|runtime>-<OS>-<arch>.<ext>`. I'll ping you on teams with the doc.

**Closed** 2021-02-16 15:27 UTC
