### ISSUE TITLE
SDL Failures causing build breaks

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#4170] opened 2019-10-22 15:35 UTC
The `Run SDL Tool` job is failing across many build pipelines with the following error:

```
TSA Upload:
  TSA Onboard:
    Saving TsaCodebaseXml file: D:\a\1\.gdn\.r\tsa-onboard.xml
    Onboarding or updating TSA codebase: Arcade-Validation
    An exception occured while attempting to onboard or update a TSA codebase: Arcade-Validation
    TSA Response: {"Message":"TSA Error Code: 200 Error message: Invalid TFS Settings for Instance: [https://devdiv.visualstudio.com/] , Project [DevDiv] , Template [TFSDEVDIV]\r\n                                                  were passed to TSA: Encountered Exception [System.Exception: TSA was given an invalid Area Path: DevDiv\\NET\\NET Core \r\n   at TSA.Core.TFS.ThrowIfInvalid(Boolean validateBugTemplate)], Correlation ID: 79262e18-70e3-4b40-b9e9-99ac5e5aa0f3"}
    TSA web call returned a non-successful status code: PreconditionFailed
```

Some example builds:

Arcade: https://dev.azure.com/dnceng/internal/_build/results?buildId=396355&view=results
Arcade-validation: https://dev.azure.com/dnceng/internal/_build?definitionId=282&_a=summary
Arcade-Services: https://dev.azure.com/dnceng/internal/_build/results?buildId=396829&view=results
CoreFX: https://dev.azure.com/dnceng/internal/_build/results?buildId=396886&view=results

**Comment by riarenas** [comment] 2019-10-22 15:37
FYI @sunandabalu

**Comment by sunandabalu** [comment] 2019-10-22 20:59
All Arcade* master branches have updated AreaPath now. I have moved all SDL settings into a variable group, so moving forward any settings' change should not require a PR. 

I confirmed that WPF and CoreFx made this change as well in their respective repos.

**Comment by StephenBonikowsky** [comment] 2019-10-22 21:27
Please add WCF to follow-up with in the future as well please. Ran into the same thing today and found your change.

**Comment by riarenas** [comment] 2019-10-22 21:29
@StephenBonikowsky I'd say your best bet is to join the dncpartners alias if you're not on that DL yet.
We communicated about this break, and Sunanda linked her changes to the thread.

**Comment by StephenBonikowsky** [comment] 2019-10-22 21:31
Ok, will do.

**Comment by markwilkie** [comment] 2019-10-22 21:34
@StephenBonikowsky - folks in devdiv changed the area path for bugs under us....  This is was caused the breaks.

**Comment by StephenBonikowsky** [comment] 2019-10-22 21:42
Ah, thanks for the info.

**Comment by sunandabalu** [comment] 2019-10-22 22:17
I confirmed that Winforms made the change to their repo as well. @StephenBonikowsky has the change in PR for WCF. 

I have a PR out to merge the change to the release/3.x branch, waiting for Ask Mode approval.

**Comment by sunandabalu** [comment] 2019-10-22 23:00
PR to release/3.x branch of arcade merged. Closing this issue now.

**Comment by premun** [comment] 2019-10-24 13:09
@sunandabalu yesterday's arcade builds started failing on the same again:
https://dev.azure.com/dnceng/internal/_build/results?buildId=399720&view=results

I think we might need to have the configuration outside of code after all :)

**Comment by sunandabalu** [comment] 2019-10-24 16:00
> @sunandabalu yesterday's arcade builds started failing on the same again:
> https://dev.azure.com/dnceng/internal/_build/results?buildId=399720&view=results
> 
> I think it's good we have the SDL configuration outside of code now :)
> 
> I have checked https://devdiv.visualstudio.com/DevDiv and I don't see Area Path `DevDiv\NET Core` so that might be a problem?

I already moved it out of code, the values are populated from a variable group.

**Comment by sunandabalu** [comment] 2019-10-24 20:54
Looks like the AreaPaths have changed again, I have an ongoing thread with the DevDiv folks regarding this. Apparently the areapaths are changing for everyone and is on ongoing process for now. So there are 2 paths moving forwarded till this is sorted:
a)	Turn SDL off till the area paths are final
b)	Keep updating area path as and when it changes. 

This is what I heard from the DevDiv folks:
“The goal is to have a single source of truth for the areas of the product and who owns them. The tree is structured such that the DevDiv\<Area Level 2> maps to a single Engineering & PM owner. Ownership Hub is that source of truth and is used by various tools for routing bugs (compliance, feedback, Watson) and ShipReady for evaluating readiness. https://shipready.vsdata.io/vs/vs-16-general_topissuesforrelease/topIssuesForRelease/topissues?ti_rg=16.4&ti_ir=false&ti_imi=true&ti_eifm=false&ti_mustfix=true
”

**Comment by sunandabalu** [comment] 2019-10-24 20:54
I'm updating the value in the variable group, picking an area path from the link above.

**Comment by MattGal** [comment] 2019-10-25 17:39
THis seems resolved, closing

**Closed by MattGal** 2019-10-25 17:39 UTC
Labels: Critical, First Responder
