### ISSUE TITLE
Publishing should not be able to overwrite blobs

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6468] opened 2020-10-27 15:25 UTC
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Publishing should not overwrite blob artifacts (it can't overwrite packages today). But, simply changing to not overwrite is not good enough as it means that you can't rerun a failed publish. Instead, if there is a conflict, the existing blob's content should be compared to the new blob's content.

**Comment by mmitche** [comment] 2020-10-27 15:26
@epananth @riarenas 

The motivator here is that MergedManifests are getting uploaded to the stable locations for stable builds. This only affects post build signing right now, but it means that two subsequent stable builds of runtime will overwrite the same MergedManifest.xml

**Comment by MattGal** [comment] 2020-10-28 00:38
PUtting back to the backlog as I'll be working on other stuff.  Some notes:



HandlePackagePublishingAsync
Calls:
  - PublishPackagesToAzDoNugetFeedAsync
  Calls:
    - PushNugetPackageAsync (already has identical-ness-check)
  - PublishPackagesToAzureStorageNugetFeedAsync
  Calls:
    - BlobFeedAction.PushToFeedAsync, which ends up in 
             return await PushCommand.RunAsync(
                    settings,
                    lockedFileSystem,
                    packagesToPush,
                    force: options.AllowOverwrite,
                    skipExisting: !options.AllowOverwrite,
                    log: log);


HandleBlobPublishingAsync
Calls:
  - PublishBlobsToAzDoNugetFeedAsync
    Calls:
    - PushNugetPackageAsync (already has identical-ness-check)
  - PublishBlobsToAzureStorageNugetFeedAsync
  Calls:
    - UploadAssetAsync (already uses IsFileIdenticalToBlobAsync)

**So I think this work entails:** 
- Teach BlobFeedAction.PushToFeedAsync to check for dupes (deeply entangled in Sleet junk)

**Comment by mmitche** [comment] 2020-10-28 14:09
I think when the flat container push is specified, then it doesn't use sleet.
If it does, you could also replace the flat container pushes with azure storage APIs

**Comment by MattGal** [comment] 2020-10-28 18:25
> I think when the flat container push is specified, then it doesn't use sleet.
> If it does, you could also replace the flat container pushes with azure storage APIs

That's the UploadAssetAsync case (which already has identical-ness checks).  I'm fairly sure that the only place that this codepath lacks "identical thing already there" checks is the one path where it actually calls into Sleet directly.

**Comment by mmitche** [comment] 2020-10-28 18:27
I don't think we need the support in sleet. We don't push to blob feeds any longer.

**Comment by mmitche** [comment] 2020-10-28 18:34
In fact, what you might do is:
- Verifying in PublishingConstants.cs that there are no sleet feeds (v3 publishing)
- Verify in v2 publishing (post-build.yml) there is no sleet publishing.

If the first two are true, remove sleet from arcade master and then backport that change to 5.0

**Comment by epananth** [comment] 2021-01-09 03:21
When blob is being uploaded 
The following checks occur : 

1) Checks if the blob already exists in the Azure storage, if it does then compares the bits. If the blob to be uploaded and the existing blob have different contents then it will error out saying it already exists with different contents. So it failed to upload to Azure Storage. 
2) If the contents are same - then it will log that it already exists so skipping upload for the specific blob
3) It does not exists so it uploads. 

Is this correct assumption? This way the blob will not get overwritten if we retry and we can preserve the contents. 

cc: @mmitche

**Comment by epananth** [comment] 2021-01-11 22:00
got my questions answered offline. Spoke to Matt and he confirmed the code looks good as is. We already have AllowOverwrite to false, so the blobs are never overwritten. Closing this one.

**Closed by epananth** 2021-01-11 22:00 UTC
