### ISSUE TITLE
Publishing should use bulk asset add location API

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5400] opened 2020-05-04 14:25 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The publishing code should use the bulk add API to reduce calls.

**Comment by JohnTortugo** [comment] 2020-05-04 15:57
Dupe of https://github.com/dotnet/arcade/issues/5323

I'll work on the linked issue this week.

**Closed by JohnTortugo** 2020-05-04 15:57 UTC
