### ISSUE TITLE
Microsoft.DotNet.Arcade.Sdk.dll does not have a proper strong name

### ISSUE THREAD

**Issue by sharwell** [dotnet/arcade#5326] opened 2020-04-22 14:03 UTC
Arcade builds are failing to create a unique assembly name for the build tasks for each commit made to this repository. This leads to build errors when trying to build more than one arcade project on the same machine:

> C:\dev\roslyn\eng\targets\Imports.targets(132,5): error MSB4062: The "Microsoft.DotNet.Arcade.Sdk.CompareVersions" task could not be loaded from the assembly C:\Users\sam\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20215.5\tools\net472\Microsoft.DotNet.Arcade.Sdk.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\dev\roslyn\src\Compilers\Test\Utilities\CSharp\Microsoft.CodeAnalysis.CSharp.Test.Utilities.csproj]

Steps to reproduce:

1. Build dotnet/roslyn-analyzers
2. Build dotnet/roslyn

Expected behavior:

Both projects build

Actual behavior:

The first project builds successfully. The second project fails because it uses the wrong strong name and tries to run the same arcade bits from the first build.

**Comment by markwilkie** [comment] 2020-04-22 14:34
cc/ @alexperovich @tmat

**Comment by alexperovich** [comment] 2020-04-22 20:25
Is this caused by a shared msbuild node? Nothing in the project or build suggest that we turned off strong naming. Unless the recent work to turn off signing for assemblies that aren't "shipping" packages caused this.

**Comment by tmat** [comment] 2020-04-22 20:45
I think we just need to set `AutoGenerateAssemblyVersion` to true for this project, or rather any project that produces msbuild task. As our doc suggests :)
https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md#recommended-settings

**Comment by alexperovich** [comment] 2020-04-22 20:50
That makes sense. We can just shove that property into here https://github.com/dotnet/arcade/blob/master/eng/BuildTask.targets.

**Comment by alexperovich** [comment] 2020-04-22 20:53
https://github.com/dotnet/arcade/pull/5330

**Comment by JohnTortugo** [comment] 2020-05-01 17:25
@alexperovich - can we close this now?

**Comment by alexperovich** [comment] 2020-05-01 19:52
Yes

**Closed by alexperovich** 2020-05-01 19:52 UTC
