### ISSUE TITLE
Arcade guidelines for producing SourceLink information

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3782] opened 2019-08-27 18:02 UTC
We should create some documentation about how repos should approach the creation of SourceLink infos.

/cc @markwilkie

**Comment by markwilkie** [comment] 2020-03-26 15:39
I bet @tmat knows where there are sourcelink docs.

**Comment by garath** [comment] 2020-06-11 20:39
@tmat ping

**Comment by markwilkie** [comment] 2020-07-16 14:28
Closing this as the issue is not getting any traction, which probably has to do w/ the fact that we do have some docs already.  @tmat, if you'd like to add to it, please reopen.

**Closed** 2020-07-16 20:05 UTC
