### ISSUE TITLE
cibuild.sh sometimes swallows MSBuild failure

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2942] opened 2019-06-04 16:40 UTC
Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=204767&_a=summary

![image](https://user-images.githubusercontent.com/2696087/58897159-87a8e300-86ac-11e9-9073-971cec7d4c0a.png)

This build step looks like this:
```yaml
      - script: eng/common/cibuild.sh
          --configuration $(_BuildConfig)
          --prepareMachine
          -p:BuildNodeJS=true
          $(_OfficialBuildArgs)
        displayName: Build
```

cc @mmitche

**Comment by natemcmaster** [comment] 2019-06-04 18:12
So, I added some console logging to [this code](https://github.com/dotnet/arcade/blob/b6107674719638ea0794f01bd32e3069de6388eb/eng/common/tools.sh#L377-L382) figure out if this is a script problem or not. It looks like our script is doing the right thing, so maybe MSBuild itself is returning exit code 0?

![image](https://user-images.githubusercontent.com/2696087/58903136-7fa37000-86b9-11e9-9c00-06443e31ed4c.png)

/cc @rainersigwald

**Comment by rainersigwald** [comment] 2019-06-04 18:28
It is possible for MSBuild to return 0 despite build errors for a few (mostly bad) reasons.

Unfortunately, it looks like your run-tests phase overwrites `Build.binlog`. Any chance you have a binlog of the errors handy?

**Comment by natemcmaster** [comment] 2019-06-04 19:31
I'll adjust our build and try to gather a repro....the failure isn't consistent, so it might take a few runs. I'll post a link to a binlog once I have one.

**Comment by natemcmaster** [comment] 2019-06-04 20:15
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=211815
Log: https://dev.azure.com/dnceng/_apis/resources/Containers/1685374?itemPath=Linux_Ubuntu%2016.04%20Release%2FBuild.binlog

**Comment by natemcmaster** [comment] 2019-06-04 20:18
The binlog shows that build failed, but as far as I can tell, `dotnet msbuild` is exiting with code 0.

![image](https://user-images.githubusercontent.com/2696087/58910654-eaa97280-86ca-11e9-807e-dd99aced8b1c.png)

https://github.com/dotnet/arcade/blob/b6107674719638ea0794f01bd32e3069de6388eb/eng/common/tools.sh#L424-L428

**Comment by rainersigwald** [comment] 2019-06-04 21:16
Looking at the binlog, these are warnings that are promoted to errors, so the expected behavior is that the build finishes (as though they were warnings) and then is marked as a failure.

Doing that in a small way works:

outer.proj

```xml
<Project>
 <Target Name="X">
  <MSBuild Projects="warnaserror.proj" />
 </Target>
</Project>
```

warnaserror.proj
```xml
<Project>
 <Target Name="X">
  <Warning Text="wrn" />
 </Target>
</Project>
```

```sh-session
$ dotnet msbuild .\outer.proj -warnaserror
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core                                                    Copyright (C) Microsoft Corporation. All rights reserved.                                                                                                                                                                                       S:\repro\dotnet\arcade\issues\2942\warnaserror.proj(3,3): error : wrn                                                   
$ echo $lastexitcode
1
```

so I wonder what's different here. I don't see any obviously fishy "continue on error" or anything in the MSBuild task calls.

**Comment by markwilkie** [comment] 2019-06-12 20:24
@rainersigwald - thoughts on next steps?

**Comment by markwilkie** [comment] 2019-06-26 20:28
ping @rainersigwald

**Comment by markwilkie** [comment] 2019-07-17 20:49
Let me know your thoughts when you're back @natemcmaster

**Comment by natemcmaster** [comment] 2019-07-18 04:07
Sounds like a bug in MSBuild.

**Comment by markwilkie** [comment] 2019-07-18 17:15
@rainersigwald - should this bug be moved to msbuild?

**Comment by markwilkie** [comment] 2019-08-30 17:47
Closing given that there's zero traction here, and no further complaints

**Closed by markwilkie** 2019-08-30 17:47 UTC
