### ISSUE TITLE
build.windows.amd64.vs2022.pre.open images missing git

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#9706] opened 2022-06-16 17:09 UTC
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1828228

### Build leg reported

Build_Windows_Debug / Shallow Checkout

### Pull Request

https://github.com/dotnet/roslyn/pull/61951

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "'git' is not recognized as an internal or external command"
 }
 ```

### Additional information about the issue reported

It appears that git is now missing from these machines
### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[1832111](https://dev.azure.com/dnceng/public/_build/results?buildId=1832111)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832111/logs/43)
|[1828230](https://dev.azure.com/dnceng/public/_build/results?buildId=1828230)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828230/logs/28)
|[1828229](https://dev.azure.com/dnceng/public/_build/results?buildId=1828229)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828229/logs/83)
|[1828668](https://dev.azure.com/dnceng/public/_build/results?buildId=1828668)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828668/logs/20)
|[1828671](https://dev.azure.com/dnceng/public/_build/results?buildId=1828671)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828671/logs/17)
|[1828670](https://dev.azure.com/dnceng/public/_build/results?buildId=1828670)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828670/logs/39)
|[1828701](https://dev.azure.com/dnceng/public/_build/results?buildId=1828701)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828701/logs/39)
|[1828956](https://dev.azure.com/dnceng/public/_build/results?buildId=1828956)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828956/logs/36)
|[1828959](https://dev.azure.com/dnceng/public/_build/results?buildId=1828959)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828959/logs/9)
|[1828955](https://dev.azure.com/dnceng/public/_build/results?buildId=1828955)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1828955/logs/75)
|[1830853](https://dev.azure.com/dnceng/public/_build/results?buildId=1830853)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1830853/logs/33)
|[1830852](https://dev.azure.com/dnceng/public/_build/results?buildId=1830852)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1830852/logs/49)
|[1831975](https://dev.azure.com/dnceng/public/_build/results?buildId=1831975)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1831975/logs/17)
|[1831976](https://dev.azure.com/dnceng/public/_build/results?buildId=1831976)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1831976/logs/6)
|[1831991](https://dev.azure.com/dnceng/public/_build/results?buildId=1831991)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1831991/logs/6)
|[1831990](https://dev.azure.com/dnceng/public/_build/results?buildId=1831990)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1831990/logs/13)
|[1831974](https://dev.azure.com/dnceng/public/_build/results?buildId=1831974)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1831974/logs/147)
|[1832008](https://dev.azure.com/dnceng/public/_build/results?buildId=1832008)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832008/logs/6)
|[1832007](https://dev.azure.com/dnceng/public/_build/results?buildId=1832007)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832007/logs/17)
|[1832019](https://dev.azure.com/dnceng/public/_build/results?buildId=1832019)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832019/logs/17)
|[1832020](https://dev.azure.com/dnceng/public/_build/results?buildId=1832020)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832020/logs/6)
|[1832006](https://dev.azure.com/dnceng/public/_build/results?buildId=1832006)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832006/logs/64)
|[1832018](https://dev.azure.com/dnceng/public/_build/results?buildId=1832018)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832018/logs/64)
|[1832089](https://dev.azure.com/dnceng/public/_build/results?buildId=1832089)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832089/logs/17)
|[1832090](https://dev.azure.com/dnceng/public/_build/results?buildId=1832090)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832090/logs/6)
|[1832088](https://dev.azure.com/dnceng/public/_build/results?buildId=1832088)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832088/logs/64)
|[1838957](https://dev.azure.com/dnceng/public/_build/results?buildId=1838957)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1838957/logs/66)
|[1836825](https://dev.azure.com/dnceng/public/_build/results?buildId=1836825)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1836825/logs/39)
|[1836826](https://dev.azure.com/dnceng/public/_build/results?buildId=1836826)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1836826/logs/6)
|[1831698](https://dev.azure.com/dnceng/public/_build/results?buildId=1831698)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1831698/logs/49)
|[1835809](https://dev.azure.com/dnceng/public/_build/results?buildId=1835809)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835809/logs/61)
|[1835576](https://dev.azure.com/dnceng/public/_build/results?buildId=1835576)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835576/logs/49)
|[1835592](https://dev.azure.com/dnceng/public/_build/results?buildId=1835592)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835592/logs/57)
|[1835588](https://dev.azure.com/dnceng/public/_build/results?buildId=1835588)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835588/logs/57)
|[1835554](https://dev.azure.com/dnceng/public/_build/results?buildId=1835554)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835554/logs/33)
|[1835566](https://dev.azure.com/dnceng/public/_build/results?buildId=1835566)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835566/logs/33)
|[1834626](https://dev.azure.com/dnceng/public/_build/results?buildId=1834626)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1834626/logs/66)
|[1834382](https://dev.azure.com/dnceng/public/_build/results?buildId=1834382)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1834382/logs/91)
|[1833463](https://dev.azure.com/dnceng/public/_build/results?buildId=1833463)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833463/logs/17)
|[1833464](https://dev.azure.com/dnceng/public/_build/results?buildId=1833464)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833464/logs/6)
|[1832564](https://dev.azure.com/dnceng/public/_build/results?buildId=1832564)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832564/logs/57)
|[1832300](https://dev.azure.com/dnceng/public/_build/results?buildId=1832300)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832300/logs/85)
|[1832301](https://dev.azure.com/dnceng/public/_build/results?buildId=1832301)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832301/logs/17)
|[1832302](https://dev.azure.com/dnceng/public/_build/results?buildId=1832302)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832302/logs/6)
|[1832533](https://dev.azure.com/dnceng/public/_build/results?buildId=1832533)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832533/logs/17)
|[1832534](https://dev.azure.com/dnceng/public/_build/results?buildId=1832534)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832534/logs/6)
|[1832532](https://dev.azure.com/dnceng/public/_build/results?buildId=1832532)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832532/logs/65)
|[1832567](https://dev.azure.com/dnceng/public/_build/results?buildId=1832567)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832567/logs/6)
|[1832565](https://dev.azure.com/dnceng/public/_build/results?buildId=1832565)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832565/logs/17)
|[1833295](https://dev.azure.com/dnceng/public/_build/results?buildId=1833295)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833295/logs/17)
|[1833296](https://dev.azure.com/dnceng/public/_build/results?buildId=1833296)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833296/logs/6)
|[1833294](https://dev.azure.com/dnceng/public/_build/results?buildId=1833294)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833294/logs/65)
|[1833462](https://dev.azure.com/dnceng/public/_build/results?buildId=1833462)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833462/logs/63)
|[1833610](https://dev.azure.com/dnceng/public/_build/results?buildId=1833610)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833610/logs/17)
|[1833611](https://dev.azure.com/dnceng/public/_build/results?buildId=1833611)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833611/logs/6)
|[1833609](https://dev.azure.com/dnceng/public/_build/results?buildId=1833609)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833609/logs/197)
|[1834381](https://dev.azure.com/dnceng/public/_build/results?buildId=1834381)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1834381/logs/7)
|[1834383](https://dev.azure.com/dnceng/public/_build/results?buildId=1834383)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1834383/logs/17)
|[1834384](https://dev.azure.com/dnceng/public/_build/results?buildId=1834384)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1834384/logs/6)
|[1834627](https://dev.azure.com/dnceng/public/_build/results?buildId=1834627)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1834627/logs/34)
|[1834629](https://dev.azure.com/dnceng/public/_build/results?buildId=1834629)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1834629/logs/17)
|[1835154](https://dev.azure.com/dnceng/public/_build/results?buildId=1835154)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835154/logs/6)
|[1835153](https://dev.azure.com/dnceng/public/_build/results?buildId=1835153)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835153/logs/17)
|[1835298](https://dev.azure.com/dnceng/public/_build/results?buildId=1835298)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835298/logs/17)
|[1835299](https://dev.azure.com/dnceng/public/_build/results?buildId=1835299)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835299/logs/6)
|[1835297](https://dev.azure.com/dnceng/public/_build/results?buildId=1835297)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835297/logs/147)
|[1835590](https://dev.azure.com/dnceng/public/_build/results?buildId=1835590)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835590/logs/6)
|[1835589](https://dev.azure.com/dnceng/public/_build/results?buildId=1835589)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835589/logs/9)
|[1835577](https://dev.azure.com/dnceng/public/_build/results?buildId=1835577)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835577/logs/33)
|[1835593](https://dev.azure.com/dnceng/public/_build/results?buildId=1835593)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835593/logs/36)
|[1835595](https://dev.azure.com/dnceng/public/_build/results?buildId=1835595)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835595/logs/16)
|[1835563](https://dev.azure.com/dnceng/public/_build/results?buildId=1835563)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835563/logs/33)
|[1835552](https://dev.azure.com/dnceng/public/_build/results?buildId=1835552)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835552/logs/65)
|[1835562](https://dev.azure.com/dnceng/public/_build/results?buildId=1835562)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835562/logs/73)
|[1835565](https://dev.azure.com/dnceng/public/_build/results?buildId=1835565)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835565/logs/61)
|[1835811](https://dev.azure.com/dnceng/public/_build/results?buildId=1835811)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835811/logs/6)
|[1835810](https://dev.azure.com/dnceng/public/_build/results?buildId=1835810)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1835810/logs/16)
|[1836646](https://dev.azure.com/dnceng/public/_build/results?buildId=1836646)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1836646/logs/13)
|[1836647](https://dev.azure.com/dnceng/public/_build/results?buildId=1836647)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1836647/logs/6)
|[1836645](https://dev.azure.com/dnceng/public/_build/results?buildId=1836645)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1836645/logs/65)
|[1836824](https://dev.azure.com/dnceng/public/_build/results?buildId=1836824)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1836824/logs/146)
|[1837203](https://dev.azure.com/dnceng/public/_build/results?buildId=1837203)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1837203/logs/24)
|[1837202](https://dev.azure.com/dnceng/public/_build/results?buildId=1837202)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1837202/logs/73)
|[1838959](https://dev.azure.com/dnceng/public/_build/results?buildId=1838959)|dotnet/roslyn|Shallow Checkout|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1838959/logs/33)
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|6|84|84|

**Comment by mmitche** [comment] 2022-06-16 17:27
@CyrusNajmabadi It looks like roslyn is using manual git commands to get a shallow fetch. There are native options in the azure devops checkout....i'll try:

```
fetchDepth: 1 # Fetch only one commit
```

Let me give it a try

**Comment by MattGal** [comment] 2022-06-22 17:17
The revert is rolled out, closing

**Closed by MattGal** 2022-06-22 17:17 UTC
Labels: Critical, First Responder, Detected By - Customer, Known Build Error

**Comment by premun** [comment] 2022-06-23 08:17
Do we still care about the original issue though?

**Comment by MattGal** [comment] 2022-06-27 16:08
> Do we still care about the original issue though?

No, it was a mistake for me to file it.  My assumption was that VS installing git meant git was on the path on the machine, which it did not.  Our git artifact thus is needed even where Git already is installed by the IDE to get it to be on the path, just in case people want to clone their repo via an arbitrary script instead of the prescribed, Azure DevOps way.

The motivation of the original issue is in the funky way we generate build images and infinite hangs being caused by a modal dialog when the git artifact got older than the git VS brought along.  This has been obviated by  using DHandler and an interactive login session while generating ImageFactory images, so while this scenario should still fail (requiring an artifact update), it should do so quickly in the validate phase, not with an 8 hour timeout.

**Comment by premun** [comment] 2022-06-28 07:57
Ah, if DHandler mitigates the hangs then that's great!

I was just thinking we could have put the VS git on PATH and that'd be it but this is better.

**Comment by MattGal** [comment] 2022-06-28 15:14
> Ah, if DHandler mitigates the hangs then that's great!

To be fair, all these things are true but it's still possible another problem falls out.  We're definitely running dhandler now, and Image Factory always uses an interactive windows session now, though, giving the best chance to recover more gracefully.
