### ISSUE TITLE
5.0 arcade update PRs failing on Linux source builds

### ISSUE THREAD

**Issue by pranavkm** [dotnet/arcade#4200] opened 2019-10-24 20:46 UTC
Two separate repos with the same failure:

* https://github.com/aspnet/AspNetCore-Tooling/pull/1258
* https://github.com/aspnet/Extensions/pull/2559
* https://github.com/aspnet/AspNetCore/pull/15192/checks?check_run_id=274053611

I'm able to reproduce the failure locally (in a WSL session). Here's a binlog: [Build.binlog.zip](https://github.com/aspnet/AspNetCore-Tooling/files/3769102/Build.binlog.zip) (strip the .zip extension)

**Comment by markwilkie** [comment] 2019-10-24 22:40
What are the errors @pranavkm ?

**Comment by pranavkm** [comment] 2019-10-24 22:44
Here's the build log:

```
/__w/1/s/.dotnet/sdk/5.0.100-alpha1-014696/MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:/__w/1/s/artifacts/log/Release/ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /nr:false /p:TreatWarningsAsErrors=true /p:ContinuousIntegrationBuild=true /p:__ToolsetLocationOutputFile=/__w/1/s/artifacts/toolset/5.0.0-beta.19518.2.txt /t:__WriteToolsetLocation /warnaserror /__w/1/s/artifacts/toolset/restore.proj
info : Clearing NuGet HTTP cache: /home/vsts_azpcontainer/.local/share/NuGet/v3-cache
info : Local resources cleared.
/__w/1/s/.dotnet/sdk/5.0.100-alpha1-014696/MSBuild.dll /nologo -logger:/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/netcoreapp2.1/Microsoft.DotNet.Arcade.Sdk.dll -maxcpucount /m -verbosity:m /v:minimal /bl:/__w/1/s/artifacts/log/Release/Build.binlog /clp:Summary /nr:false /p:TreatWarningsAsErrors=true /p:ContinuousIntegrationBuild=true /p:Configuration=Release /p:RepoRoot=/__w/1/s /p:Restore=true /p:Build=true /p:Rebuild=false /p:Test=false /p:Pack=false /p:IntegrationTest=false /p:PerformanceTest=false /p:Sign=false /p:Publish=false /p:ProjectToBuild=/__w/1/s/eng/tools/RepoTasks/RepoTasks.csproj /warnaserror /__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/Build.proj
  Restore completed in 5.04 sec for /__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/Tools.proj.
dotnet_install: Warning: Unable to locate libunwind. Probable prerequisite missing; install libunwind.
dotnet_install: Warning: Unable to locate libicu. Probable prerequisite missing; install libicu.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha1.19521.2/dotnet-runtime-5.0.0-alpha1.19521.2-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha1.19521.2/dotnet-runtime-5.0.0-alpha1.19521.2-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/__w/1/s/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
  Restore completed in 15.17 sec for /__w/1/s/eng/tools/RepoTasks/RepoTasks.csproj.
  RepoTasks -> /__w/1/s/artifacts/bin/RepoTasks/Release/netcoreapp5.0/RepoTasks.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:30.03
info : Clearing NuGet HTTP cache: /home/vsts_azpcontainer/.local/share/NuGet/v3-cache
info : Local resources cleared.
/__w/1/s/.dotnet/sdk/5.0.100-alpha1-014696/MSBuild.dll /nologo -logger:/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/netcoreapp2.1/Microsoft.DotNet.Arcade.Sdk.dll -maxcpucount /m -verbosity:m /v:minimal /bl:/__w/1/s/artifacts/log/Release/Build.binlog /clp:Summary /nr:false /p:TreatWarningsAsErrors=true /p:ContinuousIntegrationBuild=true /p:Configuration=Release /p:RepoRoot=/__w/1/s /p:Restore=true /p:Build=true /p:Rebuild=false /p:Test=false /p:Pack=true /p:IntegrationTest=false /p:PerformanceTest=false /p:Sign=false /p:Publish=false /p:BuildManaged=true /p:BuildNodeJs=false /warnaserror /__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/Build.proj
/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/Tools.proj : error MSB4057: The target "Restore" does not exist in the project.
##[error].packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/Tools.proj(0,0): error MSB4057: The target "Restore" does not exist in the project.

Build FAILED.

/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/Tools.proj : error MSB4057: The target "Restore" does not exist in the project.
    0 Warning(s)
    1 Error(s)
```

**Comment by pranavkm** [comment] 2019-10-24 22:44
The specific error is 

`##[error].packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.19518.2/tools/Tools.proj(0,0): error MSB4057: The target "Restore" does not exist in the project.`

**Comment by markwilkie** [comment] 2019-10-24 23:02
@pranavkm - this feels to me like something in your build.  @dotnet/dnceng - could one of you help @pranavkm understand what's happening here please?

**Comment by MattGal** [comment] 2019-10-24 23:51
I'm looking at this and scratching my head.  The only interesting thing that changed here from when this last worked is the Arcade SDK version, which made a HUGE jump, 1.0.0-beta.19510.3 -> 5.0.0-beta.19518.2.  Arcade SDK was on 2.0.0 for a long time and jumped to 5, starting from 1 makes it seem like an older breaking change may be coming into play here.

**Comment by MattGal** [comment] 2019-10-25 00:35
@markwilkie  I think I understand it, though we'll need to chat with some folks about the "right" fix.  

Basically @tmat  made this commit 10 days ago: https://github.com/dotnet/arcade/commit/961b7d2e1c75b331e498cb4711984869809bb00e which ends up not loading NuGet.targets (which would be loaded from `./.dotnet/sdk/5.0.100-alpha1-014696/NuGet.targets` if   Condition="'$(DotNetBuildFromSource)' != 'true'" were not satisfied) 

Since this is restoring stuff from Nuget, it does kind of make sense that it might turn off in a source build, but that's where it comes from and perhaps we can rethink how to get the Tools.proj's dependencies in the case where it's build from source.

**Comment by ryanbrandenburg** [comment] 2019-10-25 17:08
@MattGal is there an ETA here? This issue is blocking our dependency updates, so we're eager to resolve it.

**Comment by MattGal** [comment] 2019-10-25 18:17
@ryanbrandenburg  let me chat w/ Tomas when I can find him.  I found the cause of the error but I'm not sure I understand why a build-from-source thing would be trying to restore.

**Comment by BrennanConroy** [comment] 2019-10-31 15:48
Has there been any progress on this issue? (you're likely going to get a different person pinging this issue every couple days)

**Comment by dagood** [comment] 2019-10-31 17:15
@crummel may also have context on the ASP.NET Core source-build job. I believe it's just an emulation of source-build to make sure the basics don't break, so restores would be expected.

**Comment by MattGal** [comment] 2019-10-31 17:21
Ah.  So perhaps inclusion of that targets is acceptable then.  You could 1) explicitly import that targets, 2) add an extra property to https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj#L20 that allows you to turn it on or 3) just set `DotNetBuildFromSource=false` since this is a mock source build.

**Comment by MattGal** [comment] 2019-10-31 18:28
@pranavkm after some more looking I think the problem is simply these two lines:

https://github.com/aspnet/AspNetCore-Tooling/blob/master/eng/scripts/ci-source-build.sh#L15
https://github.com/aspnet/AspNetCore-Tooling/blob/master/eng/scripts/ci-source-build.sh#L18

From chatting with @tmat the best thing here is to remove those lines, see what happens, and if your emulated source build thing is broken to fix from there.

**Comment by MattGal** [comment] 2019-10-31 18:38
After longer discussion with Tomas I created https://github.com/dotnet/arcade/pull/4260

**Comment by crummel** [comment] 2019-10-31 19:07
We haven't done much with 5.0 in source-build yet.  Does just importing NuGet targets cause the restore to run?  That seems like the thing that ought to change, not just skipping the import.

**Comment by tmat** [comment] 2019-10-31 19:10
Restore target will run but there should be no packages to be restored.

**Comment by MattGal** [comment] 2019-10-31 22:20
PR is merged, I'll keep this around until we can verify that the ASP simulated source build is unblocked.

**Comment by BrennanConroy** [comment] 2019-10-31 22:26
I updated to 31.8 in [this PR](https://github.com/aspnet/AspNetCore/pull/16716), so we'll see if it worked soon.

**Comment by BrennanConroy** [comment] 2019-10-31 22:29
Linux Source Build target passed :+1:

**Comment by MattGal** [comment] 2019-10-31 22:33
Thanks Brennan, I'm going to close this for now then.

**Closed by MattGal** 2019-10-31 22:33 UTC
Labels: First Responder
