### ISSUE TITLE
[Darc/Maestro+] Barviz should limit how much of a commit message is displayed in the repo build.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6287] opened 2020-09-30 18:27 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See https://maestro-prod.westus2.cloudapp.azure.com/1157/https:%2F%2Fgithub.com%2Fdotnet%2Fruntime/63845/graph

A long commit message makes the button take up most of the available space and doesn't convey a lot of interesting information.
![image](https://user-images.githubusercontent.com/23242101/94724836-b7ebaa80-030f-11eb-8dda-c5da7f7e625a.png)

**Comment by garath** [comment] 2020-10-01 20:46
Triage: @tkapin Do you think this should go into the telemetry epic?

**Comment by tkapin** [comment] 2020-10-05 17:28
@riarenas - this was done as part of the summer internship project, so it belongs to #3326 which tracked that work. I'm closing this one as duplicate of #6309.

**Closed by tkapin** 2020-10-05 17:28 UTC
