### ISSUE TITLE
checksum mismatch between blob storage checksum files and files on blob after repo propogation

### ISSUE THREAD

**Issue by rbhanda** [dotnet/arcade#7555] opened 2021-06-23 22:38 UTC
"\\vsufile\patches\sign\NET\NET_CORE\6.0.0-preview.5\publish_files\vs_pipeline_json\6.0.0-preview.5-sha.txt" the checksum file did not match the files hosted on \\vsufile\patches\sign\NET\NET_CORE\6.0.0-preview.5\publish_files\files_to_publish or on the blob storage after repo propagation stage.

**Comment by riarenas** [comment] 2021-07-08 16:32
@adiaaida is this something that happens in the release pipeline and should be part of the release epic?

**Comment by adiaaida** [comment] 2021-07-08 16:35
Adding to the release epic

**Comment by adiaaida** [comment] 2021-08-05 16:24
We had two builds that ran for this release, and both had some of the same files (for example, windowsdesktop was the same between the two versions). The first build signed and uploaded the files to dotnetstage. But then we decided we wanted a different version of the sdk, so we ran another build, which signed and attempted to upload the new files. Because signing isn’t deterministic (it uses the timestamp as part of the process), the files were slightly different, so when we attempted to upload the files, it was rejected, and the older files, with different hashes, remained.

Several solutions have been proposed, but ultimately, we decided that we would move the publishing to dotnet-stage to the same phase as where we publish to vsufile. That way, we have declared this is a final build, and we shouldn't see this anymore, assuming that whoever approves the finalization does so appropriately.

Since we have mitigated this issues, and know the root cause, I am going to close this issue.

**Closed by adiaaida** 2021-08-05 16:24 UTC
