### ISSUE TITLE
Add word wrap to build analysis output

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/arcade#9181] opened 2022-04-25 16:33 UTC
- [ x] This issue is causing unreasonable pain

When using the build analysis tab with the installer repo, missing word wrap and long test output is causing difficulties using that tab. There is no horizontal scroll back. I can get it to scroll right through the followings steps:
- double click the word _Expected_
- Shift+End should scroll right and select the whole string

Once I'm in that spot, I can copy the string into another editor to view it but I can't get back to the original view. The below screenshots are the full width of my screen with no scroll bar.

https://github.com/dotnet/installer/pull/13689/checks?check_run_id=6155107175
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/12663534/165133014-fb685dd5-68bd-4526-9282-a2a11cef7ac5.png">

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/12663534/165133376-0008ccb9-4ce1-4001-8286-414e34d02262.png">

**Comment by ChadNedzlek** [comment] 2022-04-25 20:23
This is a duplicate of #9029 the tradeoffs here are tricky.

**Closed by ChadNedzlek** 2022-04-25 20:23 UTC

**Comment by ChadNedzlek** [comment] 2022-04-25 20:25
This one is a little weird. This exception message shouldn't be full of "\n" characters.

**Comment by ChadNedzlek** [comment] 2022-04-25 20:43
It seems like the SDK is producing odd exception messages.  This doesn't look like a helix test, so it's not a helixism.  It might be an old version of XUnit that's causing it? I recall XUnit had this bug years ago.
