### ISSUE TITLE
Publish logs fails with warning when retrying the build

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#6699] opened 2020-12-16 21:21 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Example build: https://dnceng.visualstudio.com/public/_build/results?buildId=922618&view=logs&j=63abaf99-68fc-55da-565b-69ac46624d34&t=c27b7b87-d8c4-561f-d89c-7e7d6447b7e2&l=37

It would be great if the attempt number would we added to the log file name if the attempt is > 1 to avoid this error.

cc @safern

**Comment by safern** [comment] 2020-12-16 21:23
cc: @alexperovich @chcosta

**Comment by ViktorHofer** [comment] 2020-12-16 21:23
@dotnet/runtime-infrastructure we might want to do this in dotnet/runtime as well in places where we specify the file name ourselves.

**Comment by ChadNedzlek** [comment] 2021-02-05 00:20
I'm not... 100% sure what this issue is talking about, because the build it's referencing is expired.  Is it logs, like "binlog" that we push as build artifacts? Or some other sort of log/upload?

**Comment by safern** [comment] 2021-02-05 00:28
The problem is the artifact name. Arcade publishes everything under `artifacts/log/BuildConfig` as an artifact, when you retry the build it fails to publish them because the artifact already exists, producing a warning on the build which adds churn to the build logs/timeline. 

It is just a matter of appending the build attempt to the artifact name.

**Comment by ChadNedzlek** [comment] 2021-02-05 00:29
Gotcha. So it's the "upload build artifacts". That shouldn't be too hard to do.  It's a little weird Azure doesn't handle that already... (it makes total sense that I'd want to see the artifacts from a previous attempt). But it doesn't!

**Comment by safern** [comment] 2021-02-05 00:35
Yeah, I don't know if that might be feedback we could give to them... I would expect the same thing, just as "logs". If the artifact didn't change show me the artifact from the previous attempt, if it changed, show me the one from the last attempt.

**Comment by ChadNedzlek** [comment] 2021-02-05 00:37
It'll get weird if something tries to download them... because you wouldn't know what attempt number to look for, so we'll need to make sure we only do it for sort of supplementary artifacts, that aren't meant to be downloaded by subsequent jobs/stages

**Comment by trylek** [comment] 2021-02-05 01:25
I agree with Santi that for logs this would be super valuable; for other build artifacts like CoreCLR / library build / test drops, I think Chad has a valid point that duplicating them across multiple pipeline attempts would be prone to various downstream issues, moreover the "non-log" artifacts are sometimes rather large - an extra motivation to avoid their duplication. Ultimately, I believe that retrying pipelines is supposed to be a last resort kind of thing, we should strive to make our pipelines sufficiently stable so that we don't need that option most of the time. When we do, we generally agree to nullify the results of the former run on the grounds of HW / infra instability and keeping the older versions of all artifacts seems to have little value in such case.

**Comment by ChadNedzlek** [comment] 2021-02-05 01:46
Is there some way to remove the warning?  It sounds like that's the primary complaint here... that it causes the subsequent attempts to pump out a slew of warnings about overriding them.

It also seems like when a build is retried, the original logs probably are much lower value... though it might end up being useful if there is some persistent but non-deterministic build problem that requires the artifacts in order to debug... but perhaps that's a problem to worry about if we end up in that state.

**Comment by safern** [comment] 2021-02-05 02:17
I don't think there is way to remove the warning as the step is failing but has `continueOnError: true`, which automatically causes a warning instead of an error. 

https://github.com/dotnet/arcade/blob/master/eng/common/templates/job/job.yml#L171-L175

**Comment by trylek** [comment] 2021-02-07 21:27
Would it be possible to fix this one by including the pipeline attempt number in the log artifact name? This bit is specific to log publishing so it shouldn't affect other artifacts. @riarenas, would you find this an acceptable Arcade fix to get rid of the spurious warnings? On top of just fixing the warnings I believe there are certain situations where we're automatically retrying runs due to HW instability and the presence of logs from all attempts might be actually helpful for longer-term investigation / monitoring of the issue.

**Comment by missymessa** [comment] 2021-03-30 21:01
If the overwriting of the logs becomes a problem, we will re-open and address. Closing.

**Closed by missymessa** 2021-03-30 21:01 UTC
Labels: dev-workflow
