### ISSUE TITLE
Classic maestro's mirroring doesn't work when branches are newly created with no changed files

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4871] opened 2020-02-19 16:13 UTC
-  Is this issue blocking **no**
-  Is this issue causing unreasonable pain **yes**

When a branch is newly created (e.g. in the GH UI), the webhook fires as normal, but the list of files will be empty. This will cause the mirror triggers in the classic Maestro subscriptions file to not fire, because they are based on the list of files.

This means the mirror definition needs to be manually fired off, or the branch manually pushed to start the process. Ideally if the file list is empty on a push, the trigger should still run. Sort of like "any file under this branch blob path is changed".

**Comment by dagood** [comment] 2020-02-19 16:32
Duplicate of https://github.com/dotnet/versions/issues/110

**Comment by markwilkie** [comment] 2020-09-08 14:55
Closing given that the epic closed.

**Comment by dagood** [comment] 2020-09-08 15:27
> Closing given that the epic closed.

This reason doesn't make sense to me. Closing an epic doesn't mean that every issue in it is completed.

**Comment by dagood** [comment] 2020-09-08 15:28
If you think this has low enough priority that it should be closed because it'll never happen, that's fine, and go ahead, but I'd like to understand that close reason better.

**Comment by adiaaida** [comment] 2022-02-17 22:07
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.

**Closed by adiaaida** 2022-02-17 22:07 UTC
