### ISSUE TITLE
Issue prevents deployment of new M2 Mac hardware into Helix

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#13166] opened 2023-04-14 07:23 UTC
While attempting to deploy the first M2 hardware Mac into Helix, it failed to complete successfully and halted on the OS validation step of the deployment script.  I was able to see some python/pip errors at the end that could be related, but the script may need to be looked into for supporting the new M2 hardware.

It does look like the script loaded the helix agent bits onto the system, but did not configure it to start due to failing the validation.

![image](https://user-images.githubusercontent.com/19270857/231972569-b28d513a-4356-44a5-8026-a16651c762eb.png)

System: dci-macm2-build-001 (Available in MLSKVMUI)
Queue: osx.13.arm64.open
IP: 10.197.203.151
 
 
![image](https://user-images.githubusercontent.com/19270857/231972758-a621121c-e4a9-4595-b774-712a664af392.png)

![image](https://user-images.githubusercontent.com/19270857/231972857-fb1bcfa2-ece3-4512-861f-0b3c2c66289e.png)

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description
Fixes problems with bootstrapping new MacOS M2 on-prem machines

**Comment by premun** [comment] 2023-04-14 10:18
First round of investigations - I found that the problem is with the `setuptools` python package which is missing and it's then failing when we call `get-pip.py` in `linux-pip.sh`. I found out we can all `get-pip.py --no-setuptools` and it seems to work.

https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/artifacts/linux-pip/linux-pip.sh&version=GBmain&line=38&lineEnd=39&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by premun** [comment] 2023-04-14 10:43
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/30673

**Comment by parose1** [comment] 2023-04-28 18:15
Hi all, I just wanted to update that after Wednesdays Helix rollout we were able to successfully run the helix script on these M2 Mac machines, but after Thursdays rollout we are getting this issue again. Was anything reverted in the Thursday rollout?

Screenshot of running the script on 002 on Thursday after the helix servcie rollout:

![image](https://user-images.githubusercontent.com/48035740/235222926-818d1f9b-4aad-4208-a79c-aadaf0ab6614.png)

**Comment by AlitzelMendez** [comment] 2023-05-01 22:17
@parose1, was this working before Wednesday? 

There was only a rollout on Thursday. I’m trying to understand if this was working perfectly until the rollout on Thursday or if it worked only briefly.

We haven’t rolled out @premun changes that will fix this, Premek did you do something additionally to fix this? Or do we need to wait until the rollout of your PR?

**Comment by parose1** [comment] 2023-05-01 22:39
@AlitzelMendez It was not working before last Wednesday. It may not be rollout related we just know rollouts typically happen on Wednesdays. We ran the deployment script and saw it was working on Wednesday, and then did not work again when we tried it on Thursday.

**Comment by Shawn-Lemhouse** [comment] 2023-05-02 02:55
@AlitzelMendez

A possible scenario.  if dci-macm2-build-001 was being used to test at all, and the missing python packages were loaded manually as part of that testing, could that have caused the running of the OSOB script afterwards to complete successfully?

That would explain why my attempt on Wednesday last week succeeded, but when I moved onto the 2nd system it still failed when ran on a fresh machine.

We likely still just need to wait until the rollout of @premun 's fix before we continue configuring these systems.

**Comment by premun** [comment] 2023-05-02 07:49
@Shawn-Lemhouse is right - I did install those packages on the machine when testing a fix for this. The fix I have prepared unfortunately hasn't made it in yet. I will be working on that this week.

**Comment by premun** [comment] 2023-05-04 11:40
@parose1 I merged the fix for the python package installation problem. Next Wednesday, after we roll this out, you could have another go ideally with a fresh machine

**Comment by parose1** [comment] 2023-05-04 14:58
@premun Great, thank you for the update. We will try again after next weeks rollout and let you know.

**Comment by parose1** [comment] 2023-05-11 16:11
@premun I have tested 5 M2 Mac machines so far and all are running the helix deployment script without issue and adding to the queue. Thank you!

**Comment by premun** [comment] 2023-05-12 08:04
That's great news, thanks!

**Closed by premun** 2023-05-12 08:04 UTC
Labels: First Responder
