### ISSUE TITLE
Stage-DotNet pipeline coherency check not detecting multiple emsdks

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#10840] opened 2022-09-14 10:15 UTC
Recently, we had a [run of the Stage-DotNet pipeline](https://dev.azure.com/dnceng/internal/_build/results?buildId=1979234&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=f46cfb4d-3fd5-5262-36f1-471a0354c727) that didn't have it's incoherency detected. The validate manifest job finished without detecting two different emsdks. Later, the windows-signing failed because of this. Searching for emsdk in the logs there shows that there are two different BAR IDs: 145179 and 145171

**Comment by adiaaida** [comment] 2022-09-15 17:30
Stage-DotNet only checks that there is only 1 runtime and 1 aspnetcore. No other aspects of coherency are checked today. I'm not sure why signing would be failing due to incoherency. @mmitche

**Comment by michellemcdaniel** [comment] 2022-10-27 19:54
I am going to close this as this is currently working as intended. If we ultimately want to have better coherency checking, we can discuss it, but I believe the VMR will eventually fix it itself.

**Closed by michellemcdaniel** 2022-10-27 19:54 UTC
Labels: area-product-construction
