### ISSUE TITLE
Add support for ValueTuples to GenApi tool

### ISSUE THREAD

**Issue by pakrym** [dotnet/arcade#2028] opened 2019-02-12 00:49 UTC
ASP.NET Core exposes tuples in public API. Currently ApiGen produces the following code that doesn't compile:

``` C#
public TemplateBinder(System.Text.Encodings.Web.UrlEncoder urlEncoder,
 Microsoft.Extensions.ObjectPool.ObjectPool<Microsoft.AspNetCore.Routing.Internal.UriBuildingContext> pool,
 Microsoft.AspNetCore.Routing.Patterns.RoutePattern pattern,
 Microsoft.AspNetCore.Routing.RouteValueDictionary defaults,
 System.Collections.Generic.IEnumerable<string> requiredKeys,
 [System.Runtime.CompilerServices.TupleElementNamesAttribute(new string[]{ "parameterName", "policy"})]
 System.Collections.Generic.IEnumerable<System.ValueTuple<string, Microsoft.AspNetCore.Routing.IParameterPolicy>> parameterPolicies)
 { }
```

```
Microsoft.AspNetCore.Routing.netcoreapp3.0.cs(809,369): error CS8138: Cannot reference 'System.Runtime.CompilerServices.TupleElementNamesAttribute' explicitly. Use the tuple syntax to define tuple names. [D:\github\aspnet\AspNetCore\src\Http\Routing\ref\Microsoft.AspNetCore.Routing.csproj]
```

**Comment by pakrym** [comment] 2019-02-12 01:03
cc @natemcmaster

**Comment by natemcmaster** [comment] 2019-02-12 01:18
Duplicate of https://github.com/dotnet/buildtools/issues/1850, which should probably be moved here. This is a limitation that the corefx team has known about for at least 8 months. I think we'll need to make a PR to this tool since it's not a priority for them.

**Closed** 2019-02-15 21:38 UTC
