### ISSUE TITLE
Helix agents are unable to upload results to Azdo 

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/arcade#13778] opened 2023-06-08 09:42 UTC
### Build

https://dev.azure.com/dnceng/internal/_build/results?buildId=2200348&view=results

### Build leg reported

browser-wasm linux Release LibraryTests_NodeJs

### Pull Request

https://github.com/dotnet/runtime/pull/86759

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

The issue was observed on multiple `runtime-wasm` builds

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by pavelsavara** [comment] 2023-06-08 10:28
I'm not sure this filter would hit, because the error is reported in the python log.

**Comment by missymessa** [comment] 2023-07-28 19:19
@oleksandr-didyk @pavelsavara do you know if this error is still occurring?

**Comment by pavelsavara** [comment] 2023-09-06 14:21
Dupe of https://github.com/dotnet/arcade/issues/13777 ?

**Closed by pavelsavara** 2023-09-06 14:21 UTC
Labels: Ops - First Responder, Known Build Error
