### ISSUE TITLE
Include @dotnet/source-build-internal as code owners for SB files

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/arcade#14273] opened 2023-12-08 18:50 UTC
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

@dotnet/source-build-internal is not tagged as a code owner for [SourceBuildPrebuiltBaseline.xml](https://github.com/dotnet/arcade/blob/main/eng/SourceBuildPrebuiltBaseline.xml). It would be helpful to create a [CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners?algolia-query=code%20owners) and include source-build-internal on SB files. For reference, Aspnet does this in their CODEOWNERS file: https://github.com/dotnet/aspnetcore/blob/36c976723fd0b55dad80f1ff32e665800ea4a021/.github/CODEOWNERS#L19

Having a code owners file would also be generally useful when opening PRs in this repo, as it can sometimes be difficult and time consuming to determine who should be included as a reviewer.

**Comment by garath** [comment] 2023-12-08 19:46
Duplicate of #9555.

In the past, CODEOWNERS has been avoided because Arcade is _shared_ infra (it takes a village) and pinning any person, team or group to any particular piece of code here gets a lot of debate. 

But of course, if it is correct that source-build-internal owns bits, a CODEOWNERS would be useful. Would you consider opening a PR with ownership set as your team sees appropriate?

**Closed** 2024-01-16 19:32 UTC
