### ISSUE TITLE
Should versioning scheme be improved?

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3044] opened 2019-06-13 06:50 UTC
Please see comments from @vatsan-madhavan on this issue: https://github.com/dotnet/arcade/issues/2936

/cc @tmat @mmitche @markwilkie

**Comment by tmat** [comment] 2019-06-13 17:45
I don't see a proposal for a different versioning scheme.

**Comment by mmitche** [comment] 2019-06-13 17:58
Even if two different branches produce similar looking versions, they will not overlap as long as the date suffix is included.  As far as I can tell, there is no issue at the current time.

**Comment by tmat** [comment] 2019-06-13 18:01
That is correct. The official build number we use to generate the version is stored per build definition and increasing every build.

**Comment by vatsan-madhavan** [comment] 2019-06-13 19:24
@tmat the issue is that @JohnTortugo had a specific instance of two builds producing and publishing identically versioned packages. Could that have been prevented easily, or was the underlying problem that the builds used different build-definitions (and thus it was really not a preventable problem)?

**Comment by vatsan-madhavan** [comment] 2019-06-13 19:59
https://github.com/dotnet/arcade/issues/2936#issuecomment-501850548
https://github.com/dotnet/arcade/issues/2936#issuecomment-501853954

> Right. Yaml changes never require another build pipeline. You can just make changes in the appropriate branch, as the yaml build logic is always read from the branch being build. The build pipeline itself had unique build numbers regardless of branch (e.g. if master builds as 1, then release,/3.0 builds, it will be given number 2).



> > @JohnTortugo, in your case when two packages were produced, I'm assuming that they happened on different build-definitions? If so, I think that would explain the problem...
> 
> Yes, different build definitions.

The linked comments I think explain what happened, and that the versioning process is in fact non-overlapping as long as we use the same build definition (even when the Yaml is different for different branches etc.). 

Given this, I think we can close this issue. 

@JohnTortugo, @mmitchel, @tmat , thanks for patiently digging into the details and helping understand how this works!

**Comment by mmitche** [comment] 2019-06-14 15:38
Thanks @vatsan-madhavan

**Closed by mmitche** 2019-06-14 15:38 UTC
