### ISSUE TITLE
OneLocBuild erroneously sets AutoCompletePr to true 

### ISSUE THREAD

**Issue by peterwald** [dotnet/arcade#9048] opened 2022-04-13 17:29 UTC
- [X] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Our servicing branch builds are failing because OneLocBuild is trying to auto complete the loc PR, but it doesn't have permissions to complete it (and we don't want it to).

Here is a link to an [example build task.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6020055&view=logs&j=c0636702-cad1-5e4d-7b5b-f15c1cce530a&t=ef3c2779-04f6-5216-b20f-460f31132ece)

The error we are getting in the log is:
```
OneLocBuildClient.exe Information: 0 : Pull request created with ID '392951'.
OneLocBuildClient.exe Information: 0 : Completing the pull request...
OneLocBuildClient.exe Error: 0 : Microsoft.VisualStudio.Services.Common.VssServiceException: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\011b8bdf-6d56-4f87-be0d-0092136884d9', scope 'branch'.
```

At the top of the log, I see one of the arguments listed is:
```
OneLocBuildClient.exe Information: 0 : /autocompletepr: True
```

However, we have not set AutoCompletePR, and it is still set to false in the template file loaded from the arcade folder.

/cc @AbhitejJohn

**Comment by AbhitejJohn** [comment] 2022-04-14 23:15
Tagging @jonfortescue for thoughts.

**Comment by jonfortescue** [comment] 2022-04-14 23:53
Sorry, took a look at this this morning and forgot to respond here. This is super weird, especially since other repos using the same template don't seem to be hitting the same issue.

From a preliminary investigation, it looks like `/autocompletepr` is not being passed to the task at all (see the command line log [here](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6020055&view=logs&j=c0636702-cad1-5e4d-7b5b-f15c1cce530a&t=ef3c2779-04f6-5216-b20f-460f31132ece&l=9)). The task then defaults to autocomplete true. `/createpr` is being passed, however.

Taking a stab in the dark, I think the issue is with the [`LocPRCreationEnabled` variable](https://devdiv.visualstudio.com/DevDiv/_git/VSUnitTesting?path=/.vsts-ci.yml&version=GBmain&line=8&lineEnd=9&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents). Alternatively, the issue might be with how the template treats the `CreatePr` parameter [here](https://github.com/dotnet/arcade/blob/main/eng/common/templates/job/onelocbuild.yml#L74-L76). My guess is that there's a mismatch between the variable and what the template expects. The variable might be resolving to be blank or maybe it's something like it resolves to capital-T `True` rather than `true` and the YAML cares about case for some reason, but whatever the case it's causing the template to not register that `CreatePr` is `true` while the task interprets whatever the input is as true anyway.

In any case, that's where I'd start investigating.

**Comment by peterwald** [comment] 2022-04-15 18:25
Created a fix for this. It turns out that the parameters that are unset are interpreted as true, which breaks the logic here.

**Comment by jonfortescue** [comment] 2022-04-19 17:32
@peterwald Closing this as the fix has merged; please reopen if the issue occurs again!

**Closed by jonfortescue** 2022-04-19 17:32 UTC
