### ISSUE TITLE
Projects using arcade should have StrongNameKeyId set to Open by default

### ISSUE THREAD

**Issue by eerhardt** [dotnet/arcade#2834] opened 2019-05-20 21:37 UTC
By default, all projects using arcade will get strong named using the "MicrosoftShared" key:

https://github.com/dotnet/arcade/blob/4a43fdd015308fd283e4c380fdc201e433fd0088/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L6

But the `Open` key is the correct key for most projects:

https://github.com/dotnet/arcade/blob/cdd5d318667c5af1740d69c8a7755e23e7964aeb/src/Microsoft.DotNet.Arcade.Sdk/tools/StrongName.targets#L55-L59

Instead of having all new projects using the wrong key by default, we should be defaulting to the `Open` key, which is correct for the most projects.

**Comment by markwilkie** [comment] 2019-05-20 22:45
Thoughts @JohnTortugo ?

**Comment by JohnTortugo** [comment] 2019-05-23 18:54
> Instead of having all new projects using the wrong key by default

@eerhardt - why is it the wrong key? Wouldn't it just have a 'stronger' signature?

**Comment by eerhardt** [comment] 2019-05-23 19:18
New projects using arcade, like https://github.com/dotnet/spark, https://github.com/dotnet/machinelearning, etc. shouldn't be using the `MicrosoftShared` key for strong naming. Actually, I imagine pretty much all new libraries should not be using the `MicrosoftShared` key, since only very specific projects (for example, projects that existed before we went OSS) should be using that key.

cc @ericstj @safern

**Comment by tmat** [comment] 2019-05-23 19:37
I agree with using `Open` as a default would be better. The problem is that we need to update all repos on Arcade SDK that use the current default first.

**Comment by markwilkie** [comment] 2019-06-05 20:50
yea, basically we want to avoid breaking changes wherever possible until (or unless) we ever rev the major version for Arcade which is not yet on the horizon.

Given this - I'm closing the issue.  However, @eerhardt , if you (of course) can and should reopen and push harder if you see the business need.

**Closed by markwilkie** 2019-06-05 20:50 UTC
