### ISSUE TITLE
runtime SingleFile leg failing on 6.0 CI jobs

### ISSUE THREAD

**Issue by mangod9** [dotnet/arcade#8740] opened 2022-04-01 19:31 UTC
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1694932

### Build leg reported

Build windows x64 Release SingleFile / Send to Helix

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "Helix API does not contain an entry for Windows.10.Amd64.Server19H1.ES.Open"
 }
 ```

**Comment by ilyas1974** [comment] 2022-04-01 20:43
@mangod9, this is "by design". The queue was deprecated as part of our rollout this week. It has been replaced with Windows.10.Amd64.Server2022.ES.Open. Please update your pipelines to use this new queue. We would be happy to help you do this if you need assistance.

**Comment by mangod9** [comment] 2022-04-01 21:05
ok thanks. @dotnet/runtime-infrastructure as fyi since this is failing 6.0 CI jobs.

**Comment by adiaaida** [comment] 2022-04-01 21:11
I am going to close this issues since it is a configuration issue on the runtime side.

**Closed by adiaaida** 2022-04-01 21:11 UTC
Labels: First Responder, Detected By - Customer, Known Build Error
