### ISSUE TITLE
Github translation for Publish to BAR for an internal repo should not translate the repo name

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7485] opened 2021-06-08 21:51 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

For internal repo 

Eg: 'https://dev.azure.com/dnceng/internal/_git/dotnet-winforms' should not translate to https://github.com/dotnet/winforms when publishing to BAR. 

It should just use internal repo url instead.

**Comment by riarenas** [comment] 2021-06-08 21:57
I don't think this is quite the issue. The problem that winforms was facing was:

* They were testing a change in an experimental branch only available in azure devops
* They created a default channel using the dnceng mirror URL + the branch
* During the publish to BAR task, the build said that it found a default channel for the branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=1175693&view=logs&j=5e0a0dfe-35c2-59f5-5b14-dd1b2ef09f9b&t=0c16de11-9263-5b3f-6fcc-cebb3b8ee869&l=64
* darc add-build-to-channel then said that the build was in all the configured channels (It didn't find the default channel mentioned above) https://dev.azure.com/dnceng/internal/_build/results?buildId=1175693&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073&l=32

This issue is not about stopping the translation but instead about being consistent and having proper guidance. 

* If I want to test this scenario, how should I create my default channel? which URL should I use?
* If the publish to BAR task says that a default channel was found, this should be consistent with what add-build-to-channel ends up doing.

**Comment by adiaaida** [comment] 2021-06-17 14:20
@epananth where is this? Should we put it back in the backlog?

**Comment by epananth** [comment] 2021-06-17 22:01
I did not find time to create this PR. I am going to put this back :(

**Comment by ChadNedzlek** [comment] 2021-07-19 22:42
I'm not sure what the ask is here for this one.  It sounds like it's just guidance of "this scenario isn't designed to work"? @riarenas

**Comment by riarenas** [comment] 2021-07-19 22:48
Yeah, the issue is not very clear in what it asks for, and the build is already gone, so I can't check if my summary is correct at the top.  

I don't think it's correct to not translate.

**Comment by riarenas** [comment] 2021-07-19 22:52
Ugh, ended up hitting the wrong key and it closed the issue with half finished thoughts. 

I think this is a somewhat unsupported scenario, but it also seems like there's a bug in the publish build assets job, where we say that we found a default channel that should trigger the publishing, but at the same time we don't actually publish so users end up confused. Since I'm in FR this week I'll take a quick stab at reproing this tomorrow morning, and if I can't get us more concrete data I'll close.

**Comment by ilyas1974** [comment] 2021-07-20 16:54
Putting this issue in breakdown and assigning to @riarenas to gather some more data for this issue.

**Comment by riarenas** [comment] 2021-07-21 14:48
The issue is too vague and we lost the builds that had the logs. I'm not able to reproduce this behavior.

**Closed by riarenas** 2021-07-21 14:48 UTC
Labels: Detected By - Ad-Hoc Testing, First Responder
