### ISSUE TITLE
AzCopy missing when building windows.vs2022.amd64.open

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9358] opened 2022-05-13 15:33 UTC
@andriipatsula encountered an issue in his PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22848

`windows.vs2022.amd64.open` image build fails on validation because it can't find instaleld AzCopy. When looking into the log we see that the installation script for `windows-azcopy` was not run at all. It is defined between `windows-powershell` and `windows-cmake` artifacts but we don't see it in the log. Surprisingly in one of the runs I dont' even see `windows-cmake` being executed.

This seems like some issue on ImageFactory side because I don't see how this artifact is any different that other ones. We also lack information to investigate it.

Looking at [this build](https://dev.azure.com/dnceng/internal/_build/results?buildId=1769683&view=logs&j=9f602f64-2450-51a0-e2eb-2e7e093ff59e&t=60c6cf17-2b11-597e-4355-2adb9530f56e):

[Attempt 1](https://imagefactoryv2prod.blob.core.windows.net/logfiles/ohxfybwv?sv=2020-08-04&se=2022-05-20T13%3A19%3A04Z&sr=b&sp=r&sig=8ChQcDb5xsniN4sajYKtV9VyoB8HnbsvpoGfWvLERFk%3D) - `windows-azcopy` should be installed between `windows-powershell` and `windows-cmake` but it's completely missing from log.

```
2022-05-13T13:37:20Z:     azure-arm: WARNING: -----------------------Starting Artifact windows-powershell-----------------------
2022-05-13T13:37:39Z: ==> azure-arm: Setting a 9h30m0s timeout for the next provisioner...
2022-05-13T13:37:39Z: ==> azure-arm: Provisioning with Powershell...
2022-05-13T13:37:39Z: ==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner1086724686
2022-05-13T13:37:57Z: ==> azure-arm: Setting a 9h30m0s timeout for the next provisioner...
2022-05-13T13:37:57Z: ==> azure-arm: Provisioning with Powershell...
2022-05-13T13:37:57Z: ==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner3519376152
2022-05-13T13:38:02Z:     azure-arm: WARNING: -----------------------Starting Artifact windows-cmake-----------------------
2022-05-13T13:38:02Z:     azure-arm: Installing CMake
2022-05-13T13:38:03Z:     azure-arm:
```

[Attempt 2](https://imagefactoryv2prod.blob.core.windows.net/logfiles/pfcqtoat?sv=2020-08-04&se=2022-05-20T13%3A21%3A45Z&sr=b&sp=r&sig=dKin8sSxw%2FfdGJTvDHrisalRjZFFxN0DEb2sfWDJqJ8%3D) and [Attempt 4](https://imagefactoryv2prod.blob.core.windows.net/logfiles/uqhgljkf?sv=2020-08-04&se=2022-05-20T14%3A04%3A15Z&sr=b&sp=r&sig=CJ8oqHPuxldpNnGL%2FulKXz%2BboNPzKyQofcYjZZOrICo%3D) - `windows-azcopy` missing plus some error about `packer-cleanup` script

```
2022-05-13T14:18:26Z:     azure-arm: WARNING: -----------------------Starting Artifact windows-powershell-----------------------
2022-05-13T14:18:41Z: ==> azure-arm: Setting a 9h30m0s timeout for the next provisioner...
2022-05-13T14:18:41Z: ==> azure-arm: Provisioning with Powershell...
2022-05-13T14:18:41Z: ==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner3937857803
2022-05-13T14:18:50Z: ==> azure-arm: & : The term 'c:/Windows/Temp/packer-cleanup-627e6561-ab6a-93f7-f18c-6e7fcbe77183.ps1' is not recognized as the name
2022-05-13T14:18:50Z: ==> azure-arm: of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
2022-05-13T14:18:50Z: ==> azure-arm: verify that the path is correct and try again.
2022-05-13T14:18:50Z: ==> azure-arm: At line:1 char:216
2022-05-13T14:18:50Z: ==> azure-arm: + ... a646b.ps1; &'c:/Windows/Temp/packer-cleanup-627e6561-ab6a-93f7-f18c-6 ...
2022-05-13T14:18:50Z: ==> azure-arm: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-05-13T14:18:50Z: ==> azure-arm:     + CategoryInfo          : ObjectNotFound: (c:/Windows/Temp...e7fcbe77183.ps1:String) [], CommandNotFoundException
2022-05-13T14:18:50Z: ==> azure-arm:     + FullyQualifiedErrorId : CommandNotFoundException
2022-05-13T14:18:50Z: ==> azure-arm:
2022-05-13T14:18:50Z: ==> azure-arm: Setting a 9h30m0s timeout for the next provisioner...
2022-05-13T14:18:50Z: ==> azure-arm: Provisioning with Powershell...
2022-05-13T14:18:50Z: ==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner2307976452
2022-05-13T14:18:55Z:     azure-arm: WARNING: -----------------------Starting Artifact windows-cmake-----------------------
2022-05-13T14:18:55Z:     azure-arm: Installing CMake
```

[Attempt 3](https://imagefactoryv2prod.blob.core.windows.net/logfiles/jgiihkdc?sv=2020-08-04&se=2022-05-20T14%3A03%3A45Z&sr=b&sp=r&sig=PPKmSNcXyHXlA0EQ6ePVtuYPK36eqLsq%2Bc5nekG%2BbMo%3D) - slightly different error. Neither `windows-azcopy` nor `windows-cmake` were installed

```
2022-05-13T14:17:59Z:     azure-arm: WARNING: -----------------------Starting Artifact windows-powershell-----------------------
2022-05-13T14:18:19Z: ==> azure-arm: & : The term 'c:/Windows/Temp/packer-cleanup-627e6544-4010-c9a1-69bd-65dda31306b7.ps1' is not recognized as the name
2022-05-13T14:18:19Z: ==> azure-arm: of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
2022-05-13T14:18:19Z: ==> azure-arm: verify that the path is correct and try again.
2022-05-13T14:18:19Z: ==> azure-arm: At line:1 char:216
2022-05-13T14:18:19Z: ==> azure-arm: + ... 78210.ps1; &'c:/Windows/Temp/packer-cleanup-627e6544-4010-c9a1-69bd-6 ...
2022-05-13T14:18:19Z: ==> azure-arm: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-05-13T14:18:19Z: ==> azure-arm:     + CategoryInfo          : ObjectNotFound: (c:/Windows/Temp...5dda31306b7.ps1:String) [], CommandNotFoundException
2022-05-13T14:18:19Z: ==> azure-arm:     + FullyQualifiedErrorId : CommandNotFoundException
2022-05-13T14:18:19Z: ==> azure-arm:
2022-05-13T14:18:19Z: ==> azure-arm: Setting a 9h30m0s timeout for the next provisioner...
2022-05-13T14:18:19Z: ==> azure-arm: Provisioning with Powershell...
2022-05-13T14:18:19Z: ==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner3962144229
2022-05-13T14:18:23Z:     azure-arm: Windows PowerShell
2022-05-13T14:18:23Z: ==> azure-arm: The argument 'C:/Windows/Temp/packer-elevated-shell-627e68ad-3f6f-93d6-ce6a-e1d05b83de54.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
2022-05-13T14:18:23Z:     azure-arm: Copyright (C) Microsoft Corporation. All rights reserved.
2022-05-13T14:18:23Z:     azure-arm:
2022-05-13T14:18:23Z:     azure-arm: Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
```

**Comment by MattGal** [comment] 2022-05-13 15:51
@ChulHul  FYI.

**Comment by MattGal** [comment] 2022-05-17 17:33
@ChulHul has rolled out major changes to Image Factory that no longer use Packer, and this does not seem to have reproduced since.  I'll be testing all the images indirectly as soon as https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/22969 merges, so we'll have tons of chances to hit the bug then.  

Due to the major IF changes and lack of repros I'm going to (optimistically) close this; I'll be on point to reactivate / file new issues if things are still having trouble after.

**Closed by MattGal** 2022-05-17 17:33 UTC
Labels: First Responder, Helix-Machines
