### ISSUE TITLE
Nuget errors after SDK update in ASPNETCore Tooling

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6435] opened 2020-10-22 20:20 UTC
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

ASPNETCore Tooling took in an updated Arcade in this PR: https://github.com/dotnet/aspnetcore-tooling/pull/2658/files
That same PR indicates an SDK update, as well (RC1 to RC2). 

They are now seeing errors with Nuget packages: 
```
error NU3008: Package 'Microsoft.NET.Sdk.Razor 6.0.0-alpha.1.20521.5' from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json': The package integrity check failed.
```

Discussion on Teams: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1603348854955?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1603348854955&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1603348854955

Link to build: https://dev.azure.com/dnceng/public/_build/results?buildId=862104&view=results

**Comment by dougbu** [comment] 2020-10-22 21:31
The most recent Arcade update in dotnet/aspnetcore-tooling#2658 only hit known and likely unrelated CS1029 errors. It's certainly possible those relate to the .NET SDK update but the fix is relatively straightforward (hint, hint @JunTaoLuo 😺) and within the dotnet/aspnetcore-tooling repo. See https://dev.azure.com/dnceng/public/_build/results?buildId=861677

The more interesting differences may be between the 20201021.3 and 20201021.5 builds of dotnet/aspnetcore. We had two builds succeed with the 20201021.3 package versions but then two show the NU3008 failure with 20201021.5 and 20201022.3 dependencies. Of course, I'm not positive 😺

**Comment by dougbu** [comment] 2020-10-22 22:27
If I'm on the right track, the differences between the dotnet/aspnetcore state at 20201021.3 and 20201021.5 are https://github.com/dotnet/aspnetcore/compare/6a82a84b10a8073f262ea53d7f8e01fa6cbfca08...8f508e70842e67839cdedbd8208aba46ebf55f32 That includes a dependency PR that updated Arcade bits from 5.0.0-beta.20506.7 to 6.0.0-beta.20520.8, bringing us back to looking hard at Arcade.

**Comment by dougbu** [comment] 2020-10-22 22:55
BTW the NU3008 error also shows up in dotnet/sdk#14268 as @dsplaisted reported (https://github.com/dotnet/sdk/pull/14268#issuecomment-714710429). I'm about to look at the history of that PR to see which dotnet/aspnetcore build introduced that specific issue&hellip;

**Comment by dougbu** [comment] 2020-10-23 00:14
The dotnet/sdk#14268 PR built just once without the NU3008 errors. That error (two test failures) looks unrelated to this issue. So, again the dotnet/aspnetcore build 20201021.3 seems fine but builds 20201021.5 and later from that repo aren't providing a Microsoft.NET.Sdk.Razor package that passes the integrity checks.

**Comment by dougbu** [comment] 2020-10-23 00:34
Going elsewhere after one last update: The Arcade-specific differences between those two dotnet/aspnetcore builds are shown in https://github.com/dotnet/arcade/compare/ee39cd1573dbb8011f343e1037af51d4fc00a747..7fbf2a7703498067569d07a21776b91e599028e2 or (just the commit descriptions) https://github.com/dotnet/arcade/compare/ee39cd1573dbb8011f343e1037af51d4fc00a747...7fbf2a7703498067569d07a21776b91e599028e2. This is a lot of change and it includes lots 'o changes. For example, there's a .NET SDK change (which should impact dotnet/aspnetcore because we use 6.0.100-alpha.1.20472.11 at the moment in master) as well as a Microsoft.DotNet.SignTool version update.

Suspect https://github.com/dotnet/arcade/commit/7fbf2a7703498067569d07a21776b91e599028e2 or perhaps https://github.com/dotnet/arcade/commit/f2f45f7a856fe4949735e574f7a0350bda48264f are likely candidates for causing signing problems.

**Comment by missymessa** [comment] 2020-10-23 00:36
@chcosta @mmitche ^ The commits Doug is referencing are related to the Post Build Signing work.

**Comment by chcosta** [comment] 2020-10-23 03:11
Could be. I'll take a look in the morning

**Comment by chcosta** [comment] 2020-10-23 05:48
It does appear that this is related to the Arcade update.  https://github.com/dotnet/arcade/commit/7fbf2a7703498067569d07a21776b91e599028e2 is the most likely culprit, but it could be any change between 10/6 and 10/20 and I can't get a repro.  Trying to sign locally, it seems to be doing the right things.  I'll dig in more in the morning. :/

**Comment by chcosta** [comment] 2020-10-23 09:29
One of the changes to signtool modified it such that it would not sign packages if they were already signed (and the contents of the package were already signed) . I wonder, what is happening between the "build" step of aspnetcore and the "build installers" step. It appears that aspnetcore is now signing far fewer files in the latter step than it was previously. Seems plausible that this package was getting signed, then modified, then signed again. I haven't looked at the bin logs yet.

**Comment by chcosta** [comment] 2020-10-23 09:38
Side note:we could probably also run the nuget integrity checks in signtool and re-sign the package if they fail. I'd like to get more insight into the aspnetcore build first though and make sure we understand this failure.

**Comment by chcosta** [comment] 2020-10-23 16:27
Not having bin logs for most of the steps in the aspnetcore repo, slows things down a bit.  I need to get builds with binlogs to confirm my theory here and understand what the "Build installers" step is doing.  I've confirmed that this is definitely, the commit previously mentioned.

@dougbu , perhaps you have some insight into what is causing the signing to become invalid?  Can you merge [these steps](https://github.com/dotnet/aspnetcore/blob/master/.azure/pipelines/ci.yml#L191-L220) together such that signing only occurs once, when all assets are available?  SignTool *should* be able to unpack containers and sign all assets in one pass now.  I'd prefer to work on updating Arcade's signtool / signcheck pieces to account for this scenario, but there's a two pronged investigation here and I'd like more insight on aspnetcore.

**Also, what urgency does this issue require?**  I'm giving it my full attention, but it's not clear to me whether we need to take drastic measures here.

**Comment by missymessa** [comment] 2020-10-23 17:49
Going to move this into the Post-Build Signing epic.

**Comment by dougbu** [comment] 2020-10-23 18:15
1. I do not know what is causing the signing to become invalid
    - All we know is that the problems point very strongly at a problem in the Arcade infrastructure
2. We cannot merge steps because of how WiX handles signing as well as the need to use desktop `msbuild` when we run Wix.
    - We run the majority of our build using `dotnet msbuild`
    - @mmitche looked at this recently and didn't restructure our CI build
3. What does moving this into an epic mean w.r.t. to our broken artifacts❔
    - We're not producing valid packages as it stands

**Comment by JunTaoLuo** [comment] 2020-10-23 18:16
>Also, what urgency does this issue require?

This should be prioritized given that sdk and aspnetcore-tooling currently cannot ingest builds from aspnetcore.

**Comment by dougbu** [comment] 2020-10-23 18:19
@JunTaoLuo or @Tratcher unless can we get a fixed Arcade version or a suggestion to work around the issue in dotnet/aspnetcore _today_, I strongly suggest we got back to the previous Arcade versions.

**Comment by chcosta** [comment] 2020-10-23 19:22
> All we know is that the problems point very strongly at a problem in the Arcade infrastructure

This could be argued either way, but it's not really relevant.  Yes, as I mentioned above, Arcade changes have surfaced an issue (longstanding) in the aspnetcore repo which is related to signing a package multiple times, and I'm working to resolve it.

> We cannot merge steps because of how WiX handles signing as well as the need to use desktop msbuild when we run Wix.

Not sure I follow, you are running desktop msbuild in the "build installers" step already

> What does moving this into an epic mean w.r.t. to our broken artifacts?

Nothing, it's just a tracking thing.  This is still getting top priority.

> unless can we get a fixed Arcade version or a suggestion to work around the issue in dotnet/aspnetcore today, I strongly suggest we got back to the previous Arcade versions.

Sure.  Please feel free to mitigate the problem however you feel necessary.  aspnetcore builds aren't quick to turn around, so validation, getting binlogs, running builds, etc... is making this a slow process.  I expect to have a change from the Arcade side today, but I'm not sure when that will get promoted.  You can either revert to the previous version of Arcade, or I have a private version which has all of the Arcade changes except for the signtool change at question.  If you need help reverting the change, you'll probably need to work with First Responders to make that happen.

I think it would be fantastic if someone could help me understand the aspnetcore build better and track down what is happening to invalidate the package in aspnetcore, but barring that, I will continue to work on this from the Arcade side and try to understand the repo side better when I get cycles.

Thanks for doing the initial leg work to narrow down the scope of this problem Doug!

**Comment by chcosta** [comment] 2020-10-23 23:13
I have a fix for this, https://github.com/dotnet/arcade/pull/6448.  I'm still working on validating aspnetcore official builds.  

Just to set expectations:  Given the time of day / week, I don't expect that validation will complete until Monday and the PR will likely not merge before then either.  So, this will not be promoted and flow to aspnetcore until mid / late next week (assuming nothing waylays the Arcade builds).  I'll comment back here after I've fully validated this change w.r.t. aspnetcore.

**Closed** 2020-10-26 21:16 UTC

**Comment by dougbu** [comment] 2020-10-27 17:01
@chcosta was your fix included in the most recent Arcade update❔ I noticed that included one of those recursive version updates and the previous promotion was huge&hellip;

**Comment by chcosta** [comment] 2020-10-27 17:05
Doesn't look like it was included.  Looks like the Arcade update included everything through 10/25, my change went in 10/26.

FYI @missymessa

**Comment by dougbu** [comment] 2020-10-27 17:31
@chcosta thanks for saving me from an incorrect Arcade update in dotnet/aspnetcore😺 I'll keep an 👁️ out for a promotion that includes f56644c6b0fe.

Will the right promotion need an Arcade dependency update too❔

**Comment by chcosta** [comment] 2020-10-27 20:28
@dougbu You should be able to update your dependencies and get the new version of Arcade with the fix now.  Otherwise, I think your repo will update its dependencies tomorrow morning.
