### ISSUE TITLE
Microsoft.DotNet.Arcade.SDK does not import publish targets

### ISSUE THREAD

**Issue by sbomer** [dotnet/arcade#1171] opened 2018-10-25 21:33 UTC
Using `<Project Sdk="Microsoft.DotNet.Arcade.Sdk">` does not import any of the targets related to publish.

I'd like to be able to use the logic mentioned in https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Publishing.md, both:
- the "Publish" target from https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L33, and
- the related tasks that it imports from https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/build/Microsoft.DotNet.Build.Tasks.Feed.targets

The eng scripts call publish by running msbuild on build.proj, which calls msbuild on publish.proj. However, for projects that use the "Project Sdk" syntax, it doesn't get imported. There also aren't any convenient properties defined that would make manually importing the target files easy (I would have to write logic to detect the arcade toolset installation directory).

This is especially important for helping arcade onboarding, as it will make it easier to write part of our build logic (the publishing logic) against arcade before the whole repo has moved to using the eng/* scripts.

**Comment by markwilkie** [comment] 2018-10-25 22:01
It seems reasonable at least to me that we'd import publish as it's a required package.  Thoughts @jcagme @tmat ?

**Comment by tmat** [comment] 2018-10-25 22:50
This is working as designed. Artifact publishing is only performed during CI build, not in inner-loop build.

Why would you need artifact publishing in your project? 

Note that `Publish` target from `Publish.proj` is different from .NET Core SDK `Publish` target, which is used to output all binaries to output directory that are necessary to run an app.

**Comment by sbomer** [comment] 2018-10-25 23:47
> Why would you need artifact publishing in your project?

I'm working on migrating the coreclr official builds to azure pipelines, and would like to reuse arcade targets to upload artifacts to blob storage, etc..

**Comment by tmat** [comment] 2018-10-25 23:53
@markwilkie @weshaggard  We will want to move coreclr repo to Arcade SDK as well, correct? 
If so then I'd recommend starting there and then move the CI/official build to Azure, instead of the other way around.

**Comment by sbomer** [comment] 2018-10-26 00:00
> We will want to move coreclr repo to Arcade SDK as well, correct?

We're trying to do both in parallel. /cc @RussKeldorph 

In any case, I think the arcade SDK should make it possible for me to start from an empty project using the "Microsoft.DotNet.Arcade.Sdk", and call the tasks documented in https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Publishing.md.

We're doing the same thing for helix publishing, and that works correctly because the Sdk.props/targets import chaing includes the helix targets. It would be great if I could do the same with publish.

**Comment by tmat** [comment] 2018-10-26 00:04
> In any case, I think the arcade SDK should make it possible for me to start from an empty project using the "Microsoft.DotNet.Arcade.Sdk", and call the tasks 

No it should not. That's not the intended way of using this stuff.

If you want some temporary workaround then you can copy `Publish.proj` to the repo and remove it later when the repo switches to Arcade SDK.

**Comment by tmat** [comment] 2018-10-26 00:15
You can also reference the package that implements the publishing task directly:

```xml
<PackageReference Include="Microsoft.DotNet.Build.Tasks.Feed" Version="..." />
```

and then use the task directly like so:
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L71-L80

**Comment by markwilkie** [comment] 2018-10-26 15:36
@sbomer - thanks for working on this.  Do you have a sense for when the migration plan for CoreCLR will be ready?  (what gets done by when for moving to Arcade and AzDO)  I'd like to start with what you guys (repo experts) think and then go from there.

**Comment by sbomer** [comment] 2018-10-26 18:11
@markwilkie, I don't have a timeline for the end-to-end plan, but onboarding official builds to Azure DevOps is well on its way. We have most of the OS legs building and submitting tests to helix, and am still working on publishing. I think we'll be 80% of the way to having official builds on AzDO by end of next week.
@RussKeldorph @hoyosjs may have more info about the rest of the plan - we can discuss this at our next sync with @chcosta on Monday if you like.

For publishing:
I was able to work around this in a `<Project Sdk="Microsoft.DotNet.Arcade.Sdk">` project by duplicating some of the logic that Arcade currently has in `Tools.proj` and `Build.proj` to restore Microsoft.DotNet.Build.Tasks.Feed:
- Adding the PackageReference @tmat mentioned, with the version `$(MicrosoftDotNetBuildTasksFeedVersion)` imported from arcade props
- Setting a `TargetFramework` to make nuget happy
- Setting `RestoreSources` to include the same feeds defined in Tools.proj
- Performing an `msbuild /t:Restore` on the project, with `NUGET_PACKAGES` set to `.packages` in the repo root
- Creating another project that imports the targets from the restored package. Now I can call the `PublishFilesToBlobFeed` target.

Compare this with the [experience for helix](https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.Helix/Sdk), which requires adding the helix SDK to global.json, and creating a project with `<Project Sdk="Microsoft.DotNet.Helix.Sdk">`.

> That's not the intended way of using this stuff.

I understand that Arcade doesn't currently support this, and instead requires going through the build scripts and Build.proj. IMHO as a consumer, it would make sense to write a simple project against the Arcade SDK and use it to perform only one step of the pipeline, instead of requiring everything to go through the Build.proj entry point. This is relevant for us because we aren't completely onboarded onto Arcade (and likely will always have some custom build logic in separate steps, outside of Arcade). I believe this is a reasonable expectation since other MSBuild SDKs work similarly.

It seems like this could be accomplished by importing some of the aforementioned logic from the Arcade Sdk.props/targets, instead of only from Build.proj. This would let consumers of Arcade control the MSBuild entry point, providing a little more flexibility while still making the Arcade logic convenient to use.

**Comment by tmat** [comment] 2018-10-30 01:29
> I understand that Arcade doesn't currently support this, and instead requires going through the build scripts and Build.proj. 

No, it does not require going thru build scripts. As I pointed you can use `PushToBlobFeed` task directly by referencing `Microsoft.DotNet.Build.Tasks.Feed`.

>  This is relevant for us because we aren't completely onboarded onto Arcade (and likely will always have some custom build logic in separate steps, outside of Arcade)

The pipeline has extensibility points that should allow you to insert other build steps that you might need. Arcade build pipeline is designed to drive the build process. It's not designed to be consumed by another build project that drives the build. We can indeed add more extensibility points if it turns out to be necessary.

**Comment by chcosta** [comment] 2018-10-30 04:02
@sbomer, let's try to find time to look at this together tomorrow. Referencing the feed package should be sufficient but perhaps we're missing something about your scenario.

**Comment by jcagme** [comment] 2019-02-08 18:57
@sbomer did referencing the package work for you or you needed some other sort of workaround?

**Comment by sbomer** [comment] 2019-02-08 19:23
@jcagme, We ended up with something similar to the workarounds described above in https://github.com/dotnet/arcade/issues/1171#issuecomment-433496724. At the moment we have an empty project to enable us to just restore the blob feed publish tasks in https://github.com/dotnet/coreclr/blob/dfde393b46f555a78b847ea45cf534e120c8e35e/eng/build-job.yml#L146. My comment is a decent summary of the usability issues I see with the publish targets. Generally our repo has a lot of build logic for building native components that seem like they're outside the scope of arcade - that's why we're using arcade somewhat selectively.

**Comment by JohnTortugo** [comment] 2019-11-05 01:22
Much have changed in the publishing infra in the last year.. does anyone disagree on closing this issue?

**Comment by sbomer** [comment] 2019-11-05 17:04
We have a workaround that does the job, so feel free to close this as by design. Thanks!

**Closed** 2019-11-07 21:36 UTC
