### ISSUE TITLE
.NET 8: Unified Build Infrastructure

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#10100] opened 2022-07-20 17:57 UTC
This epic covers Unified Build Infrastructure to be completed in the .NET 8 timeframe.

**Comment by mmitche** [comment] 2022-08-25 18:41
https://github.com/dotnet/arcade/issues/10588

**Comment by tkapin** [comment] 2022-10-10 16:07
This was intended to be a container epic, we agreed to close this one.

**Closed by tkapin** 2022-10-10 16:07 UTC
Labels: Epic, area-unified-build, area-product-construction
