### ISSUE TITLE
MacOS x64 timeout

### ISSUE THREAD

**Issue by agocke** [dotnet/arcade#9265] opened 2022-05-05 20:17 UTC
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1753328

### Build leg reported

Installer Build and Test coreclr  OSX_x64 Release

### Pull Request

https://github.com/dotnet/runtime/pull/68886

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "ran longer than the maximum time of 120 minutes"
 }
 ```

### Additional information about the issue reported

This is known (queues have low numbers of machines) -- just adding to tracking.

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|1755926|dotnet/runtime|CoreCLR  Product Build OSX x64 release|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1755926/logs/2366
|1754775|dotnet/aspnetcore|Tests: Helix|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1754775/logs/83
|1755923|dotnet/aspnetcore|Tests: Helix|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1755923/logs/79
#### Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|2|3|3|

**Comment by MattGal** [comment] 2022-05-06 17:31
There's three different things going on here.  Initial notes:

#### 1755926 

This is a build that ended up on a very slow MacOS VM.  We've hit issues like this in the past and this is a known (albeit rare) issue with Hosted MacOS Machines.  I've opened [an IcM](https://portal.microsofticm.com/imp/v3/incidents/details/306211701/home) on them to investigate this, but GitHub will evidently not be online until next week.  Regardless, it's a fairly rare issue, at least lately, and there's nothing we can do about this one.


#### 1754775

This one looks like our SQL processor had a bad time.  From this Kusto query, the two "timed out" Jobs' last work items finished by 2022-05-05 20:33:01.9610000 UTC, but the polling Helix SDK didn't finish because the jobs never finished. This is definitely on us, and is very interesting, I'll dig deeper and share any findings.

```
WorkItems
| where JobName in ('9fffd425-9cee-4ca7-b52f-a98be20d1627', 'f52d199e-5e83-47c7-a586-67a7a4ae899d')
| extend waited = Started-Queued
| extend runtime = Finished-Started
| order by Finished desc 
```

#### 1755923

This one was in good shape and finished as expected, but we hit an error with payload 'dotnet-sdk-7.0.100-preview.5.22228.6-osx-x64.tar.gz'

```
dotnet-sdk-7.0.100-preview.5.22228.6-osx-x64.tar.gz.partial
2022-05-06T09:24:18.487Z	ERROR  	executor(324)	_download_and_unpack	Exception "Compressed file ended before the end-of-stream marker was reached" seen downloading: 
Traceback (most recent call last):
  File "/private/etc/helix/scripts/helix/executor.py", line 296, in _download_and_unpack
    self._unpack(partial_file_path, contents_root, is_workitem_payload)
  File "/private/etc/helix/scripts/helix/executor.py", line 377, in _unpack
    unzipped_file_paths = self._get_unpacked_file_paths(file_path, contents_root)
  File "/private/etc/helix/scripts/helix/executor.py", line 606, in _get_unpacked_file_paths
    for file_name in tar.getmembers():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 1763, in getmembers
    self._load()        # all members, we first have to
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 2350, in _load
    tarinfo = self.next()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 2281, in next
    self.fileobj.seek(self.offset - 1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 368, in seek
    return self._buffer.seek(offset, whence)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```
... this put the work item back into the queue during an evidently relatively busy time, and by the 2nd attempt rolled around it had timed out.  Unless this reproduces consistently I'd just say this was a blip in the download of the correlation payload, since all other work items in this time had to use the same file and  passed.

**Comment by MattGal** [comment] 2022-05-06 18:10
For 1754775, these are missing WorkItemQueued events, which is really funky because these come from the helix-service's controller itself and don't even run on the client.  My understanding is @ChadNedzlek is looking at the matter of missing EventHub events.  
[App Insights query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA83QzQrCMAwA4PueInjSQ0fb%252Fdnpdhd8B8nWTAtuk7Yqig9v9aAe9G4IBBI%252BSLInD%252BNhpR1UEHmLLbnoBucdWQJvenIe%252BwPUFWj09GhMJZeS8SwkSF4KUWZprOY5DzGDL3b50yZJyUWscvG0Lxqgwy1BOw4ezeBgorqu06nMmGqJWNpiwZpMdgzVvCHJtchlMQneHfserbkSNJdwFVn0Zhw2K734k9M%252BdwIzwPT5%252Bvfc0Yms8Zd1qHuoQdwBgcah3Z8BAAA%253D)

```
Unhandled exception System.InvalidOperationException: No WorkItemQueued event for item at Microsoft.Internal.Helix.DataMigration.DataMigrationMessageHandler.GetTimes(IEnumerable`1 events) in S:\src\ServiceFabric\Helix\DataMigration\DataMigrationMessageHandler.cs:line 743 at Microsoft.Internal.Helix.DataMigration.DataMigrationMessageHandler.HandleWorkItemFinished(WorkItemFinishedNotification notification, CancellationToken cancellationToken) in S:\src\ServiceFabric\Helix\DataMigration\DataMigrationMessageHandler.cs
```

So, I can confirm all three of these timeouts are distinct infrastructure issues you need not concern yourself with, but I will keep this open until @ChadNedzlek  confirms that we have an issue tracking the dropped events because that is very, very concerning.

**Comment by MattGal** [comment] 2022-05-06 18:28
I opened https://github.com/dotnet/arcade/issues/9275 to deal with the sporadic issue seen in 1754775, this is not a new thing but definitely something we need to pursue with partner teams (in this case the Event Hub / Service Bus folks).   As all three issues are investigated, I'm going to close this one in favor of the IcM and issue opened as that more accurately tracks the problems.

**Closed by MattGal** 2022-05-06 18:28 UTC
Labels: First Responder, Detected By - Customer, Known Build Error
