### ISSUE TITLE
VMR synchronization does not apply new repo patch.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#11976] opened 2022-12-15 20:00 UTC
In [77d32a23f40688092e2b467f43b63692901f2391](https://github.com/dotnet/installer/pull/15105/commits/77d32a23f40688092e2b467f43b63692901f2391), I am adding a new patch to a repo but that repo's commit sha is not changing.  When I run vmr-sync.sh, the patch is not being applied to the vmr.

Appling patches to repos that do not have a corresponding sha change is a common source-build operation.

cc @premun

**Comment by premun** [comment] 2022-12-16 09:34
All patches affected by the current change are reverted and re-applied back (or one of those when they're being added/removed).

In the logs, I can see:
> info: Detected a change of a VMR patch /mnt/vss/_work/1/vmr/src/installer/src/SourceBuild/tarball/patches/razor/0001-Disable-source-build-by-default-and-opt-in-instead-8.patch for razor

I will investigate whether maybe not all files are staged or something

**Comment by premun** [comment] 2022-12-16 09:51
@MichaelSimons I can see everything being fine:

> info: Re-applying 1 VMR patch...
info: Applying patch D:\github\dotnet\src\installer\src\SourceBuild\tarball\patches\razor\0001-Disable-source-build-by-default-and-opt-in-instead-8.patch to src/razor...
dbug: Executing command: 'git -C D:\github\dotnet apply --cached --ignore-space-change --directory src/razor D:\github\dotnet\src\installer\src\SourceBuild\tarball\patches\razor\0001-Disable-source-build-by-default-and-opt-in-instead-8.patch'

Then:

```
$ cat src/razor/Directory.Build.props
   ...
   <ExcludeFromSourceBuild>true</ExcludeFromSourceBuild>`
   ...
```

**Comment by premun** [comment] 2022-12-20 14:12
We were able to reproduce this with the following setup:
- `dotnet/installer` at `ee24e314ddbf6c83e337725fbe7248a54ee57a49`
- `dotnet/dotnet` at `76fe18e7ea1ca435f02ecfd5b5ae82917d0c8d38`

**Comment by dkurepa** [comment] 2022-12-22 15:17
I couldn't use Michaels original commits, so I tried recreating his PR from the same parent commit as he did, with the same content. I had an issue with applying the patch (git was complaining it was corrupted, but the VMR was trying to apply it.
I also tried creating my own test patch with the same conditions Michael described (added a patch for a repo, without changing the patched repo's sha) and it successfully got applied

**Comment by premun** [comment] 2022-12-22 15:19
When it got successfully applied, were the patches present and checked into the VMR (ie example above with `Directory.Build.props`)?

**Comment by premun** [comment] 2022-12-23 11:08
Since we can't repro this, I believe it might have been caused by this other thing that was in play and that was the commit that happened in the VMR that was moving the git-info files. At one point, we've had two sets of those files in the VMR and we had two versions of the tooling that was reading these from or the other place so I assume that there was a mismatch between which versions of the repo the tooling thought is in the VMR. If this comes back, we can revisit this but we already have E2E tests for this case now.

**Closed by premun** 2022-12-23 11:08 UTC
