### ISSUE TITLE
dotnet install script returns  Preview 2 version on -Channel 7.0 -Version latest as

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/arcade#9264] opened 2022-05-05 18:39 UTC
Hi,

It looks like aka ms links are outdated for dotnet 7.0 sdk version. Please refer the issue for getting more details [https://github.com/dotnet/install-scripts/issues/273](https://github.com/dotnet/install-scripts/issues/273)

Could you take a look if the corresponded pipeline was run after generating [7.0 preview 3 packages](https://dev.azure.com/dnceng/internal/_build/results?buildId=1688024&view=artifacts&pathAsName=false&type=publishedArtifacts)?
This package is mention on the official website: https://dotnet.microsoft.com/en-us/download/dotnet/7.0

Thank you!

**Comment by riarenas** [comment] 2022-05-09 14:40
Added to FR for investigation

**Comment by MattGal** [comment] 2022-05-10 00:27
I believe this is just what happens when the install scripts fail to resolve a good aka.ms link and "fall back".  I would expect that to get preview 3 I'd do something like:

``` ps1
dotnet-install.ps1 -Channel 7.0-preview3 -Quality signed -Version latest
```
... and this does indeed work, but I'll spend some more time figuring it out in the morning.

**Comment by MattGal** [comment] 2022-05-10 21:04
To summarize: 
- Install script "Quality" defaults to "GA", and finds p2 because of a fallback mechanism in the scripts.
- 7 hasn't GA'd and really shouldn't work at all for this quality.
- If you pass 'preview', it finds p4 as expected

This is either an issue with the install scripts (should a pre-GA product say that previews are GA?)An issue in the release pipeline, where these links are updated, and/or issue in the docs

@mmitche, @bozturk, @rhbandari FYI.  I'm closing this one in favor of the linked install-scripts issue.  As this is not a recent regression, well defined behavior, or breaking folks' builds, it does not meet the FR bar.

**Closed by MattGal** 2022-05-10 21:04 UTC
Labels: First Responder
