### ISSUE TITLE
Ignore neutral checks in Maestro auto-merge

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#10511] opened 2022-08-19 14:58 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In dotnet/runtime we have a couple pipelines that only run when specific source files are touched. This causes the pipeline to report `neutral` status on GitHub checks.

However Maestro auto-merge considers all non-successful statuses as "failing" and so we need to explicitly ignore pipelines in a custom darc config like this:

```
  - Merge Policies:
    AllChecksSuccessful
      ignoreChecks =
                       [
                         "WIP",
                         "license/cla",
                         "runtime-coreclr superpmi-diffs",
                         "runtime-coreclr superpmi-replay",
                         "runtime-libraries enterprise-linux"
                       ]
```

Whenever we have new conditional pipelines like this we need to go back and tweak the `ignoreChecks` for all subscriptions.

It'd be much easier if neutral statuses were ignored by auto-merge, then we could switch back to using the "Standard" merge policy which handles statuses like WIP and Build Analysis automatically.

**Comment by riarenas** [comment] 2022-08-19 15:02
Previously, we decided to not take this approach as we saw instances of PRs only having neutral checks being merged automatically before any azure devops validation could happen. 

https://github.com/dotnet/core-eng/issues/13431 has some more information on this, but basically what ended up happening was:

* maestro posted the PR
* 5 minutes later, the only checks in the PR were neutral, either from pipelines that don't run automatically like in this case, or build analysis.
* Maestro saw no failed checks, merged the PR before any validation ran.

It could be time to revisit and see if we can find a better solution than keeping neutral checks in the "not success" case.

**Comment by riarenas** [comment] 2022-09-15 14:53
We discussed this again and decided it's not something we want to change. 

The AllChecksSuccessful policy should keep its current behavior, which is stated in the [darc documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Darc.md):

>AllChecksSuccessful - All PR checks must be successful, potentially ignoring a specified set of checks. Checks might be ignored if they are unrelated to PR validation. The check name corresponds to the string that shows up in GitHub/Azure DevOps.

The biggest problem with attempting to change from "everything is successful" to "nothing has explicitly failed" is that we have no way to differentiate when a check is skipped or posts a neutral status by design, or when there's a problem. We would rather err on the side of caution and block the automatic merging in those cases, so that the individual cases are investigated.

A way to mitigate this problem today is to use batched subscriptions, in that case when you add a new pipeline that needs to be ignored by maestro, you would rely on the `set-repository-policies` command to modify the merge policies for an entire branch instead of having to set them on a per-subscription basis.

There are a couple improvements that I'm going to propose for whenever we work in the dependency flow / darc space again:

* Provide a way to clone subscriptions and branch policies. This way you could modify one of your subscriptions with the new , and then clone it into your other subscriptions or branches. https://github.com/dotnet/arcade/issues/10871
* Allow the standard merge policy to take additional ignoreChecks: This way you can keep using the standard merge policy, but add any repo-specific checks to be skipped. https://github.com/dotnet/arcade/issues/10872

**Closed by riarenas** 2022-09-15 14:53 UTC
