### ISSUE TITLE
BARViz showing username/password popup when accessing AzDO

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7527] opened 2021-06-15 14:34 UTC
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

As of the morning of 6/15, a username and password popup is shown when accessing BARViz. I believe this is happening when it's attempting to access AzDO build and/or code info.

**Comment by riarenas** [comment] 2021-06-15 14:59
THis is most likely due to https://github.com/dotnet/core-eng/issues/13351

**Comment by markwilkie** [comment] 2021-06-18 14:49
@ilyas1974 - has this been sorted already? (I seem to recall it has)

**Comment by ilyas1974** [comment] 2021-06-18 14:52
I believe so - let me have someone in FR confirm.

**Comment by missymessa** [comment] 2021-06-18 15:32
This issue isn't reproducing for me. So I'll close it. I'll direct the RCA to the other one that Michelle filled out.

**Closed by missymessa** 2021-06-18 15:32 UTC
Labels: First Responder, Needs Triage, RCA Requested
