### ISSUE TITLE
Support publishing to VS Drop

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#878] opened 2018-09-26 18:29 UTC
Whether or not to publish to VS Drop should be re-evaluated and probably implemented.  This is especially true when we have a "blessed build".

**Comment by JohnTortugo** [comment] 2018-11-26 19:37
@markwilkie is this blocking build preview?

Cc'ed @ericstj @tmat @natemcmaster

**Comment by JohnTortugo** [comment] 2019-05-15 21:30
Let @johnbeisner knows when this gets done.

**Comment by riarenas** [comment] 2019-09-26 17:37
@markwilkie should we be looking into this one for servicing 3, or should we look into this for the next release?

**Comment by riarenas** [comment] 2020-01-16 06:04
This one keeps popping up from time to time. Moving to current epic.

**Comment by riarenas** [comment] 2020-06-23 16:04
I think we can just close this as a dupe of https://github.com/dotnet/arcade/issues/5538, which has a lot more details on how this is being throught out.

**Closed by riarenas** 2020-06-23 16:04 UTC
Labels: QuickConfidentReleases
