### ISSUE TITLE
Longest build path not going to base of the graph

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6210] opened 2020-09-18 22:01 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

So, I just noticed a weird occurrence in the longest build path graph on BarViz. It appears that for, at least, .Net 6 Dev and .Net 5 RC 2, the longest build path calculation isn't starting at the correct roots:

![Screen Shot 2020-09-18 at 2 58 59 PM](https://user-images.githubusercontent.com/9666644/93648375-7e39ac00-f9bf-11ea-9f6d-1a048730aacf.png)

![Screen Shot 2020-09-18 at 2 59 18 PM](https://user-images.githubusercontent.com/9666644/93648397-88f44100-f9bf-11ea-84c3-92e181fa7611.png)

I would expect for, in the case of .Net 6 Dev, installer be part of the longest build path, as sdk is not a shipping product and the latest build of sdk -> installer was a product dependency. Additionally, .NET 5 RC 2 is all messed up, indicating that the longest build path stops at wpf. This seemed to be fine a few days ago, so I'm wondering if something got rolled out recently.

@lpatalas 
FYI @mmitche

**Comment by mmitche** [comment] 2020-09-18 22:18
Yeah it was good prior to the last rollout at least. Thanks for the heads up.

**Comment by lpatalas** [comment] 2020-09-19 06:08
I just checked and the graphs look ok again. There were no changes related to graph generation in last rollout so I have suspicion that we may be picking some "work-in-progress" state sometimes. Maybe the builds are running at the moment when the graph is generated and not all dependencies are written to the BAR yet? Unfortunately I'm out of office until 25th so won't be able to investigate it next week.

![image](https://user-images.githubusercontent.com/1406063/93660354-4cbbf180-fa4e-11ea-97f6-b3b5c0b8367c.png)
![image](https://user-images.githubusercontent.com/1406063/93660353-3ca41200-fa4e-11ea-9bac-c1f9f930d49a.png)

**Comment by adiaaida** [comment] 2020-09-21 14:45
I think investigation can wait until you're back, but I just wanted to note that I'm seeing it in RC2 again (the sdk->installer dependency), but not .NET 6. Very strange. It definitely knows there's a dependency (though I guess that's on the subscription, so that make sense). I assume what you're suggesting is that, if the deps for the most recent build haven't been written to the BuildDependencies table yet, IsTooling will return true? That sounds like it makes sense, but maybe we could try to be more robust and check the most recent build that has entered the BuildDependencies table. Seems weird to me, though, that a Build could be entered into the Builds table so much faster than it enters the BuildDependencies table. I'd expect those two things to happen pretty much simultaneously.

**Comment by lpatalas** [comment] 2020-09-29 09:31
I'm taking a look at it.

**Comment by lpatalas** [comment] 2020-09-30 20:36
I tried to investigate it but it's pretty hard to find out what causes the issue. Most of the time the graph looks ok. The issue manifests from time to time but after a while the longest build path goes back to normal. It will be tricky to reproduce it.

My semi-blind guess is that it may be caused by `!e.IsToolingOnly` condition in: https://github.com/dotnet/arcade-services/blob/737108990a317c591d6beb46197a1b094e5979a6/src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyFlowGraph.cs#L305. I think this condition may be unnecessary so I will try to remove it and see if it helps.

**Comment by lpatalas** [comment] 2020-10-06 23:40
I tested changes mentioned in previous comment but it does not seem like a good idea to change that part of the code.

The problems with this issue are that: it's not happening too often from what I see, I can't reproduce it locally and I'm not completely sure why it's happening other than my guesses from comment above. I'm also wondering how critical it is because it seems that I could spend a lot of time just on investigating this. On the other hand it may be preventing us from closing the telemetry epic I guess.

@adiaaida @mmitche What would be your thoughts on this? Should I invest more time in investigating it now? Maybe you have any tips on what to check to find the root cause?

**Comment by lpatalas** [comment] 2020-10-12 13:59
This issue appeared once again for `.NET 6 Dev` so I was able to do some more investigation today.

![net6dev-graph](https://user-images.githubusercontent.com/1406063/95751682-3e54a480-0c9f-11eb-852f-574a8e8f0148.png)

On the graph we can see that longest path does not follow from `dotnet/aspnetcore` to `dotnet/sdk` as it should. I checked that subscription and I get following data:

```
{
  "Id": "c0c2be01-34a3-46d9-31fe-08d7a4f3bc87",
  "ChannelId": "1296",
  "SourceRepository": "https://github.com/dotnet/aspnetcore",
  "TargetRepository": "https://github.com/dotnet/sdk",
  "TargetBranch": "master",
  "Policy": "{\"Batchable\":false,\"UpdateFrequency\":2,\"MergePolicies\":[{\"Name\":\"Standard\",\"Properties\":{}}]}",
  "LastAppliedBuildId": "67288",
  "Enabled": "True"
}
```

That build looks like this:

```
{
  "Id": "67288",
  "GitHubRepository": "https://github.com/dotnet/aspnetcore",
  "GitHubBranch": "master",
  "Commit": "ab973d23fb5fc3b00d37ba63182b5bb14dc02803",
  "AzureDevOpsBuildNumber": "20201009.13",
  "DateProduced": "2020-10-10T08:20:57.7130659+00:00",
  "AzureDevOpsRepository": "https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore",
  "AzureDevOpsAccount": "dnceng",
  "AzureDevOpsBranch": "refs/heads/master",
  "AzureDevOpsBuildDefinitionId": "21",
  "AzureDevOpsBuildId": "847871",
  "AzureDevOpsProject": "internal",
  "Released": "False",
  "Stable": "False"
}
```

But now when I try to query `BuildDependencies` table for builds that depend on `67288` I get only rows for `dotnet/aspnetcore-tooling` and none for `dotnet/sdk`:

```
select *
from [dbo].[BuildDependencies] as D
join [dbo].[Builds] as B on B.Id = D.BuildId
where D.DependentBuildId = 67288

[
  {
    "BuildId": "67290",
    "DependentBuildId": "67288",
    "IsProduct": "True",
    "TimeToInclusionInMinutes": "56.069161665",
    "Id": "67290",
    "GitHubRepository": "https://github.com/dotnet/aspnetcore-tooling",
    "GitHubBranch": "master",
    "Commit": "10cfcf88ef3ac62002b34566b71e58683399bf42",
    "AzureDevOpsBuildNumber": "20201010.1",
    "DateProduced": "2020-10-10T09:32:17.2728794+00:00",
    "AzureDevOpsRepository": "https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore-tooling",
    "AzureDevOpsAccount": "dnceng",
    "AzureDevOpsBranch": "refs/heads/master",
    "AzureDevOpsBuildDefinitionId": "262",
    "AzureDevOpsBuildId": "847929",
    "AzureDevOpsProject": "internal",
    "Released": "False",
    "Stable": "False"
  },
  {
    "BuildId": "67340",
    "DependentBuildId": "67288",
    "IsProduct": "True",
    "TimeToInclusionInMinutes": "56.069161665",
    "Id": "67340",
    "GitHubRepository": "https://github.com/dotnet/aspnetcore-tooling",
    "GitHubBranch": "master",
    "Commit": "1d37accabf3a482edf02a3d341b4ac4b04e5e4f4",
    "AzureDevOpsBuildNumber": "20201012.1",
    "DateProduced": "2020-10-12T13:29:53.4342305+00:00",
    "AzureDevOpsRepository": "https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore-tooling",
    "AzureDevOpsAccount": "dnceng",
    "AzureDevOpsBranch": "refs/heads/master",
    "AzureDevOpsBuildDefinitionId": "262",
    "AzureDevOpsBuildId": "848920",
    "AzureDevOpsProject": "internal",
    "Released": "False",
    "Stable": "False"
  }
]
```

When I look at merged PRs in `dotnet/sdk` we see that the build `67288` was applied in https://github.com/dotnet/sdk/pull/14090. However for some reason the `BuildDependencies` table was not updated.

In code we have following query that determines if given edge on the graph is tooling or product:

```
public bool IsProductDependency(int buildId, string repositoryName, string branchName)
        {
            return BuildDependencies
                .Any(d => d.IsProduct
                    && d.DependentBuildId == buildId
                    && ((d.Build.GitHubRepository == repositoryName
                            && d.Build.GitHubBranch == branchName)
                        || (d.Build.AzureDevOpsRepository == repositoryName
                            && d.Build.AzureDevOpsBranch == branchName)));
        }
```

Because there are no `BuildDependencies` rows where `buildId = 67288 and repositoryName = "dotnet/sdk"` this query returns no results and we assume that there are no tooling dependencies.

**Comment by adiaaida** [comment] 2020-10-12 15:18
Looking at the official build history for sdk, I think I have a theory of what's going on:

1. aspnetcore creates a new build.
2. The subscription to sdk gets triggered in github. Builds run. It gets checked in. The subscription gets updated.
3. The change is mirrored over to the internal repo.
4. A build is eventually triggered (but as of right now, has not been: https://dev.azure.com/dnceng/internal/_build?definitionId=140&_a=summary. The most recently completed master build is 20201008.29, where as the build that we're looking for is 20201009.13. (It was just easier for me to grab these Ids rather than look up the bar ids).

So the problem is that the subscription was updated, but an official build of sdk hasn't run yet, so a new bar build for sdk with those new dependencies hasn't been added. @mmitche does this sound right?

If so, this suggests that we have a race condition that's not going to easily go away, and perhaps we need to do the look up in BuildDependencies the opposite direction: get the most recent build of the target repo, look up all of its dependencies in BuildDependencies, and find the one that matches the source repo, rather than looking up based on the DependentBuildId.

**Comment by lpatalas** [comment] 2020-10-19 15:03
I'm working on implementing the changes described above.

**Comment by lpatalas** [comment] 2020-10-21 15:00
It was closed automatically by GitHub because of link inside PR. I will reopen it so that we can track it. I will close it after confirming that everything works correctly on production instance.

**Closed** 2020-10-27 16:58 UTC

**Comment by lpatalas** [comment] 2020-10-30 12:34
I checked it on production and looks ok now.
