### ISSUE TITLE
If helix sdk fails when sending job because there was a bad request, error is not diagnosable

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#1274] opened 2018-11-06 02:07 UTC
If the job failed to be sent for some reason, I would get:

```
2018-11-06T01:46:12.2089156Z /home/vsts_VSTSContainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18529.4/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(129,5): error : HttpOperationException: Operation returned an invalid status code 'BadRequest' [/__w/1/s/eng/sendtohelix.proj]
2018-11-06T01:46:12.2090839Z /home/vsts_VSTSContainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18529.4/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(129,5): error :    at Microsoft.DotNet.Helix.Client.Job.NewOperationWithHttpMessagesAsync(JobCreationRequest newJob, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/Generated/Job.cs:line 256 [/__w/1/s/eng/sendtohelix.proj]
2018-11-06T01:46:12.2091556Z /home/vsts_VSTSContainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18529.4/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(129,5): error :    at Microsoft.DotNet.Helix.Client.JobExtensions.NewOperationAsync(IJob operations, JobCreationRequest newJob, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/Generated/JobExtensions.cs:line 66 [/__w/1/s/eng/sendtohelix.proj]
2018-11-06T01:46:12.2092371Z /home/vsts_VSTSContainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18529.4/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(129,5): error :    at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync() in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 132 [/__w/1/s/eng/sendtohelix.proj]
2018-11-06T01:46:12.2093092Z /home/vsts_VSTSContainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18529.4/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(129,5): error :    at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore() in /_/src/Microsoft.DotNet.Helix/Sdk/SendHelixJob.cs:line 150 [/__w/1/s/eng/sendtohelix.proj]
2018-11-06T01:46:12.2093627Z /home/vsts_VSTSContainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18529.4/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(129,5): error :    at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 41 [/__w/1/s/eng/sendtohelix.proj]
2018-11-06T01:46:12.2094772Z /home/vsts_VSTSContainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18529.4/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(129,5): error :  [/__w/1/s/eng/sendtohelix.proj]
```

So then I have to repro locally, open fiddler and see what the request actually returned in the json. 

It would be great if this error could be improved and show the actual error in the request form.

cc: @alexperovich @jonfortescue

**Comment by markwilkie** [comment] 2018-11-06 19:44
Any suggestions @alexperovich ?

**Comment by jonfortescue** [comment] 2018-11-06 21:20
@alexperovich autorest seems to claim this is GIGO https://github.com/Azure/autorest/issues/693

**Comment by alexperovich** [comment] 2018-11-06 21:33
We do this already IIRC. We have a "default" response. That doesn't really fix this issue though because the exception message is still just "The operation failed with 'BadRequest'". The exception just happens to have a Body property that can be inspected, but that data won't be available with the stack trace.

**Comment by safern** [comment] 2018-11-06 21:57
Yes I'm actually expecting something like, `"The operation failed with 'BadRequest' with message: 'unknown QueueID'"`

**Comment by alexperovich** [comment] 2018-11-07 00:54
I really want it to return an `ArgumentException` with message `The queue id '<queueid>' does not exist`. That requires a bit more work. I plan to fix this along with the other generated api clients as part of dotnet/core-eng#3728.

**Comment by safern** [comment] 2018-11-07 02:00
I’m wasn’t referring to include the queue id value that doesn’t exist. I’m that was the literal error I was getting in the response body. Had to look at it through fiddler though.

**Comment by markwilkie** [comment] 2018-11-07 15:48
@alexperovich - is there something we can do shorter term to by just grabbing the response body contents so folks don't need fiddler?

**Comment by alexperovich** [comment] 2018-11-07 21:53
We can, it should be already available on the exception. Adding custom handling for that exception is doable.

**Comment by HaoK** [comment] 2018-11-26 21:30
I also ran into the unhelpful bad request error, root cause of all my helix jobs being rejected was when I accidentally removed the pr/ in front of the source.  Would definitely be ideal if that error was surfaced to the output of the build

**Comment by alexperovich** [comment] 2019-01-11 22:34
This is fixed now via #1746

**Closed by alexperovich** 2019-01-11 22:34 UTC

**Comment by adamsitnik** [comment] 2019-02-12 07:49
@alexperovich are you sure that this was fixed?

I am still getting this error with no details:

```log
2019-02-12T07:40:48.5251664Z /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18629.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(85,5): error : HttpOperationException: Operation returned an invalid status code 'BadRequest' [/__w/1/s/eng/common/helixpublish.proj]
2019-02-12T07:40:48.5252699Z /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18629.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(85,5): error :    at Microsoft.DotNet.Helix.Client.Job.NewOperationWithHttpMessagesAsync(JobCreationRequest newJob, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/Generated/Job.cs:line 256 [/__w/1/s/eng/common/helixpublish.proj]
2019-02-12T07:40:48.5253594Z /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18629.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(85,5): error :    at Microsoft.DotNet.Helix.Client.JobExtensions.NewOperationAsync(IJob operations, JobCreationRequest newJob, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/Generated/JobExtensions.cs:line 66 [/__w/1/s/eng/common/helixpublish.proj]
2019-02-12T07:40:48.5254607Z /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18629.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(85,5): error :    at Microsoft.DotNet.Helix.Client.HelixApi.RetryAsync[T](Func`1 function, Action`1 logRetry, Func`2 isRetryable) [/__w/1/s/eng/common/helixpublish.proj]
2019-02-12T07:40:48.5256024Z /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18629.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(85,5): error :    at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync(Action`1 log) in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 153 [/__w/1/s/eng/common/helixpublish.proj]
2019-02-12T07:40:48.5257650Z /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18629.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(85,5): error :    at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore() in /_/src/Microsoft.DotNet.Helix/Sdk/SendHelixJob.cs:line 209 [/__w/1/s/eng/common/helixpublish.proj]
2019-02-12T07:40:48.5259098Z /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18629.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(85,5): error :    at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 43 [/__w/1/s/eng/common/helixpublish.proj]
2019-02-12T07:40:48.5259758Z /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/1.0.0-beta.18629.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(85,5): error :  [/__w/1/s/eng/common/helixpublish.proj]
2019-02-12T07:40:48.5298866Z 
```

More details: https://github.com/dotnet/performance/pull/265#issuecomment-461876544

**Comment by alexperovich** [comment] 2019-02-12 08:27
Thats a very old version of the helix api client. You should update to the latest.

________________________________

**Comment by adamsitnik** [comment] 2019-02-12 08:32
@alexperovich thank you!
