### ISSUE TITLE
Git issues during dependency updates

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7343] opened 2021-05-04 22:58 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We've had some dependency update failures due to the nodes trying to access files in the git installation that are already in use by another process

```
Unexpected error processing action: The process cannot access the file 'D:\SvcFab_App\MaestroApplicationType_App0\temp\PullRequestActorServiceType\132639871000904417\git-portable\Git-2.22.0-64-bit.zip' because it is being used by another process.
```

**Comment by chcosta** [comment] 2021-05-18 17:31
How do I get from one of the linked issues to an actual failure?

**Comment by riarenas** [comment] 2021-05-18 17:34
There should be exception logs in AI around the "last seen" timestamp in the individual issues.

**Comment by chcosta** [comment] 2021-05-18 20:30
AI shows IO exceptions that are from two callstacks regularly occuring, both are being thrown from the same method.

IO exception trying to remove a directory
```
System.IO.IOException:
   at System.IO.FileSystem.RemoveDirectoryRecursive (System.IO.FileSystem, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.FileSystem.RemoveDirectory (System.IO.FileSystem, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at SubscriptionActorService.LocalGit+<GetPathToLocalGitAsync>d__7.MoveNext (SubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=nullSubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: /_/src/Maestro/SubscriptionActorService/LocalGit.csSubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: 109)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at SubscriptionActorService.DarcRemoteFactory+<>c__DisplayClass11_0+<<GetRemoteAsync>b__0>d.MoveNext (SubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=nullSubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: /_/src/Maestro/SubscriptionActorService/DarcRemoteFactory.csSubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: 81)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.DotNet.Services.Utility.ExponentialRetry+<RetryAsync>d__5`1.MoveNext (Microsoft.DotNet.Services.Utility, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.DotNet.Services.Utility, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: /_/src/Shared/Microsoft.DotNet.Services.Utility/ExponentialRetry.cs)
```

IO Exception trying to open a file
```
System.IO.IOException:
   at System.IO.FileStream.ValidateFileHandle (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.FileStream.CreateFileOpenHandle (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.FileStream..ctor (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at SubscriptionActorService.LocalGit+<GetPathToLocalGitAsync>d__7.MoveNext (SubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=nullSubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: /_/src/Maestro/SubscriptionActorService/LocalGit.csSubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: 111)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at SubscriptionActorService.DarcRemoteFactory+<>c__DisplayClass11_0+<<GetRemoteAsync>b__0>d.MoveNext (SubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=nullSubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: /_/src/Maestro/SubscriptionActorService/DarcRemoteFactory.csSubscriptionActorService, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: 81)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.DotNet.Services.Utility.ExponentialRetry+<RetryAsync>d__5`1.MoveNext (Microsoft.DotNet.Services.Utility, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.DotNet.Services.Utility, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: /_/src/Shared/Microsoft.DotNet.Services.Utility/ExponentialRetry.cs)
```
Both appear to be from this section of code, https://github.com/dotnet/arcade-services/blob/6e63e7b48b65f572d902a4ecc5381c5f9c808e73/src/Maestro/SubscriptionActorService/LocalGit.cs#L68-L100

I'm not familiar with how this code is running, but I'd presume that more than one instance of the subscriptionactorservice is running, and that the [SemaphoreSlim](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim?view=net-5.0) class [being used](https://github.com/dotnet/arcade-services/blob/6e63e7b48b65f572d902a4ecc5381c5f9c808e73/src/Maestro/SubscriptionActorService/LocalGit.cs#L24) is not sufficient because it is only app local and not shared across classes.

@ChadNedzlek thoughts?

**Comment by ChadNedzlek** [comment] 2021-05-18 23:23
Makes sense that a Semaphore wouldn't help, since the same service might have multiple instances on the same machine.  We'd need a machine level one, which are a bit trickier, and don't really have good async versions that I can find.

**Comment by ChadNedzlek** [comment] 2021-05-18 23:24
It seems the the services should be using isolates storage locations for things, so they aren't interfering with each other would probably be the better option.  Using the instanceId of the service to make that.

**Comment by chcosta** [comment] 2021-05-19 15:46
@ChadNedzlek , do you think a [system semaphore](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphore.-ctor?view=net-5.0#System_Threading_Semaphore__ctor_System_Int32_System_Int32_System_String_) would be sufficient?

**Comment by chcosta** [comment] 2021-05-21 15:48
I'm going to move this to the backlog so that it can be addressed by someone in next week's FR shift.  @ChadNedzlek , please remove this from FR if you think it's not appropriate there (but I think it makes sense there unless you are touching this stuff in your epic, or another epic).

**Comment by ChadNedzlek** [comment] 2021-06-15 00:58
A system semaphore could work. They don't have "async" methods, so we'd need to be careful how we use them (mixing thread blocking constructs into async code can lead to weird deadlocks)

**Comment by alexperovich** [comment] 2021-07-14 21:28
We shouldn't need cross-process mutexing. The LocalGit thing is a singleton, thus one-instance-per-service-instance, and we use the service isolated storage, so it shouldn't collide with anything.

**Comment by alexperovich** [comment] 2021-07-14 21:45
I also can't see any evidence of this happening at all anymore. It happened for a single 90 second period on the 30th. The code all does the right thing, so this very much feels like something else was running on the machine and messing with our files. Like defender or just windows things.

**Comment by riarenas** [comment] 2021-07-14 21:51
I'm fine with closing until it comes back. The 30th was a rollout day, so there might have been Service fabric-y things going on besides just the normal operations.

**Comment by riarenas** [comment] 2021-07-14 21:51
Didn't mean to actually close it.

**Comment by alexperovich** [comment] 2021-07-14 21:52
I did.

**Comment by riarenas** [comment] 2021-08-04 20:01
We saw another surge of this exact same errors during today's rollout: [app insights query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAw3K0QmAMAwFwFUeXUYEl6jpAwNtU9KACg5vv%252B%252F4CEeo9YkP90UnhttZ2fYCsR5ZF6XDJNdNI61lXug4X4Q2zshtoHDKD2EQVd9KAAAA/timespan/2021-08-04T18%3A00%3A12.000Z%2F2021-08-04T20%3A00%3A12.413Z)

This looks like it can happen when the node comes up. Reopening as it came back.

**Comment by MattGal** [comment] 2021-08-11 00:03
I've got some changes locally that refactor and implement a very simplistic cross-process semaphore for LocalGit.cs:

### Strategy:
- Internal FileSemaphore class that spins and waits for exclusive access to a file path
- Acquires this lock before any downloading
- Simplify check by always calculating the path to git.exe and checking for its existence, since _gitExecutable doesn't actually change per actor/instance, and if it's already there we can just immediately test it.

**Comment by ChadNedzlek** [comment] 2021-08-11 00:07
Didn't want to use a named Mutex?  That's a bit simpler than having to mess with the file system.

**Comment by MattGal** [comment] 2021-08-11 16:20
Created https://github.com/dotnet/arcade-services/pull/1701, after applying Chad's precog PR feedback

**Comment by MattGal** [comment] 2021-08-12 15:19
[Scenario test run was clean](https://dnceng.visualstudio.com/internal/_build/results?buildId=1289292&view=results) and logs indicate that the update process has occurred on all staging nodes, moving to rollout.

**Comment by MattGal** [comment] 2021-08-19 00:03
This is rolled out and [the problem only reproduced with last week's version today](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0utSE4tKMnMzytW4KpRKM9ILUpVKCjKT8pJzfVMUUjOzytJzATKKfnkJyfmuGeWKIGUFZfm5iYWZValKiRVKiQWFORkJieCzIgPSy0qBtIASDnV7FUAAAA%253D/timespan/P1D).

I'll put this in the "validate" column and close after a few days if I don't see any repros with >= v1.1.0-beta.21418.1

**Comment by MattGal** [comment] 2021-09-03 17:55
@epananth has volunteered to venture once more into this issue.

**Closed** 2021-09-23 19:28 UTC
Labels: First Responder
