### ISSUE TITLE
runtime pipeline - MSBuild log file used by another process

### ISSUE THREAD

**Issue by karelz** [dotnet/arcade#9842] opened 2022-06-29 09:36 UTC
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

Rolling runtime runs have seen several identical failures in last 2 weeks:
- [1846661](https://runfo.azurewebsites.net/view/build/?number=1846661) (6/27 AM) - 1x - [AzDO log](https://dev.azure.com/dnceng/public/_build/results?buildId=1846661&view=logs&j=fcaa063f-6419-5e58-b2af-9d549ec8d7bb&t=83613dd5-c469-5fc6-b3ef-ae348715a225&l=729)
- [1845989](https://runfo.azurewebsites.net/view/build/?number=1845989) (6/26 AM) - 1x - [AzDO log](https://dev.azure.com/dnceng/public/_build/results?buildId=1845989&view=logs&j=e36cdb78-1b23-5f53-5d15-e931194c7d32&t=5f3cc2c3-b299-5f57-0006-9e48b00ce7cd&l=737)
- [1845989](https://runfo.azurewebsites.net/view/build/?number=1845989) (6/21 AM) - 1x - [AzDO log](https://dev.azure.com/dnceng/public/_build/results?buildId=1836163&view=logs&j=e36cdb78-1b23-5f53-5d15-e931194c7d32&t=5f3cc2c3-b299-5f57-0006-9e48b00ce7cd&l=736)
- [1833048](https://runfo.azurewebsites.net/view/build/?number=1833048) (6/19 AM 3rd rerun) - 1x - [AzDO log](https://dev.azure.com/dnceng/public/_build/results?buildId=1833048&view=logs&j=e36cdb78-1b23-5f53-5d15-e931194c7d32&t=5f3cc2c3-b299-5f57-0006-9e48b00ce7cd&l=735)

failure:
```
##[error].packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22316.2\tools\VSTest.targets(55,5): error MSB3491: (NETCORE_ENGINEERING_TELEMETRY=Build) Could not write lines to file "D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log". The process cannot access the file 'D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log' because it is being used by another process.
```

**Comment by jonfortescue** [comment] 2022-07-06 19:59
Closing as dupe of #9864.

**Closed by jonfortescue** 2022-07-06 19:59 UTC
Labels: First Responder
