### ISSUE TITLE
CI failure accessing a log file

### ISSUE THREAD

**Issue by noahfalk** [dotnet/arcade#9903] opened 2022-07-07 00:01 UTC
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1862311

### Build leg reported

Installer Build and Test coreclr  windows_x64 Release / Build

### Pull Request

https://github.com/dotnet/runtime/pull/71574

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false
 }
 ```

### Additional information about the issue reported

I see the error ".packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22327.2\tools\VSTest.targets(55,5): error MSB3491: Could not write lines to file "D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log". The process cannot access the file 'D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log' because it is being used by another process." reported in the build analysis. Based on the error message this sounds like something didn't work properly running and analyzing the test automation and there is no clear link back to any problem in the build being tested.
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by riarenas** [comment] 2022-07-11 18:38
This looks like a duplicate of https://github.com/dotnet/arcade/issues/9864. Please reopen with details on why this is different if that's not the case.

**Closed by riarenas** 2022-07-11 18:38 UTC
Labels: First Responder, Detected By - Customer, Known Build Error
