### ISSUE TITLE
Upgrade Microsoft.CodeCoverage and Microsoft.NET.Test.Sdk to 17.4.0

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade#11856] opened 2022-12-06 23:04 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See context in https://github.com/dotnet/arcade/issues/11842. We did this as a workaround, and were told that the issue we are facing was fixed in later versions. We need to upgrade our version of CodeCoverage (and Test.Sdk) to 17.4.0, which is the latest stable version, and then remove the disable of UseVerifiableInstrumentation.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Does not need a release note description.

**Comment by MarcoRossignoli** [comment] 2022-12-07 07:59
On TP team we were thinking if there's a way to dogfood our preview by design and maybe have a good override in case of blocking issue, this could help us to test our code in all arcade project, something like "<EnableMicrosoftNETTest.dkPreview>true</EnableMicrosoftNETTest.dkPreview>" that can be disabled and fallback to last stable version. We could keep it up to date manually with a PR or with DARC.

cc: @nohwnd @Evangelink

**Comment by MarcoRossignoli** [comment] 2022-12-09 09:37
Another idea is to provide floating version for the two package above like `17.*-*` so we will dogfood the last one(we ship in public here https://pkgs.dev.azure.com/dnceng/public/_packaging/test-tools/nuget/v3/index.json)

**Comment by MattGal** [comment] 2023-01-05 01:09
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/28631 - helix service
https://github.com/dotnet/arcade-services/pull/2168 - arcade-services

**Comment by Evangelink** [comment] 2023-01-05 12:41
That's only the update of code coverage and not test SDK. Are you planning to also handle it?

**Comment by MattGal** [comment] 2023-01-05 16:06
> That's only the update of code coverage and not test SDK. Are you planning to also handle it?

This was an oversight, will go update both PRs.

**Comment by MattGal** [comment] 2023-01-05 18:33
Hit some interesting issues trying to do this in arcade-services which I discussed with @MarcoRossignoli , he's going to investigate on his end and advise how to proceed.

**Comment by MarcoRossignoli** [comment] 2023-01-09 15:13
Yeah I'll take a look soon, from first investigation I'm pretty sure we're not inside any sdk so that implicit warning/error is unexpected, I'm trying to understand if it's a nuget bug or if I'm missing something. I've asked some help to @rainersigwald to, maybe he can speedup the investigation.

Sorry for the delay, if you're blocked and in rush I think it's fine to merge as-is and postpone the upgrade of the test sdk.

**Comment by MattGal** [comment] 2023-01-09 17:53
> Yeah I'll take a look soon, from first investigation I'm pretty sure we're not inside any sdk so that implicit warning/error is unexpected, I'm trying to understand if it's a nuget bug or if I'm missing something. I've asked some help to @rainersigwald to, maybe he can speedup the investigation.
> 
> Sorry for the delay, if you're blocked and in rush I think it's fine to merge as-is and postpone the upgrade of the test sdk.

As far as I can tell this doesn't block anything, it was just work sitting on the backlog that I grabbed.  Please let me know if you have suggestions to actually update it.

**Comment by MarcoRossignoli** [comment] 2023-01-10 07:50
Thanks to @rainersigwald help we found out that the old test sdk is implicitly imported by `.nuget\packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.22601.5\tools\Tests.props`

**Comment by MattGal** [comment] 2023-01-12 19:00
Attempt 2 in arcade services is https://github.com/dotnet/arcade-services/pull/2187

**Comment by Evangelink** [comment] 2023-01-12 19:05
I didn't pay attention earlier but it'd be better to use `17.4.1`.

**Comment by MattGal** [comment] 2023-01-12 19:15
> I didn't pay attention earlier but it'd be better to use `17.4.1`.

Do you mind explaining the benefit of doing so?

**Comment by Evangelink** [comment] 2023-01-13 07:59
Sure `17.4.1` includes a fix for resolution of satellite assemblies because it seems that `17.4.0` got a regression causing some issue with different culture. The exact conditions for the error are not perfectly figured out so I think that's safer to use `17.4.1` rather than `17.4.0`.

**Comment by MattGal** [comment] 2023-01-17 21:41
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/28886 is merged, I'll leave this in "validate" until the official build is clean for dotnet-helix-service.

**Comment by MattGal** [comment] 2023-01-17 21:58
Test and coverage runs for both arcade-services and helix-service are green, closing .

**Closed by MattGal** 2023-01-17 21:58 UTC
Labels: FROps
