### ISSUE TITLE
Failed to find compatible device: arm64-v8a

### ISSUE THREAD

**Issue by karelz** [dotnet/arcade#10617] opened 2022-08-27 13:42 UTC
- 9/13 - [15374](https://runfo.azurewebsites.net/view/build/?number=15374) - 1x hit:
    - System.ComponentModel.EventBasedAsync.Tests Work Item - DNCENGWIN-116
- 9/13 - [14506](https://runfo.azurewebsites.net/view/build/?number=14506) - 1x hit:
    - System.CodeDom.Tests Work Item - DNCENGWIN-116
- 9/12 - [13766](https://runfo.azurewebsites.net/view/build/?number=13766) - 1x hit:
    - System.Net.Http.Json.Unit.Tests Work Item - DNCENGWIN-116
- 9/8 AM Rolling run [8501](https://runfo.azurewebsites.net/view/build/?number=8501) - 4x hits:
    - System.Net.Http.Functional.Tests Work Item - DNCENGWIN-085
    - System.IO.FileSystem.DriveInfo.Tests Work Item - DNCENGWIN-117
    - System.ComponentModel.TypeConverter.Tests Work Item - DNCENGWIN-055
    - System.ComponentModel.EventBasedAsync.Tests Work Item - DNCENGWIN-097
- 9/7 PM Rolling run [7900](https://runfo.azurewebsites.net/view/build/?number=7900) - 2x hits:
    - System.DirectoryServices.Protocols.Tests Work Item - DNCENGWIN-097
    - System.Composition.Convention.Tests Work Item - DNCENGWIN-117
- 9/7 AM Rolling run [6968](https://runfo.azurewebsites.net/view/build/?number=6968) - 2x hits:
    - System.Diagnostics.Tracing.Tests Work Item - DNCENGWIN-085
    - Microsoft.Extensions.Configuration.Tests Work Item - DNCENGWIN-062
- 9/5 PM Rolling run [5191](https://runfo.azurewebsites.net/view/build/?number=5191) - 1x hit:
    - System.ComponentModel.EventBasedAsync.Tests Work Item - DNCENGWIN-098
- 9/5 AM Rolling run [4698](https://runfo.azurewebsites.net/view/build/?number=4698) - 3x hits:
    - Microsoft.Extensions.Configuration.Json.Tests Work Item - DNCENGWIN-071
    - Microsoft.Extensions.Primitives.Tests Work Item - DNCENGWIN-098
    - System.Linq.Tests Work Item - DNCENGWIN-081
- 9/4 PM Rolling run [4489](https://runfo.azurewebsites.net/view/build/?number=4489) - 2x hits:
    - System.Net.ServicePoint.Tests Work Item - DNCENGWIN-098
    - Microsoft.Extensions.FileSystemGlobbing.Tests Work Item - DNCENGWIN-081
- 9/3 PM Rolling run [4234](https://runfo.azurewebsites.net/view/build/?number=4234) - 2x hits:
    - System.Numerics.Vectors.Tests - DNCENGWIN-098
    - Microsoft.Extensions.Configuration.Json.Tests - DNCENGWIN-081
- 9/2 PM Rolling run [3461](https://runfo.azurewebsites.net/view/build/?number=3461) - 1x hit:
    - Microsoft.Extensions.DependencyModel.Tests - DNCENGWIN-081
- 9/2 AM Rolling run [2661](https://runfo.azurewebsites.net/view/build/?number=2661) - 2x hits:
    - System.ComponentModel.TypeConverter - DNCENGWIN-085
    - System.ComponentModel.EventBasedAsync - DNCENGWIN-081
- gap in runs 8/27-9/2
- 8/27 PM Rolling run [1972127](https://runfo.azurewebsites.net/view/build/?number=1972127) - 3x hits:
    - 	System.Net.Security.Tests Work Item - DNCENGWIN-118
    - System.Net.Http.Unit.Tests Work Item - DNCENGWIN-048
    - System.Linq.Tests Work Item - DNCENGWIN-053
- 8/27 AM Rolling run [1971504](https://runfo.azurewebsites.net/view/build/?number=1971504) - 3x hits:
    - System.Net.NameResolution.Functional.Tests Work Item - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-275b28d624c64179b2/System.Net.NameResolution.Functional.Tests/1/console.f1cd4a83.log?%3Fhelixlogtype%3Dresult) - DNCENGWIN-118
    - System.IO.Compression.Tests Work Item - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-275b28d624c64179b2/System.IO.Compression.Tests/1/console.0bfd6be8.log?%3Fhelixlogtype%3Dresult) - DNCENGWIN-053
    - Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests Work Item - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-275b28d624c64179b2/Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests/1/console.de27c24e.log?%3Fhelixlogtype%3Dresult) - DNCENGWIN-048
- 8/26 PM Rolling run [1970381](https://runfo.azurewebsites.net/view/build/?number=1970381) - 3x hits:
    - System.Reflection.CoreCLR.Tests Work Item - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cab1e42008a742f392/System.Reflection.CoreCLR.Tests/1/console.cd578a34.log?%3Fhelixlogtype%3Dresult) - DNCENGWIN-118
    - System.Globalization.CalendarsWithConfigSwitch.Tests Work Item - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cab1e42008a742f392/System.Globalization.CalendarsWithConfigSwitch.Tests/1/console.e9feda50.log?%3Fhelixlogtype%3Dresult) - DNCENGWIN-062
    - Microsoft.Bcl.AsyncInterfaces.Tests Work Item - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cab1e42008a742f392/Microsoft.Bcl.AsyncInterfaces.Tests/1/console.ae69a68f.log?%3Fhelixlogtype%3Dresult) - DNCENGWIN-048

net7.0-Linux-Release-arm64-Mono_Release_LinuxBionic-Windows.10.Amd64.Android.Open

Example of log:
```
[14:37:54] dbug: Attempt 9 failed, retrying in 10 seconds...
[14:38:04] dbug: Executing command: 'C:\h\w\AA090904\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.22422.1\runtimes\any\native\adb\windows\adb.exe devices -l'
[14:38:04] dbug: No attached devices found
                 Exit code: 0
                 Std out:
                 List of devices attached
                 
                 
                 
                 
[14:38:04] dbug: All 9 retries of action failed
[14:38:04] warn: No attached devices / emulators detected. Check that any emulators have been started, and attached device(s) are connected via USB, powered-on, unlocked and authorized.
[14:38:04] dbug: No suitable devices found
[14:38:04] crit: Failed to find compatible device: arm64-v8a
```

**Comment by karelz** [comment] 2022-08-29 18:42
Tagging @dotnet/dncenghot

**Comment by garath** [comment] 2022-08-29 18:53
Acknowledged, investigating.

**Comment by garath** [comment] 2022-08-29 19:06
Machines -048, -062 and -118 are clearly misbehaving, I've taken them offline for now.

**Comment by premun** [comment] 2022-08-29 20:59
@garath might make sense to do it for all of these https://github.com/dotnet/arcade/issues/10548

Seems like the alert got missed?

**Comment by garath** [comment] 2022-08-29 21:15
> Seems like the alert got missed?

Ah, yeah, seems like that has happened. I have taken the rest of those machines offline, so hopefully jobs flow more smoothly. I will raise an ICM to get the machines fixed-up. @ilyas1974 FYI.

**Comment by garath** [comment] 2022-09-06 22:47
The ICM was [331318192](https://portal.microsofticm.com/imp/v3/incidents/details/331318192/home) and has been closed. I've brought the machines back online.

**Comment by karelz** [comment] 2022-09-08 22:04
There are new hits - some on the same machines. Reopening and updating to post with hits.
@garath can you please take the machines offline again until it is resolved? Thanks!

**Comment by garath** [comment] 2022-09-08 22:41
Yep, looks like this is being handled in #10548. There's an open ICM. There may need to be some additions to it. @dotnet/dnceng will someone on FR please help with that?

**Comment by premun** [comment] 2022-09-09 10:54
Newly failing `097` and `117` were also just disabled and IcM ticket opened

**Comment by garath** [comment] 2022-09-12 18:22
Thanks, @premun. Closing this issue now that the machines are offline and the ICM is up to date.

**Comment by oleksandr-didyk** [comment] 2022-09-14 13:36
I guess it would be better to track it in the current alert issue -> https://github.com/dotnet/arcade/issues/10804#issuecomment-1246147708

I'll disable the machines and create and IcM in the meantime, seems the last IcM was closed as completed but the machines are still facing issues

**Comment by karelz** [comment] 2022-09-14 13:39
The alert has the 116 machine listed. In future, what should be my action on issue like that? Comment?
Or will it automatically be monitored by someone?

In other words -- in future, when I notice some machine is bad, what should I do?
cc @markwilkie

**Comment by karelz** [comment] 2022-09-14 13:53
@premun do you know who is involved in those things? Is it Mobile infra? Or general repo infra?

**Comment by premun** [comment] 2022-09-14 14:06
I don't have visibility into this much but I am now checking latest builds on main and it seems to be working for most mobile tests:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75458-merge-5db03fa8ca954988b8/System.Runtime.Tests/1/console.6c2ccb31.log?helixlogtype=result

where it says:
```
Reporting 1 events from diagnostics file `/datadisks/disk1/work/B1C70986/w/AB0D0964/e/diagnostics.json`
Analyzing android/test@x86 (1)
```

However, the top result in the description that you updated is seeing this failure. The tests there are the Android headless tests which I believe were written by @directhex?
@directhex it seems that the payload in the headless tests are constructed wrong? The Helix SDK should include some files there (maybe the CWD is changed or something) so that the `xharness-event-processor.py` is called properly.

**Comment by MattGal** [comment] 2022-09-14 18:33
Hi @karelz,

Like @premun , I spent some time checking this out this morning.  The problem as he notes is that CoreCLR seems to be starting xharness directly, as seen in https://github.com/dotnet/runtime/blob/main/eng/testing/BionicRunnerTemplate.cmd#L44.  Since you just run Xharness and immediately return its exit code, we have nowhere to resolve this problem.  "Real" phone devices fail some times, and we have had workarounds (Which mono is already using) for some time as well. 

XHarness has no knowledge of Helix; this is by design since it was meant to be used outside of Helix and we didn't want it to get "polluted" with the details of a test infrastructure otherwise unrelated to it. Invoking it directly means if the specific device you end up running on has a problem, you're out of luck.  

The Arcade Helix SDK _does_ know about Xharness' exit codes and can request both that the machine reboots and to retry on a different machine entirely. Interestingly, the mono team is already using this:; if you check out this query you'll see a real example.  

```
WorkItems
| where WorkItemId == 1060761396
```
Note the exit code 81, followed by a second "infra retry" execution on a different machine, where the test then passes.

Ideally you should emulate what mono is doing here; their usage of the Arcade Helix SDK's XHarness support means when we improve Xharness Arcade functionality, they get this "for free".  Failing that, simply providing copies of the files from https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner and ensuring that xharness-event-processor gets called is a feasible, albeit unsupported-by-dnceng solution.  A _very_ kludge-y solution could be simply to detect the known exit codes like 81 and request infra retry directly in BionicRunnerTemplate.cmd but I do not recommend it.

Feel free to ping me on Teams to discuss further.

**Comment by Chrisboh** [comment] 2022-09-15 16:59
Closing this in favor of our Grafana alert #10804

**Closed by Chrisboh** 2022-09-15 16:59 UTC
Labels: First Responder, Detected By - Customer
