### ISSUE TITLE
Failing to download artifacts on some legs of pipeline

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/arcade#11802] opened 2022-12-01 21:05 UTC
### Build

https://dev.azure.com/dnceng/internal/_build/results?buildId=2055077&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=2054005&view=results

### Build leg reported

SuperPMI collect libraries_tests pmi OSX arm64 checked

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "The \"DownloadFromResultsContainer\" task failed unexpectedly.",
    "BuildRetry": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

We occasionally see errors while downloading the artifacts from helix. See https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2055077/logs/1436. They happen on selected legs only while other legs can download the artifacts just fine.

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by kunalspathak** [comment] 2022-12-01 21:05
@BruceForstall

**Comment by ulisesh** [comment] 2022-12-01 21:23
Updated error message to track impact, thanks for reporting this @kunalspathak

**Comment by Chrisboh** [comment] 2022-12-05 17:44
@alexperovich what is the latest status of this?

**Comment by MattGal** [comment] 2022-12-07 00:57
@Chrisboh at Alex's request I've assigned this issue to myself as he won't be around for the rest of the year.  There seems to be no way to handle this in our own code other than _maybe_ by setting `DOTNET_CLI_USE_MSBUILD_SERVER=0` in builds where it's affected (in this case we've only seen it on SuperPMI, so probably not something to do to everyone's build).  Let's discuss in FR standup tomorrow AM.

**Comment by MattGal** [comment] 2022-12-13 17:42
Given the lack of hits of this, and that the problem is external to DncEng code I am closing this issue  If it comes back, we can explore setting DOTNET_CLI_USE_MSBUILD_SERVER=0 since that will end out of process communication which behaves differently on MacOS versus linux.

**Closed by MattGal** 2022-12-13 17:42 UTC
Labels: First Responder, Known Build Error
