### ISSUE TITLE
RequestFailedException: Service request failed. Status: 403 (This request is not authorized to perform this operation using this permission.)

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#11056] opened 2022-09-29 14:34 UTC
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=34525

### Build leg reported

coreclr  Pri0 Runtime Tests Run  OSX x64 checked / Send tests to Helix (Unix)

### Pull Request

https://github.com/dotnet/runtime/pull/76357

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "x-ms-error-code: AuthorizationPermissionMismatch",
    "BuildRetry": false
 }
 ```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[57154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=57154)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/57154/logs/72)|dotnet/roslyn#64824|
|[56814](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56814)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/56814/logs/93)||
|[56417](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56417)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/56417/logs/62)|dotnet/roslyn#64804|
|[56287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56287)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/56287/logs/1993)|dotnet/runtime#77052|
|[52971](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52971)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/52971/logs/79)|dotnet/roslyn#64740|
|[52258](https://dev.azure.com/dnceng-public/public/_build/results?buildId=52258)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/52258/logs/1033)|dotnet/runtime#76949|
|[50744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=50744)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/50744/logs/99)||
|[42483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=42483)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/42483/logs/518)||
|[37694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=37694)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/37694/logs/2271)||
|[35359](https://dev.azure.com/dnceng-public/public/_build/results?buildId=35359)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/35359/logs/78)||
|[35045](https://dev.azure.com/dnceng-public/public/_build/results?buildId=35045)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/35045/logs/63)||
|[34525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=34525)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/34525/logs/1285)||
|[34499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=34499)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/34499/logs/1968)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|4|13|

**Comment by MattGal** [comment] 2022-09-29 14:52
Added a bit of the error message, this looks like a super rare issue with Azure storage where the drop container's SAS URI received from the Helix API was not valid for the Helix SDK.  This happens many 10s of thousands of times a day so if it's reproducible at all it should get lots of hits.

**Comment by markwilkie** [comment] 2022-09-29 14:54
Thanks @MattGal !

**Comment by ulisesh** [comment] 2022-10-04 06:50
We will wait until the 7-Day hit count get down to 0 to close the issue

**Comment by MattGal** [comment] 2022-10-21 15:10
This keeps getting one-off hits, so I'm going to try to harden against it. 

Checking out the repo, this has ben reported multiple times and been ignored by the team:
https://github.com/Azure/azure-storage-net/issues/1040
https://github.com/Azure/azure-storage-net/issues/1012

Since none of them got listed as fixed, simply updating the dependency is unlikely to work.  Rather I will see if I can stick some retry logic in there.

**Comment by MattGal** [comment] 2022-10-21 16:04
@jkotas I have hardened against this in https://github.com/dotnet/arcade/pull/11364.   Once this merges and flows, this mode of failure won't happen; there will be multiple retries before giving up and giving up will simply print a warning.

One thing to note here is that the reason this is so rare, and the reason you're hitting this issue, very likely may be because you are uploading the same payload twice somewhere;  the code path in question can only hit if an HTTP 409 throws when uploading the payload (we then check if it exists and do nothing if so).   My change should make this non-fatal in all cases either way.

**Comment by MattGal** [comment] 2022-10-24 20:44
Given no hits since last Weds (10/19) and a mitigation merged into dotnet/arcade main, I am proactively closing this issue.  If you need a fix for this, directly taking a new Arcade update via darc command is the fastest way to get relief.

**Closed by MattGal** 2022-10-24 20:44 UTC
Labels: First Responder, Detected By - Customer, Known Build Error
