### ISSUE TITLE
Getting NETSDK1023 even when xunit.assert isn't implicitly referenced

### ISSUE THREAD

**Issue by bricelam** [dotnet/arcade#13798] opened 2023-06-12 20:28 UTC
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

After a130eb4216444f36a8966bd0c7ab97fa0d6ece6d, we're seeing some unusual behavior in the EF Core specification tests (tests that ship as NuGet packages for providers to use).

We have these lines in our csproj:

```xml
<Project>
  <PropertyGroup>
    <IsUnitTestProject>False</IsUnitTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.assert" Version="$(XUnitVersion)" />
    <PackageReference Include="xunit.core" Version="$(XUnitVersion)" />
  </ItemGroup>
</Project>
```

The error messages that started showing up after the arcade commit are as follows:

> D:\efcore\.dotnet\sdk\8.0.100-preview.6.23279.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.Shared.targets(152,5): error NETSDK1023: A PackageReference for 'xunit.assert' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [D:\efcore\test\EFCore.Specification.Tests\EFCore.Specification.Tests.csproj]
> D:\efcore\.dotnet\sdk\8.0.100-preview.6.23279.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.Shared.targets(152,5): error NETSDK1023: A PackageReference for 'xunit.core' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [D:\efcore\test\EFCore.Specification.Tests\EFCore.Specification.Tests.csproj]

However, if I comment out the `PackageReference`s I get compiler errors saying that it can't find xUnit.net types.

For now, I've worked around the issue by adding `<NoWarn>NETSDK1023</NoWarn>`, but it would be good to understand why `IsImplicitlyDefined="true"` is affecting this project when the package reference clearly isn't being added outside of the project.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment] 2023-08-24 20:46
@agocke can you help here?

**Comment by missymessa** [comment] 2023-09-21 19:31
ping @agocke :)

**Comment by agocke** [comment] 2023-10-05 22:51
Could I get a binlog from the efcore build? I looked through the source and the reason wasn't obvious.

**Comment by missymessa** [comment] 2023-10-19 20:13
@bricelam can you help @agocke help you? :)

**Comment by bricelam** [comment] 2023-10-20 16:46
Steps:

1. Clone dotnet/efcore
2. Search for *NETSDK1023* and remove it
3. Get a binlog

**Comment by AndriySvyryd** [comment] 2024-09-12 18:33
Also, when using CPM, adding this to `Directory.Packages.props`:
```
    <PackageVersion Include="xunit.assert" Version="$(XUnitVersion)" />
    <PackageVersion Include="xunit.core" Version="$(XUnitVersion)" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="$(XUnitRunnerVisualstudioVersion)" />
```

causes

```
error NU1009: The packages xunit.core;xunit.assert;xunit.runner.visualstudio are implicitly referenced. You do not typically need to reference them from your project or in your central package versions management file. For more information, see https://aka.ms/sdkimplicitrefs
```

**Comment by ericstj** [comment] 2024-09-13 21:12
Those are implicitly referenced here: https://github.com/dotnet/arcade/blob/bd749a18dd72b8fcb5257ae01a4faf6dd487cc5f/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.targets#L9-L11

Seems like those targets are imported here: https://github.com/dotnet/arcade/blob/bd749a18dd72b8fcb5257ae01a4faf6dd487cc5f/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.targets#L15-L23C6

I guess you're meant to just set XUnitVersion.  It seems this goes back to this change by @AndyGerlicher https://github.com/dotnet/arcade/commit/6b1db298190d3bdf97b26d223f0320256962e063 which explicitly mentions doing this to work better with CPM.

**Comment by AndriySvyryd** [comment] 2024-09-13 22:08
> I guess you're meant to just set XUnitVersion.

The problem is that we still need to reference those packages and set the version to avoid errors https://github.com/dotnet/efcore/blob/release/9.0/test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj#L62-L64

**Comment by agocke** [comment] 2024-09-14 01:38
As far as I can see, there's nothing strange about the Arcade usage of implicit package references here.

The two possible questions are: 
  1. Should Arcade have implicit package references?
  2. Is the implicit package reference behavior in NuGet correct?

Regarding (1), this configuration long predates my involvement, and the "official" support for implicit references seems to indicate this is a supported scenario. I don't see anything necessarily wrong with Arcade's behavior here.

For (2), this is a question for the NuGet team.

I'm closing this as not relevant for the Arcade repo. This can be re-opened as a NuGet issue if (2) is in question.

**Closed by agocke** 2024-09-14 01:38 UTC
Labels: area-Infrastructure-libraries
