### ISSUE TITLE
Helix sdk warnings about OutputPath not set

### ISSUE THREAD

**Issue by HaoK** [dotnet/arcade#1605] opened 2018-12-17 21:25 UTC
When using the helix SDK as part of our build i.e. `<Sdk Name="Microsoft.DotNet.Helix.Sdk" Version="1.0.0-beta.18614.1" />` we end up having to add `<SkipInvalidConfigurations>true</SkipInvalidConfigurations>` due to getting this warning:

```
D:\a\1\s\.dotnet\x64\sdk\2.1.500\Microsoft.Common.CurrentVersion.targets(781,5): warning : The OutputPath property is not set for project 'helix.proj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform=''.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\a\1\s\test\helix.proj]
```

**Comment by HaoK** [comment] 2019-02-16 03:41
Empty directory targets/props fix works, merged via https://github.com/aspnet/AspNetCore/pull/7373

**Comment by jonfortescue** [comment] 2019-02-18 20:16
Awesome to hear!

**Comment by pakrym** [comment] 2019-03-01 22:51
I don't think the workaround works anymore.

**Comment by jonfortescue** [comment] 2019-03-02 00:05
@alexperovich any ideas?

**Comment by alexperovich** [comment] 2019-03-02 00:16
I don't have any other ideas. There are probably some things getting imported that cause this problem from these imports: https://github.com/aspnet/AspNetCore/blob/master/eng/helix/helix.proj#L6.

**Comment by JunTaoLuo** [comment] 2019-04-17 01:40
Is there any update on this?

**Comment by markwilkie** [comment] 2020-03-26 15:16
This issue looks stale and not necessarily relevant anymore.  However, please feel free to reopen if those assumption are incorrect.

**Comment by Pilchie** [comment] 2020-05-26 18:43
We're trying to clean up our warnings, and this is a big chunk of them.  Tagging @dsplaisted - can you help us figure out how to structure the .proj file to avoid the warning?

**Comment by dsplaisted** [comment] 2020-05-26 23:34
It looks like you could run a target before `_CheckForInvalidConfigurationAndPlatform` that sets `_InvalidConfigurationWarning` to `false` to disable this warning.

**Comment by dougbu** [comment] 2020-05-27 04:59
@dsplaisted is setting a "private" property (`$(_InvalidConfigurationWarning)`) not a hack in your view? And, any chance of a first-class way to turn this output off?

**Comment by alexperovich** [comment] 2020-05-27 05:02
This shouldn't even be a problem. `dotnet msbuild` on a helix sdk project with no Directory.Build.props/targets affecting it doesn't cause this error. This is something caused by the build stuff around it.

**Comment by dougbu** [comment] 2020-05-31 05:49
@alexperovich I'm not sure what "build stuff around it" you mean. Our [eng/helix/Helix.proj](https://github.com/dotnet/aspnetcore/blob/master/eng/helix/helix.proj) project is in a directory with empty `Directory.Build.*` files that block our repo's root `Directory.Build.*` files and therefore any implicit Arcade SDK use. The project imports very little aside from a few properties and our [eng/Build.props](https://github.com/dotnet/aspnetcore/blob/master/eng/Build.props) file.

The root cause here is one or more of the following
1. The Helix SDK is based on neither the Arcade SDK nor .NET SDK files i.e. ProjectLayout.props and Microsoft.NET.DefaultOutputPaths.targets aren't imported
2. The Helix SDK doesn't provide an `$(OutputPath)` default
3. We're blocking too much and _should_ be using the Arcade SDK or our root `Directory.Build.*` files.
4. Our Helix.proj does not set `$(OutputPath)`
5. The `_CheckForInvalidConfigurationAndPlatform` can downgrade errors about an empty `$(OutputPath)` to warnings **but** can't be disabled completely (without the hack @dsplaisted mentioned)

Should we fix the Helix SDK, the .NET SDK, or our Helix.proj? If the last, should we be importing something from another SDK or defining `$(OutputPath)` ourselves?

----

BTW minimal repros are difficult given examples like https://github.com/dotnet/arcade/blob/2d9ac5e1016d7618cc2b262831b0430cf8e993c8/src/Microsoft.DotNet.Helix/Sdk/Readme.md#hello-world fail miserably at the command line.

**Comment by dougbu** [comment] 2020-06-01 19:12
I think we can close this issue. I filled the Helix SDK gap by defining `$(OutputPath)` in dotnet/aspnetcore@d2b3eecedb63 aka dotnet/aspnetcore#22395 and if nobody else is complaining&hellip;

**Closed** 2020-06-01 19:45 UTC
